### ISSUE TITLE
fileselect: navigation and resume

### ISSUE THREAD

**Issue by tehn** [monome/norns#1019]
on entry of fileselect, resume position:

- in param list, for existing file, start in folder of existing file
- in param list, if blank, start in global last-used folder
- generally, if no folder specified, use global last-used

unfortunately the fileselect logic will need to be rewritten, and the UI changed slightly.

- K2 cannot mean both "exit" and "back" at the same time
- `..` will need to be the top menu item
- K2 always means abort
- `/dust/` should remain the lowest-possible-root

---

rationale: loading a bunch of samples in parameter slots, it's nice if you don't have to re-navigate to the same folder.

**Comment by csboling** [comment]
Somehow did not see this ticket. Consolidating some thoughts / questions here about the desired behavior.

The behavior after merging https://github.com/monome/norns/pull/1137 is that selecting file params will go to the last folder where a file was chosen. K2 then means "go up a level", and if you go press K2 again when looking at the `dust/` folder this exits back to the EDIT PARAM menu. This basically was the smallest change that seemed workable.

* This issue suggests an actual `..` entry in the fileselect list and using K2 to cancel out completely. This makes sense I think.
* Comment in #402 suggests an optional argument to `params:add_file` to let you give a default root path for a file param. This would mean the fallback order is:
  1) folder containing the currently selected file for the param
  2) folder containing the last file that was selected with the fileselect menu
  3) script-provided folder passed to `params:add_file`
  4) `dust/`
* Should the last used path be remembered when changing scripts? Or does loading a script reset the initial directory to the default (param-specified folder || `dust/`)
* Probably TAPE file selection needs the same last-used behavior -- this maybe is covered by reopening the folder containing the currently selected file.
