### ISSUE TITLE
params:hide/show/visible returning unexpected results

### ISSUE THREAD

**Issue by dndrks** [monome/norns#1044]
running quick hide/show tests with params and getting unexpected results.
- `params:hide(1)` returns ok
- `params:visible(1)` returns true
- `params:show(1)` returns ok
- `params:visible(1)` returns false

- loading a new script (one which doesn't define visibility) doesn't reset `params:visible(1)` to true.
- a RESTART doesn't flip `params:visible(1)` to true -- it seems like it retains its last-defined state?

also including these in a script's `init()` doesn't seem to affect PARAMS menu visibility?

**Comment by tehn** [comment]
indeed this was clearly not sufficiently tested!

will get it working properly.
