### ISSUE TITLE
screen.lua errors if "option" param type receives non-".0" float

### ISSUE THREAD

**Issue by dndrks** [monome/norns#1055]
test script:
```
function init()
  params:add_option("test_option", "test option", {"one","two","three"},1)
end
```

- `params:set("test_option",2.0)` changes parameter as expected
- `params:set("test_option",2.1)` results in `screen.lua` errors:

```
lua: 
/home/we/norns/lua/core/screen.lua:215: bad argument #1 to 'screen_text_extents' (string expected, got nil)
stack traceback:
	[C]: in field 'screen_text_extents'
	/home/we/norns/lua/core/screen.lua:215: in field 'screen_text_right'
	/home/we/norns/lua/core/screen.lua:158: in function 'core/screen.text_right'
	/home/we/norns/lua/core/menu/params.lua:369: in function 'core/menu/params.redraw'
	/home/we/norns/lua/core/menu/params.lua:528: in field 'event'
	/home/we/norns/lua/core/metro.lua:169: in function </home/we/norns/lua/core/metro.lua:166>
```

I only noticed this because I'm working on OSC docs and it seems that TouchOSC can only send floats -- every so often, you can land on "2.0", but most of the time you're working with "1.934721028".

I have [an OSC touchup branch](https://github.com/monome/norns/tree/osc-touchup) that clamps received OSC values to integers if the param type is "option" -- but is there any value in addressing this elsewhere?

**Comment by tehn** [comment]
i'll check over the code for other clamping needs, thanks for spotting this
