### ISSUE TITLE
global clock: improve averaging function for midi/crow

### ISSUE THREAD

**Issue by dndrks** [monome/norns#1088]
potential user behavior:
- boot norns where global clock is set to `midi`
- their ext midi clock source isn’t sending signal, because they aren’t ready to play yet
- user makes a sandwich, comes back to the studio and then starts their midi clock source and try to use a script like the one below — a straight-forward sequencer that uses clock.sync(1/4) to clock a 16th pulse.
- it will take a long while to start executing steps, though -- because 20 minutes of no signal have been averaged.

to test:
- start with CLOCK set to internal , 120bpm
- let it run for 30 seconds or so
- switch CLOCK to midi (do not have your ext. midi clock source playing)
- return to script’s screen
- start your ext. midi clock source

_what i’m seeing_: counter/redraw stalls for quite a bit of time (typically 12-20 beats), even though beats are still executing

_what i expected_: clock would start averaging when it receives a start message and dump old history, taking only a beat to stabilize.

```
function init()
  task_id = clock.run(test_clock)
  count = 0
end
function test_clock()
  while true do
    clock.sync(1/4)
    count = count+1
  end
end
clock.run(function()
  while true do
    clock.sleep(1/60)
    redraw()
  end
end)
function redraw()
  screen.clear()
  screen.level(15)
  screen.move(0,10)
  screen.text(params:string("clock_source")..": "..count)
  screen.move(0,20)
  screen.text(string.format("%.2f",clock.get_beats()))
  screen.move(0,30)
  screen.text(string.format("%.2f",clock.get_tempo()))
  screen.update()
end
```

**Comment by tehn** [comment]
agreed. i can add some filters to greatly improve this

**Comment by catfact** [comment]
i'd try windowed median and windowed mean for jitter reduction

see `norns/lua/lib/filters.lua` for example algos if it helps
