### ISSUE TITLE
MIDI clock in - only from port 1

### ISSUE THREAD

**Issue by nattog** [monome/norns#1119]
At present Norns only can be clocked with MIDI from port 1 - it would be great to expand the choice to all 4 ports, to avoid having to potentially reassign devices. I imagine that the choice could present itself as when selecting MIDI clock output.

**Comment by okyeron** [comment]
Could you expand a bit on the details of your testing situation?

I'm building a midi monitor script and using the global clock system (`clock.run()`, etc.) I get midi clock OK with a device (Roland TR-09) sending clock from any vport.

However, MIDI clock tempo seems to get set in params regardless of which MIDI vport is being used in the active script. (active script is connected to device 1, but device 3 is sending clock, so params show device 3 tempo)

Perhaps `source` in`clock.set_source(source)` could be expanded to be `Internal, MIDI 1, MIDI 2, MIDI 3, MIDI 4, Link, Crow`? Or is that outside the intent of the clock system?

**Comment by tehn** [comment]
is there not a way to deactivate midi clock on the hardware that you don't want sending it?

**Comment by okyeron** [comment]
Depends on the device? 

The Roland TR-09 I'm testing with has 2 settings for clock sync "AUTO" and "INT" - in both cases clock is always being sent. In AUTO, it will defer to incoming clock if it detects it.

I could see an interesting use case for listening to multiple (different) midi clocks and switching between them. (maybe a "way out there" edge case?)

**Comment by tehn** [comment]
i think it makes sense to have the system specify which device clocks are watched vs. ignored. will figure out the best UI for this--- the clock param menu is getting clogged, so perhaps will put this in the upcoming "devices settings" menu

**Comment by tehn** [comment]
feature added
