### ISSUE TITLE
imported files using 'require' only update after reset

### ISSUE THREAD

**Issue by tlubke** [monome/norns#1120]
A mild inconvenience when working on a lib used in a script, norns has to be reset in order for file changes to be recognized in a case where it is being used with `require 'path'`.

**Comment by tehn** [comment]
use `include` instead: https://monome.org/docs/norns/faq/#what-is-the-difference-between-require-and-include

**Comment by ngwese** [comment]
The scripting reference section on libraries directs people to use `include` as well:
https://monome.org/docs/norns/script-reference/#libraries
