### ISSUE TITLE
default pset, and script-supplied psets

### ISSUE THREAD

**Issue by tehn** [monome/norns#1123]
- make sure pset data from dust/code/SCRIPT/data get copied to dust/data/SCRIPT
- clarify default script loading methods--- call `params.read(1)`

**Comment by dndrks** [comment]
just some data points from `Questions`: https://llllllll.co/t/norns-presets-on-boot/33592/1

it's interesting that the growth of the ecosystem + userbase has made "default states" more attractive -- that when someone loads a script, they either want it to be how they last saved it or they want to define the re-load state. it sorta feels like a Nintendo Switch, where norns is the main console but you want to pick up where you left off in an individual game.

**Comment by tehn** [comment]
cool! so we're talking about two issues:

1. definitely agree that some mechanism for auto-loading the last selected pset is smart. there isn't immediately a mechanism in place for this--- we'd basically have to write a new file in the data/script folder to save the last-loaded pset. i'd still want an explicit function to load the pset--- but perhaps a good syntax is no arg means load whatever was loaded last. rationale being i think there shouldn't be a whole lot of magic/unexpected behavior that could lead to confusion.

2. i'm interpreting this as a need for two tiers of pset. basically a global pset and a "numbered/dynamic" (currently) pset. this makes total sense. i'll introduce the third case (which was implemented in aleph) which is the "don't save this in the pset" flag for a param--- this is hugely effective for partial-list recall, which extends psets to a radically different use potential (ie, you can make a sequencer just with psets controlling a subset of params).

if each param had an additional attribute to specify its save-level (global, normal, off) we could navigate all this. i've hesitated in the past because it is an additional UI challenge.

**Comment by catfact** [comment]
maybe worth noting (to manage expectations) that since parameter actions are arbitrary functions, banging a preset doesn't necessarily restore state.
