### ISSUE TITLE
softcut crashing with position update in phase callback

### ISSUE THREAD

**Issue by okyeron** [monome/norns#1124]
I was trying some various things with softcut but I seem to have found a crashy bug. (tested on Shield and Fates)

Using softcut study 3 as an example, I changed some things to try and update `softcut.position()` in the phase callback.

[Gist here of code I used](https://gist.github.com/okyeron/6306469d1ae6a05b66f1d6e7c47b4ca4)

Turning encoder one will end up with the `pos` number going negative (stops printing at -348.875) and then softcut getting killed.

While this is probably buggy/bad code, it is crashing softcut reproducibly. RESET from norns menu gets things back to normal, but otherwise, there's no output or errors shown in maiden.

`journalctl -r` reports:

```
May 28 17:21:11 fates jackd[386]: JackAudioDriver::ProcessGraphAsyncMaster: Process error
May 28 17:21:11 fates jackd[386]: JackEngine::XRun: client = SuperCollider was not finished, state = Triggered
May 28 17:21:11 fates jackd[386]: JackEngine::XRun: client = crone was not finished, state = Triggered
May 28 17:21:11 fates jackd[386]: ClientNotify fails name = crone notification = 18 val1 = 1 val2 = 0
May 28 17:21:11 fates jackd[386]: Could not write notification
May 28 17:21:11 fates jackd[386]: CheckRes error
May 28 17:21:11 fates jackd[386]: Cannot write socket fd = 13 err = Broken pipe
May 28 17:21:11 fates jackd[386]: ClientNotify fails name = crone notification = 18 val1 = 0 val2 = 0
May 28 17:21:11 fates jackd[386]: Could not write notification
May 28 17:21:11 fates jackd[386]: CheckRes error
May 28 17:21:11 fates jackd[386]: Cannot write socket fd = 13 err = Broken pipe
May 28 17:21:11 fates jackd[386]: ClientNotify fails name = softcut notification = 1 val1 = 0 val2 = 0
May 28 17:21:11 fates jackd[386]: Could not write notification
May 28 17:21:11 fates jackd[386]: CheckRes error
May 28 17:21:11 fates jackd[386]: Cannot write socket fd = 13 err = Broken pipe
May 28 17:21:11 fates jackd[386]: JackAudioDriver::ProcessGraphAsyncMaster: Process error
May 28 17:21:11 fates jackd[386]: JackEngine::XRun: client = SuperCollider was not finished, state = Triggered
May 28 17:21:11 fates jackd[386]: JackEngine::XRun: client = crone was not finished, state = Triggered
May 28 17:21:11 fates jackd[386]: JackAudioDriver::ProcessGraphAsyncMaster: Process error
May 28 17:21:11 fates jackd[386]: JackEngine::XRun: client = SuperCollider was not finished, state = Triggered
May 28 17:21:11 fates jackd[386]: JackEngine::XRun: client = crone was not finished, state = Triggered
May 28 17:21:11 fates systemd[1]: norns-crone.service: Failed with result 'signal'.
May 28 17:21:11 fates systemd[1]: norns-crone.service: Main process exited, code=killed, status=6/ABRT
May 28 17:21:11 fates jackd[386]: JackAudioDriver::ProcessGraphAsyncMaster: Process error
```

**Comment by okyeron** [comment]
I just realized this is probably something with attempting to go out of range of the buffer. 

So how long is the buffer...? Checking lines I found:
>there are 2 buffers. each is 16777216 frames or ~350 seconds. this length is basically arbitrary but it is useful that it is a power of 2 (2^24.)

So when position hits 350 (or beyond the end of the buffer) it craps out.

**Comment by catfact** [comment]
yes, but we should not crash from an OOB positition value.

in any case, this is fixed in the upcoming softcut update. if we need a bandaid i would just clamp the position in seconds on the lua side.

**Comment by dndrks** [comment]
closing the loop -- this seems pretty well-fixed. executing `softcut.position(1,-348.875)` returns a clamped position value of `0.0` and executing `softcut.position(1,350)` returns a clamped position value of `349.5`.
