### ISSUE TITLE
pattern_time: firm up lib conventions and consider new functionality

### ISSUE THREAD

**Issue by dndrks** [monome/norns#1131]
### lib conventions

if using softcut as a standard, `pattern_time` could be improved by:
- replacing `rec_start() / rec_stop()` and `start() / stop()` with single functions that look to arguments for state, eg: `rec(x)`, `overdub(x)`, `play(x)`
- `time_factor` is a little unclear, perhaps could replace with `rate(x)`, where 0.5 is half-speed and 2.0 is double-speed (current is 0.5 == double-speed, 2 == half-speed)

we could also consider merging `next_event` into `play`, so that stepping through playback can be driven by the `clock` module.

### new functionality to consider

- a `loop` flag to allow 1-shot pattern playback
- `quantize` function that accepts a quantization size (and percentage?) processing times to the nearest division at the current bpm and generating a quantums value that would be useful for `clock` syncing
- expose start/end points, independent of the `count`

**Comment by tehn** [comment]
how is this looking? your in-progress version from awhile back seemed to be coming along well

**Comment by tehn** [comment]
@dndrks agreed this is a good musical library, and these added features would make it more so.

with the possibility of v3 moving specialized libs to external repos i do think we could consider keeping this one as core if we improve it (and possibly rename it? don't really like the underscore... maybe the rename could also alter the scope a bit.)

**Comment by dndrks** [comment]
this was all solved with https://github.com/monome/norns/pull/1713
