### ISSUE TITLE
parameter input quantization

### ISSUE THREAD

**Issue by catfact** [monome/norns#1144]
currently, `paramset:delta` is hard-coded to increment in steps of 1/100 of the range (`maxval - minval`), times the increment. 

in scripts, its possible to scale the input to the delta arbitrarily, but in menus one is stuck with a quantum of 0.01 times the range (or 0.0005 in "fine" mode.) this is usually fine but sometimes inconvenient.

it might be nice to add an input quantum to `ControlSpec`, as well as an output quantum (the `step` field), so that this can be controlled more specifically.

**Comment by ngwese** [comment]
i believe i’ve run into this limitation as well but i hadn’t yet dug into what made parameters manipulated via the menu system feel different than when manipulating within the script
