### ISSUE TITLE
international keyboard support

### ISSUE THREAD

**Issue by catfact** [monome/norns#1145]
non-US keyboard layouts are not respected by keyboard-centric scripts such as Orca. this is a norns system limitation. 

norns isn't using a linux system layer (like a virtual console, Xorg or Wayland) to get _symbols_ from the kernel. it is going directly for _keycodes_ from the HID events stream.

scripts like Orcae make use of the named enumeration of HID codes that we made here, in the norns system HID layer:
https://github.com/monome/norns/blob/master/lua/core/hid_events.lua#L8

these enumeration names assume US keyboard layout, i think. that would probably be the best place to define other layouts for different regions; scripts could continue to use the the named enums without tracking keyboard layout.

contributions would definitely help here. IIRC the tool that made these mappings from `libudev` was rather ad-hoc, but i could try and clean it up and make sure it is available in the norns repo for anyone who would like to contribute other layout data.

**Comment by catfact** [comment]
maybe a better alternative: we could have matron use a virtual console (or something?) to get symbol events from the kernel, in addition to HID events, and scripts could use either one as appropriate.

**Comment by okyeron** [comment]
Looks like the current event code mapping was created directly from the libevdev source:
https://gitlab.freedesktop.org/libevdev/libevdev/-/blob/master/include/linux/input-event-codes.h

I *think* we'd need to create alternate event name map tables for AZERTY/QWERTZ/etc.

Maybe something like replacing `hid_events.codes` with `hid_events.keyboards.qwerty` and then setting a default where `hid_events.codes = hid_events.keyboards.qwerty` but allows for an override somewhere in a preference/param?

QMK (open source keyboard software) looks like it does something similar with [a keyboard map header for specific languages](https://beta.docs.qmk.fm/using-qmk/simple-keycodes/reference_keymap_extras)

[I found this Google/Chrome dev update/article](https://developers.google.com/web/updates/2016/04/keyboardevent-keys-codes) a very friendly way of describing what happens with the Code and Key attributes

**Comment by artfwo** [comment]
> maybe a better alternative: we could have matron use a virtual console (or something? not sure how to do this myself) to get symbol events from the kernel, in addition to HID events, and scripts could use either one as appropriate.

console input will also introduce a few issues to handle:

* layout setup. on debian systems you change it by dpkg-reconfiguring keyboard-configuration and console-setup packages. this requires logging in, running some commands and answering non-trivial questions such as "what's your compose key?".
* layout switching. the default switching mechanism may not work unless the user is logged in as well, so matron might have to handle the (different) layout changing shortcuts here.

in addition to:

* character display: not all fonts in matron can display non-ASCII characters.

however, as somebody using a non-US keyboard 100% of the time, i'm wondering if this improvement is actually worth the effort. this limitation you describe has typically never been a problem in other environments - when a keyboard is used for _control_ input (games, DAWs, emacs commands) or _code_ input. text input in native languages would be nice to have, but goes slightly beyond the purpose of norns and can be easily solved on the script level for all the potential edge cases.

**Comment by catfact** [comment]
yeah on balance it seems better to just stick with the HID codes and add new layouts there as needed. hopefully keyboard-heavy script contributors can help with this; it's as simple as you say @okyeron.

**Comment by catfact** [comment]
this topic has come up at least a couple more times so i am trying to direct interest to this issue.

one thing worth clarifying: please correct me if i'm wrong, but as i understand it the setting in `/etc/default/keyboard` affects only virtual console and X programs, which receive character code input from `kbd`. 

i think we've established that the lower-hanging solution is not to implement a virtual console within `matron` (yuck)  but to simply add more keycode tables. this could all be done in lua.

additionally @tehn has expressed a desire for a higher-level abstraction wrapping `hid` in lua, in which (i suppose) one can set a callback with string input, and automatically detect keyboard devices.

most of this can be done in lua. keyboard detection might need to be in matron C sources.

**Comment by catfact** [comment]
this might be helpful: the QMK source includes lists of _aliases_ for many languages. 
https://github.com/qmk/qmk_firmware/blob/master/quantum/keymap_extras/

one way forward would be to scrape these headers and create something that looks like, say:

```
hid_events.codes_colemak.KEY_P = hid_events.codes.KEY_R
...
```

**Comment by tyleretters** [comment]
i like the idea to add keycode tables.

"automatically detect keyboard devices" - meaning keyboards smart enough to self-identify?

**Comment by catfact** [comment]
apologies; i'm muddying the waters with what should be a new issue (or 2.)

 @tehn expressed desire for a higher-level keyboard interface in lua, which would automatically be used when a device supporting keyboard interface is connected. whereas now, we don't distinguish between different HID classes. such a distinction would have to happen at a lower level.

**Comment by tyleretters** [comment]
#1251 is beyond my skill level for now. if that seeks to "provide the keycode decoding by default" then perhaps this issue is superfluous? or would it still be valuable to do the lua conversion tables?

**Comment by catfact** [comment]
IMHO: it would still be valuable to do the lua conversion tables. i would implement new "keyboard" module as a higher-level wrapper around the existing low-level lua HID module. changes at the C level would simply facilitate choosing the appropriate script-level interface in lua for a given device. (e.g.: keyboard, mouse, gamepad, other.)

**Comment by tyleretters** [comment]
alright, i'll try to sketch out one table and report back for feedback

**Comment by tyleretters** [comment]
proposal:

1. configuration - @catfact floated the idea of a configuration file. i propose adding another item at the bottom of SYSTEM > DEVICES > HID which allows the user to scroll through avialable keyboard locales. only one can be selected at a time and it defaults to US-ANSI.

2. architecture / organization - similar to the [qmk](https://github.com/qmk/qmk_firmware/tree/master/quantum/keymap_extras) files, we can have one `.lua` file per locale. tables inside these files would be very flat and would contain the aliases.

3. usage - extend/modify `keyboard` to use information as defined in point 1, maps and then aliases from point 2. developers can access the output this with something like `keyboard.localized(type, code, val)`. this will mirror (and can be used in tandem with) `keyboard.event(type, code, val)`.

 open to feedback!

**Comment by tehn** [comment]
`SYSTEM > DEVICES` should remain exclusively for selection.

there's already a ticket open for device-settings expansion (ie, grid rotation, midi passthru): https://github.com/monome/norns/issues/1129

FYI (soon) "SYSTEM" will be renamed "SETTINGS"

we could just have another submenu, or reimagine the entire SETTINGS menu system if needed

---

but generally, yes, manual selection of a list of locales which are just lua files.

**Comment by p3r7** [comment]
i guess this ticket could be closed now.
