### ISSUE TITLE
FR: maiden's catalogs refresh automatically

### ISSUE THREAD

**Issue by dndrks** [monome/norns#1159]
while it's documented that users need to refresh the community catalog to pull in new scripts, it often requires reiteration. eg: https://llllllll.co/t/grd/33768/63

curious if there's a way to automatically refresh the catalog once a network is detected, or once the user connects to maiden, so that any scripts which might have been released while the user was offline are presented without additional actions from the user?

**Comment by tehn** [comment]
moved to https://github.com/monome/maiden/issues/184
