### ISSUE TITLE
FR: add tag-centric actions to maiden's project manager

### ISSUE THREAD

**Issue by dndrks** [monome/norns#1160]
current behavior: tags like `grid`, `arc`, and `drum` are informational. the user can visually scan or do a quick string search to find scripts with certain tags, but this is all manual.

proposed behavior: tags become more functional, so a user could click on a tag and see only the `drum`-tagged scripts.

this would also help solve a discontinuity that's starting to occur in the community, where folks are creating Library threads for pre-release scripts which they don't feel comfortable submitting to the project manager because they're still in public beta. for example: if scripts with a `beta` tag could be toggled visible, this would create continuity for users (they download all scripts from one place, without having to use direct file management) and would likely give developers more testers.

**Comment by tehn** [comment]
moved to https://github.com/monome/maiden/issues/185
