### ISSUE TITLE
add params/toggle

### ISSUE THREAD

**Issue by andr-ew** [monome/norns#1166]
proposing a new param type exactly like `trigger`, but stores a boolean and toggles on key press in the menu

certainly `option` can accomplish a similar thing - my particular use case is working on a screen UI builder tool and wanting to let the user input params - in this case I'd need to draw `option` different from `toggle` so there'd be an awkward workaround to detect  which case is which (& maybe this helps clear the way for midi button / foot switch mapping in the menu!)

**Comment by andr-ew** [comment]
for context check out wrms

https://github.com/andr-ew/wrms/blob/master/wrms.lua

I'm kind of replicating the params functionality, and it would be nice to stick with the norns syntax for consistency, but the catch is no toggles

**Comment by tehn** [comment]
feel free to PR this proposal, it's a good first delve into the norns codebase
