### ISSUE TITLE
Clock module function reference docs out of date

### ISSUE THREAD

**Issue by okyeron** [monome/norns#1176]
I've been doing various things with midi clock this past week and it seems the clock module function reference docs are a bit out of date/wrong at https://monome.org/norns/modules/clock.html  (this appears to be the same for the on-device docs on the most recent Shield Update)

As best I can tell:
`stop()` is now `cancel()`

`set_source (source)` now takes an integer value 1-4 for INTERNAL, MIDI, LINK, CROW

`clock.INTERNAL` and `clock.MIDI` (mentioned in current docs) no longer exist?

Functions in `clock.lua` which are missing from the docs:

`clock.create`
`clock.suspend`
`clock.resume`
`clock.get_beats`
`clock.get_tempo`
`clock.get_beat_sec`

Callbacks:
`clock.transport.start`
`clock.transport.stop`

**Comment by tehn** [comment]
doc overhaul is in progress, we're aware of the holes
