### ISSUE TITLE
add params/momentary (or perhaps gate)

### ISSUE THREAD

**Issue by andr-ew** [monome/norns#1181]
in the same spirit of #1166 

a trigger-like param, but `action` is called twice per key press (on & off edges). I usually call this behavior "momentary" but some people also call it "gate" (?)

will happily PR as before (assuming the proposal looks good)!

**Comment by tehn** [comment]
i do not believe the param system and current params UI is equipped to deal with this, so i suspect any implementation would end up being a somewhat messy hack

i also believe (if you map a footswitch, for example) that this functionality is achievable with an OPTION type. so what you're really suggesting is basically a param menu UI element?

if you arrive at a clean implementation do PR it for review. in the meantime i'm not going to keep this open as an issue, as i'm attempting to limit the quantity of open feature requests in the issue tracker.
