### ISSUE TITLE
support multiple screen backends

### ISSUE THREAD

**Issue by csboling** [monome/norns#1187]
To facilitate running norns on a desktop or other hardware, it is desirable to have matron be able to render to different types of displays besides the linux `/dev/fbX`. This issue is intended for discussing the design of this functionality and implementation approaches. My prototype branch is [here](https://github.com/monome/norns/compare/main...csboling:decouple-fb).

Use cases include:
- working on matron and lua without norns hardware
- having a virtual interaction mechanism for scripting and demos -- you could capture a screen recording on your PC demonstrating a script UI
- running norns on a PC for connecting to your DAW through JACK, etc?

Design issues include:
- what back ends are important? SDL and "in the browser" seem like good candidates
- how to configure what screens / options to use? @catfact made the suggestion of spinning up a separate lua VM for evaluating lua configuration and stopping it before weaver starts, which sounds quite broadly useful in matron.
- how best to structure the browser interaction? My thought right now is having matron spawn its own websocket server as a UI control interface that the maiden browser app can interact with in a similar fashion to the matron / supercollider ws-wrapper REPLs (I have the maiden side of this working on a branch here somewhere). Another option would be to have matron push data to/from the maiden go server and then from there to the browser somehow.

Interacts with https://github.com/monome/norns/pull/1052

**Comment by Prosperoh** [comment]
I started working on some modifications to make it more easy to use on my local machine, picking up from where @csboling started, [branch here](https://github.com/Prosperoh/norns/tree/decouble-fb-modif). For now, the possibility to render on a bigger SDL window, and some fixes to the events.

**Comment by tehn** [comment]
fixed by #1444
