### ISSUE TITLE
er.gen(0, 16) == er.gen(1, 16)

### ISSUE THREAD

**Issue by tyleretters** [monome/norns#1189]
- expected behavior: providing er with a value of `0` for pulses returns a table where all booleans are false.
- actual behavior: providing er with a value of `0` for pulses returns a table where the first boolean is true.

if this is actually an issue and not intended behavior i can make a pr to resolve it.

**Comment by tehn** [comment]
your expectation is correct, though i'm confused how 0 would be creating a true value given playfair/etc work as expected?

**Comment by tyleretters** [comment]
```
er = require("er")

t = er.gen(0, 16)

for k,v in pairs(t) do
  print(v)
end
```
yields
```
true
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
```

**Comment by tehn** [comment]
yikes that is definitely wrong :)

**Comment by catfact** [comment]
you're right, this degenerate case was not handled.

trivial fix

**Comment by tyleretters** [comment]
yay! thank you!!
