### ISSUE TITLE
TAPE overwrites old takes by default after reboot

### ISSUE THREAD

**Issue by madskjeldgaard** [monome/norns#1197]
Hi!

Something that surprised me when I got into using Norns recently was that the tape feature (which I love!) overwrites old takes by default. I would expect it to look for existing tapes and increment file number index from the highest existing take before recording.

Thanks for your hard work

(tested on Fates)

**Comment by dndrks** [comment]
hi mads,

hope all's well!

this has been [reported previously](https://github.com/monome/norns/issues/1026) and was [solved](https://github.com/monome/norns/pull/1027), with an [additional protection](https://github.com/monome/norns/pull/1173). if you are on `200712`, it might be good to ping @okyeron, as this isn't reproducible on stock or shield.

**Comment by okyeron** [comment]
Mads, I'll send you a message on lines with some possible update info. There was an error in the `200712` update but I thought it only affected controlspec changes.

**Comment by madskjeldgaard** [comment]
Thanks a lot everyone and sorry for reposting a solved issue ! 




On Wed, Sep 16, 2020 at 8:00 PM +0200, "Steven Noreyko" <notifications@github.com> wrote:















Mads, I'll send you a message on lines with some possible update info. There was an error in the 200712 update but I thought it only affected controlspec changes.
