### ISSUE TITLE
negative resonance settings crash softcut

### ISSUE THREAD

**Issue by lylepmills** [monome/norns#1209]
I ran the following on a whim to see what would happen -

```
softcut.post_filter_rq(1, -0.01)
```

In doing so I managed to crash softcut badly enough that (after some brief, very loud, self-oscillation) it didn't make any more sound. Nothing short of a hard reset by pressing the button on the back of the norns was enough to get it back to a good state (I tried things like `softcut.reset()`, soft resets, etc).

It seems like there should be some protection against this?

**Comment by tehn** [comment]
fixed by #1211
