### ISSUE TITLE
201023: crow showing as a MIDI device, not usable

### ISSUE THREAD

**Issue by dndrks** [monome/norns#1217]
reported at https://llllllll.co/t/norns-update-201023/37646/25.

to repro:
- plug a crow into norns while monitoring in maiden
- crow does not trigger the typical "telephone line" message in maiden
- crow shows up as a MIDI device under DEVICES > MIDI: `crow: telephone line`
- subsequent plug/unplug shows as `crow: telephone line 2`, `crow: telephone line 3`, etc
- crow is not addressable by norns via CLOCK > crow output

@ngwese , unsure if this is related to the virtual MIDI work?

**Comment by ngwese** [comment]
could be related to those changes but ???? not sure how. will investigate this evening

**Comment by ngwese** [comment]
early investigation indeed shows the virtual midi commit is the source of the bug. will work on a fix asap
