### ISSUE TITLE
norns.script.load(norns.state.script) changed behavior?

### ISSUE THREAD

**Issue by tyleretters** [monome/norns#1238]
- updated to 201113
- launch awake
- in maiden-repl, type `norns.script.load(norns.state.script)`
- press return

**expected result**
awake reloads as if it were just launched for the first time

**actual result**
script reloads but we also return to norns menu, encoders are not responsive until k1 is pressed

**Comment by tyleretters** [comment]
i've been able to reproduce this on several applications. i can also confirm that it isn't just a `screen` / redraw issue - the encoders are *not* sending data to the script and updating values in the background.

**Comment by tehn** [comment]
thanks for the heads up, fixing now

**Comment by tyleretters** [comment]
thank you for the quick fix!!
