### ISSUE TITLE
allow midi map/learn for taper parameters

### ISSUE THREAD

**Issue by catfact** [monome/norns#1241]
i  haven't been keeping up with these features, but it seems like parameter types now need to be explicitly made mappable in the param type class. this isn't happening for `Taper`, which is a pretty serious limitation.

seems like easy fix... is it enough to add something like 

```
Taper.new(...)  
   local o =... 
   ...
   if allow_pmap == nil then o.allow_pmap = true else o.allow_pmap = allow_pmap end
```

?

i also may be misunderstanding something, this report is hearsay

**Comment by ngwese** [comment]
i’ll take a look, likely due to the bit i added to which allows one to prevent params from being mapped if need be. i thought i had done it in a compatible manner but will double check.

**Comment by jasonw22** [comment]
I wonder if there's a larger issue? Just got a new 16n and went to try mapping grain size and density in angl but they weren't mappable.

**Comment by ngwese** [comment]
it looks like angl user taper parameters almost exclusively.

https://github.com/tehn/ash/blob/master/angl.lua#L120

**Comment by jasonw22** [comment]
@ngwese i tried applying the patch from this commit manually to my local norns (which is up to date) but the angl params still aren't mappable. Is there anything else I should do?

**Comment by tehn** [comment]
@jasonw22 i just checked and mine seems to be mappable. did you do a SYSTEM > RESTART after `git pull`?

**Comment by jasonw22** [comment]
If you mean SYSTEM > RESET, yes. However I didn't do a git pull, I just patched the two files mentioned in the commit, manually.

**Comment by tehn** [comment]
can you try a pull so your system is on latest main? seems to be working fine here.

**Comment by jasonw22** [comment]
`git pull` in `/home/we/norns`, followed by SYSTEM > RESET resulted in a hang on the resulting screen saying `reset`. Did a hard reset and the menu never comes up, but I can still SSH in.

**Comment by tehn** [comment]
you'll need to:

cd norns
git pull
./waf

or, since you already pulled, try

norns/edge.sh

(which automates the above)

**Comment by jasonw22** [comment]
Thanks for the extra help. Unfortunately, I seem to be having some issues. 

```
10.0.0.23 ~/norns $ ./edge.sh
Already up-to-date.
Setting top to                           : /home/we/norns 
Setting out to                           : /home/we/norns/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for 'alsa'                      : yes 
Checking for 'libudev'                   : yes 
Checking for 'libevdev'                  : yes 
Checking for 'liblo'                     : yes 
Checking for 'cairo'                     : yes 
Checking for 'cairo-ft'                  : yes 
Checking for 'lua53'                     : yes 
Checking for 'nanomsg'                   : yes 
Checking for 'avahi-compat-libdns_sd'    : yes 
Checking for 'sndfile'                   : yes 
Checking for libmonome                   : yes 
Checking for supercollider               : yes 
Checking for program 'dpkg-architecture' : /usr/bin/dpkg-architecture 
Checking boost includes                  : 1.62.0 
'configure' finished successfully (2.465s)
Waf: Entering directory `/home/we/norns/build'
[ 1/58] Compiling third-party/link-c/ableton_link.cpp
[34/58] Compiling maiden-repl/src/page.c
[35/58] Compiling maiden-repl/src/pages.c
[36/58] Compiling maiden-repl/src/ui.c
In file included from ../maiden-repl/src/pages.c:1:0:
../maiden-repl/src/page.h:7:21: fatal error: ncurses.h: No such file or directory
 #include <ncurses.h>
                     ^
compilation terminated.

../maiden-repl/src/page.c:2:21: fatal error: ncurses.h: No such file or directory
 #include <ncurses.h>
                     ^
compilation terminated.

../maiden-repl/src/ui.c:9:19: fatal error: panel.h: No such file or directory
 #include <panel.h>
                   ^
compilation terminated.
```

**Comment by tehn** [comment]
@jasonw22 apologies for all of the trouble, i didn't realize this was such a pain

get ncurses this way:

sudo apt-get install libncurses5-dev libncursesw5-dev

then re-run the compile

**Comment by jasonw22** [comment]
Thanks so much! Norns is functional, and taper parameters are mappable.
