### ISSUE TITLE
parameter mapping: 'out' range doesn't facilitate floats

### ISSUE THREAD

**Issue by dndrks** [monome/norns#1249]
from [this thread / post](https://llllllll.co/t/norns-param-map-screen/32352/5):

a mapped control's `out` range is definable by integers only, which works well for certain types of parameters (options, binary on/off, etc). however, parameters with float ranges between 0 and 1 or which have musical needs for floats (cutoff frequency, etc) are not able to be mapped in useful ways.

**proposed behavior**: K3 + E3 on `out` range could add the same fine-tune precision offered on the standard parameter screen, allowing users to set a range of floats to which their `in` values map.

**Comment by tehn** [comment]
additionally/alternatively, the PMAP screen could properly detect the param
type and do float vs. int
