### ISSUE TITLE
parameters > edit screen can be made inaccessible after manual script clear

### ISSUE THREAD

**Issue by dndrks** [monome/norns#1261]
## repro steps

- connect to maiden for error monitoring
- load a script with parameters (awake works well)
- navigate to PARAMETERS > EDIT
- use E2 to scroll down deep into the script's params (eg. on awake, nav down to `probability`)
- turn E1 CCW navigate to main menu and CLEAR script with K1+K3
- try to turn E1 CW to navigate back to PARAMETERS > EDIT

**experienced behavior**
- screen will seemingly stay stuck on main menu (I think it does move to PARAMETERS > EDIT, but can't render due to below)
- maiden prints:
```lua
lua: /home/we/norns/lua/core/paramset.lua:357: invalid paramset index: 56
stack traceback:
	[C]: in function 'error'
	/home/we/norns/lua/core/paramset.lua:357: in function 'core/paramset.lookup_param'
	/home/we/norns/lua/core/paramset.lua:301: in function 'core/paramset.t'
	/home/we/norns/lua/core/menu/params.lua:410: in function 'core/menu/params.redraw'
	/home/we/norns/lua/core/menu/params.lua:608: in field 'event'
	/home/we/norns/lua/core/metro.lua:169: in function </home/we/norns/lua/core/metro.lua:166>
```
- turn E2 CCW and you'll suddenly see the PARAMETERS > EDIT menu
- turn E2 CW, but you won't be able to navigate past REVERB
- if you try to press K2 to back out to parent PARAMETERS menu with REVERB selected, you won't be able to and maiden will print additional errors about an `invalid paramset index`
- you'll need to turn E2 CCW to resurface the params and select LEVELS
- you can now press K2 to back out to parent PARAMETERS menu
- select EDIT and everything is now sorted

**Comment by tehn** [comment]
seems like a manual script clear should just reset the position of the param views. do you want to try to tackle this? could be a one-line fix, and you'd learn how the menu works a little :)

**Comment by tehn** [comment]
also--- this is a pretty wild edge case given script CLEAR is not a common state which would require param nav... but agreed, it should be fixed
