### ISSUE TITLE
FR: add multi-device MIDI output to global clock

### ISSUE THREAD

**Issue by dndrks** [monome/norns#1275]
from https://llllllll.co/t/norns-clock/30738/104

currently, users can only send MIDI clock from the global clock to a single output. this is fine if folks are working with devices which can be daisy-chained, but more and more gear is made with USB-MIDI only which makes passing clock through multiple devices difficult/impossible.

it could be useful to offer this sort of multing inside of norns itself, perhaps as a context menu inside similar to SYSTEM > DEVICES > MIDI, where many devices can be specified as recipients of MIDI clock out. to avoid introducing a nested menu inside of a nested menu (introducing a new menu paradigm), this could maybe manifest as a list of ports (1-16) with simple "yes/no" toggles.

**Comment by tehn** [comment]
we should have a discussion re: SYSTEM DEVICES 3.0 update, which should have per-device config. we could add some clock args here.

**Comment by dndrks** [comment]
@artfwo , does expanding the MIDI out section of `PARAMS > CLOCK` feel like it's in scope of the recent clock work? realizing we can maybe two-birds-one-stone this with the recent conversations we've been having about clock management.

**Comment by artfwo** [comment]
this gist can technically be packaged as a module, where a simple require('...') would load the params and start the midi send coroutine, so potentially scripts that need this functionality can have it close at hand, and others wont, keeping the params menu a bit cleaner?
