### ISSUE TITLE
grid module C code assumes 4 quads on device

### ISSUE THREAD

**Issue by catfact** [monome/norns#1307]
the implementation of grid refresh in `device_monome.c` always assumes 4 quads of LEDs.

after a call to `g.all()`, all four quads are marked dirty, so 4x map messages will be sent on `refresh`.

this doesn't appear to cause any problems with most devices, but it seems like older/slower grid models might respond strangely. (flickering, etc.)

so we should probably teach `device_monome` to respect device size.

**Comment by catfact** [comment]
come to think of it, it would probably be a good idea to switch `/led/level/map` for `/led/map` on monobright devices. (though, i don't think libmonome directly exposes a query for monobright...)

**Comment by artfwo** [comment]
libmonome automatically translates `led_level_map` to `led_map` on monobright devices. why would you want to implement the brightness conversion in the client (matron)?

p. s. it's also possible to detect the varibright (mext) devices by id - it will always be mNNNNNNN or `^m\d+$`

**Comment by catfact** [comment]
ok thanks. i hadn't got as far as looking in the protocols. so: i wouldn't!

**Comment by dndrks** [comment]
fixed in #1358 <33
