### ISSUE TITLE
rebuilding group menu after change in visibility

### ISSUE THREAD

**Issue by schollz** [monome/norns#1319]
**what i'm trying to do specifically**:

i have a "scene" parameter in a group that will hide a bunch of parameters in that group and unhide a bunch of other parameters in the same group. i'm trying to use this "scene" parameter in the parameters menu, within a group.

**what is expected:**

i'd like the "scene" to toggle an action which hides/unhides parameters and then the parameter menu refreshes with newly updated visibility.

**what happened:**

the parameters in the group do not refresh unless you go out and back into the group.

**the code i'm using:**

the snippet for scene changing essentially looks like this (full code [here](https://github.com/schollz/granchild/blob/scenes/granchild.lua#L44-L52)):

```lua
  params:add_group("sample "..i,47)
  params:add_option(i.."scene","scene",{"a","b"},1)
  params:set_action(i.."scene",function(scene)
      for _,param_name in ipairs(param_list) do
        params:hide(i..param_name..(3-scene))
        params:show(i..param_name..scene)
        local p = params:lookup_param(i..param_name..scene)
        p:bang()
      end
  end)
  ...
```

but if you change a scene while in the group menu, you currently have to log out of the group menu and back into it to see the visibility of parameters swap (and update the correct indices).

**a possible fix:**

one way to fix this is to breakout the [build_sub(sub)](https://github.com/monome/norns/blob/main/lua/core/menu/params.lua#L163) function so that it can be toggled in an action.

here's a diff that does that:

```diff
diff --git lua/core/menu/params.lua lua/core/menu/params.lua
index e777120..891580d 100644
--- lua/core/menu/params.lua
+++ lua/core/menu/params.lua
@@ -11,6 +11,7 @@ local m = {
   pos = 0,
   oldpos = 0,
   group = false,
+  groupid = 0,
   alt = false,
   mode = mSELECT,
   mode_prev = mSELECT,
@@ -120,6 +121,12 @@ local function write_pset(name)
   end
 end

+m.rebuild_sub = function()
+  if page ~= nil and m.group then
+    build_sub(m.groupid)
+     _menu.redraw()
+  end
+end

 m.key = function(n,z)
   if n==1 and z==1 then
@@ -163,6 +170,7 @@ m.key = function(n,z)
         build_sub(i)
         m.group = true
         m.groupname = params:string(i)
+        m.groupid = i
         m.oldpos = m.pos
         m.pos = 0
       elseif t == params.tSEPARATOR then
```

and then i simply add

```
_menu.m.PARAMS.rebuild_sub()
```

at the end of my action to get it to rebuild and refresh that group menu.

is there another way to do this? is this worth a PR? if so, how should i modify this patch to conform to something kosher (using `_menu.m.PARAMS.rebuild_sub()` doesn't seem kosher)?

**Comment by tehn** [comment]
definitely want to avoid calling complex global sub-functions from scripts--- i don't want a super-nested page function to be considered future-proof API

an acceptable (though still somewhat tentative feeling) solution would be to introduce `_menu.rebuild_params()` which calls the sub-function

i'd accept a PR for this
