### ISSUE TITLE
callback for saving/loading parameters

### ISSUE THREAD

**Issue by schollz** [monome/norns#1325]
I'd like to be able to run arbitrary code after `ParamSet:read` or `ParamSet:write`, whether it is invoked via the `PSET` menu, or whether it is invoked manually. 

i have several use-cases that this would be useful:

- after reading a `PSET` I'd like to reset certain parameters
- after reading a `PSET` I'd like to load softcut buffers corresponding to that save
- after writing a `PSET` I'd like to dump softcut buffers corresponding to that save

i'm pretty sure it would be useful for others too. a common workaround pattern is to avoid `PSET` by making [custom `save/load` menus](https://github.com/schollz/barcode/blob/master/barcode.lua#L59-L72) (I do this a lot) in order to customize the saving/loading process. another pattern i've seen is to [rewrite the pset.write/read function](https://github.com/tlubke/shapes/blob/midi-cc/shapes.lua#L605-L627) to inject a callback.

what I'm thinking would be most useful is two new `ParamSet` class variables that contain callback functions that can be set using `ParamSet:set_callback_write` and `ParamSet:set_callback_read`. then at the end of `ParamSet:read/write` those functions would run if not nil.

another option would be to directly add callbacks to the functions, e.g. `ParamSet:read(filename, name, callback_fn)`...but this is not ideal for my use-case when someone saves/loads via the `PSET` menu (whereas the former option does).

is this appropriate for a PR? or is there is a way to already do this?

**Comment by tehn** [comment]
i think your first suggestion makes sense (and as you say, the second suggestion accomplishes nothing new).

looking forward to a pr!

**Comment by catfact** [comment]
nice
