### ISSUE TITLE
system update gets stuck

### ISSUE THREAD

**Issue by nerone** [monome/norns#1334]
there is an issue when right after norns shield boot SYSTEM -> UPDATE is launched, it gets stuck at "checking for update..." and nothing happens. returning back and relaunching UPDATE does not matter.
my guess this could be related to wifi connection not being established at the moment when UPDATE action is triggered the first time.

**Comment by dndrks** [comment]
hi @nerone ! hope all's well :)

i'm unable to repro this issue -- but combined with your other report (#1333 ), I'm wondering if there isn't a legitimate WIFI issue within your setup.

- is the IP address visible via the K2 toggle before you initiate UPDATE?
- if not, does navigating to WIFI and getting the IP address to appear (as described in #1333) then allow for UPDATE to run?

**Comment by nerone** [comment]
@dndrks all good, thanks : ]

i was able to do some tests and found that the problem is specific to my setup, specifically to my LTE router (my guess due to high ping — checking for update takes around 5–10 seconds). i also tried update check with another non-LTE router and norns did it almost instantly.
