### ISSUE TITLE
inconsistent audio level state (engine -> softcut, etc)

### ISSUE THREAD

**Issue by catfact** [monome/norns#1336]
there are a number of reports where user needs to "goose" audio levels ,such as here:

https://llllllll.co/t/orca/22492/575?u=zebra

i believe the problem goes away when state is saved and recalled, but is present after a RESET or otherwise wiping the persisted state.

my vague theory:

- the initial state of the DSP parameters is silence, but default state of widgets is 0db. 
- this has always been the case since the params were addeed, but is exposed by more recent changes to the way audio level state is stored/recalled/cleared. (e.g. cleared on RESET)

**Comment by tehn** [comment]
i'll chase this down. the whole introduction of RESET added some complexity. pretty sure it's a mismatch in initialization, like you say.

**Comment by tehn** [comment]
also GOOSE

**Comment by tehn** [comment]
i traced the workings and am pretty sure this problem has been fixed. without a reliable repro case i'm going to close this and simply assume that some people haven't updated to the newest version.

will reopen if needed.
