### ISSUE TITLE
number params type wraps incorrectly

### ISSUE THREAD

**Issue by dndrks** [monome/norns#1353]
too zonked to tackle atm, dropping this here for reminder!

repro:
```lua
function init()
  params:add{type = "number", id = "rnd", name = "stuff", min = 1, max = 3, default = 1, wrap = true}
end
```

goes between 2 + 3 when delta > 0, 2 and 1 when delta < 0

relevant lines: https://github.com/monome/norns/blob/d9967043529dc0b856d0c85480346517f70ee35b/lua/core/params/number.lua#L30-L45

**Comment by catfact** [comment]
that's right; thank you; but propose we incrase val of `self.range` instead.
