### ISSUE TITLE
(pre-release clock) internal clock drift

### ISSUE THREAD

**Issue by dndrks** [monome/norns#1360]
(i originally posted this in Slack, but it didn't make sense to keep it inaccessible)

hope you had a nice weekend @artfwo !

after a ping from @schollz about some potential internal clock wonkiness on the latest commit (#1335), I dug in and was able to repro. here’s the test script: https://gist.github.com/dndrks/773847a22b481387bd28a1daeb0a0985

### steps to repro:
- set norns clock to internal at 120 bpm
- begin recording TAPE
- run test script and reset the internal clock (you can modify the script to not rely on a transport start and you’ll get the same results)
- record about 40 seconds or ~75 quarter note executions

### expected results:
since the `clock.get_beats()` return even quarter notes, I expect the beats in the audio file to sync to the same quarter note pulses:

<details closed>
<summary>matron prints</summary>
<br>
<pre>
1.0005110400007	1
2.0020116579999	2
3.0013622859997	3
4.0023739480002	4
5.0010232240002	5
6.0022049899999	6
7.00139812	7
8.0015208280001	8
9.0008399959997	9
10.00191343	10
11.001106766	11
12.002268323999	12
13.000558121999	13
14.000916974001	14
15.002053742	15
16.001198746	16
17.00235499	17
18.00163541	18
19.000959476	19
20.001154786	20
21.00066656	21
22.001623534	22
23.00113385	23
24.002612592	24
25.002261656	25
26.00046656	26
27.001160307999	27
28.002495408	28
29.002872487999	29
30.002119782	30
31.002051866	31
32.001745722	32
33.003055298	33
34.001188432	34
35.00054656	35
36.00250103	36
37.00227499	37
38.002290408001	38
39.000502288	39
40.001589992	40
41.002154886	41
42.002450614	42
43.001199996	43
44.001665098	44
45.001074786	45
46.001471138	46
47.003025404	47
48.003017486	48
49.0018952	49
50.0013576	50
51.001234056	51
52.001763742	52
53.001841556	53
54.002438634	54
55.002409158001	55
56.002429676	56
57.002225408	57
58.00313853	58
59.002296968	59
60.000315416	60
61.001762284001	61
62.000919788	62
63.000519374	63
64.001460932	64
65.0006751	65
66.00115541	66
67.000679164001	67
68.00112958	68
69.001375412	69
70.000793122	70
71.00201791	71
72.002644364	72
73.001062496	73
74.001261662	74
</pre>
</details>

### actual results:
when I bring the audio file into a DAW (here, Ableton Live), I see/hear that the audible pulses drift from a 120 bpm metronome:

<img width="1345" alt="drift-1" src="https://user-images.githubusercontent.com/24821020/116884574-e064bb80-abf4-11eb-96b3-c36baf00186d.png">

here's a 16th-value zoomed-in version, showing an _eventual_ 1/16th note drift:
<img width="1022" alt="drift-2" src="https://user-images.githubusercontent.com/24821020/116884635-f2def500-abf4-11eb-932a-56774754b91e.png">

### control

to be sure this was an `internal` issue I also tested with `Link`, which did not exhibit the same drift.

here's an audio file I recorded with clock set to `Link` and 120bpm, with a metronome from Live running into the left channel and the synth engine running into the right (zoomed in at 1/16th resolution, same as the prior screenshot):
![image](https://user-images.githubusercontent.com/24821020/116885643-1d7d7d80-abf6-11eb-86d6-ecbff9092dea.png)

@schollz also confirmed:
- this is not an issue with incoming MIDI clock
- this isn't an issue present in the release build

**Comment by artfwo** [comment]
thanks @dndrks , i'll have a closer look later this week, but we can't do much in this regard, as we're not using sample (or sample-synced) clock for the internal source, hence it will always have zero or more drift when playing along any other clock (other norns or any other device), unless explicitly synchronized.

that said, i'll see if tuning sleep intervals in the internal source helps improve the situation here.

**Comment by dndrks** [comment]
no worries! i guess i'm mostly curious if it's a regression, since the release build doesn't exhibit this behavior?

**Comment by artfwo** [comment]
but in the issue above you mentioned that this is an issue present in the release build?

**Comment by dndrks** [comment]
woop! edited -- it is _not_ present in the release build. apologies, it was early AM

**Comment by artfwo** [comment]
yeah, it could happen due to the different way of updating the reference in the latest revision (the smooth tempo changing thing), i'll see if we can improve it to stay closer to the wall clock.

**Comment by artfwo** [comment]
hey @dndrks , could you please check if this is still an issue on the linked branch? thank!
