### ISSUE TITLE
clock beta: Ableton Link transport reset issue

### ISSUE THREAD

**Issue by dndrks** [monome/norns#1368]
the beta testing group on Discord has started diving in and found an issue with Ableton Link syncing -- happens in Live as well as Bitwig. this was not an issue with the previous public release.

steps to repro:
- get norns and Live/Bitwig on the same network and enable Link on both
- in Live/Bitwig, enable `Start Stop Sync` (issue only happens when this is enabled)
- load Awake
- toggle the transport on for your Live/Bitwig set
- Awake will ramp up its tempo for a few seconds (very very high), then settle back to the expected tempo

during this, the `tempo` under parameters doesn't reflect any weirdness -- it'll just keep displaying the same bpm -- but there's an audible rush of notes, which is also reflected in the awake UI's playhead.

**Comment by artfwo** [comment]
reproduced successfully, can have a look at it this week. thanks @dndrks!

**Comment by artfwo** [comment]
draft fix in #1370. this will pause all `clock.sync` calls until link transport is at beat 0 with the current quantum.

scripts that depend on this feature might require adjusting playhead either in `transport.start` callback or in time-dependent coroutines with `get_beats()`.

potentially `clock.sync` could return the beat on resuming.
