### ISSUE TITLE
failure to open non-bidirectional MIDI ports

### ISSUE THREAD

**Issue by catfact** [monome/norns#1449]
in this particular case i'm noticing that the 2nd port on a korg sq-1 is not recognized. (making it not useful as a CV output device.)

so far this is what i know

without `matron` running, alsa reports this:
```
$ amidi -l
Dir Device    Name
IO  hw:1,0,0  SQ-1 MIDI 1
 O  hw:1,0,1  SQ-1 MIDI 2
```
after adding a couple prints in matron, i see this:

```
scanning devices...
device_monitor(): adding midi device SQ-1
initializing midi device at path: /dev/snd/midiC1D0
this is a multiport device...
initializing midi device at path: /dev/snd/midiC1D0
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC1D0 failed: No such device
failed to open alsa device hw:1,0,1
```

**Comment by catfact** [comment]
took a more careful look, but i am not illuminated. 
actually looking at the names passed to `snd_rawmidi_open`, they look correct...
```
device_monitor(): adding midi device SQ-1
device_monitor(): adding midi device SQ-1
initializing midi device at path: /dev/snd/midiC1D0; port index = 0; multiport=1
alsa name: hw:1,0,0
initializing midi device at path: /dev/snd/midiC1D0; port index = 1; multiport=1
_norns.midi.add: 3, SQ-1 1, userdata: 0x71209650
alsa name: hw:1,0,1
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) 
open /dev/snd/midiC1D0 failed
: No such device
failed to open alsa device hw:1,0,1
dev_list_add: error allocating device data
```

**Comment by catfact** [comment]
ah, is it because the second port is output only?

**Comment by catfact** [comment]
.. yes this seems to do it. if i simply pass NULL for all input handles, both outputs work as expected.

having midi device with a null handle requires adding checks in `dev_midi_start`. and presumably changing things in the lua layer... so seems like we need to do a little work to function properly with a device like this.

**Comment by awwaiid** [comment]
Sharing as another datapoint, I think I have run into this with a Logidy UMI3 foot-switch midi device, which I think is also output-only.

```
Apr 17 21:57:01 norns kernel: usb 1-1.2: USB disconnect, device number 4
Apr 17 21:57:04 norns kernel: usb 1-1.2: new full-speed USB device number 7 using dwc_otg
Apr 17 21:57:10 norns kernel: usb 1-1.2: New USB device found, idVendor=194f, idProduct=0069, bcdDevice= 0.01
Apr 17 21:57:10 norns kernel: usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Apr 17 21:57:10 norns kernel: usb 1-1.2: Product: Logidy UMI3
Apr 17 21:57:10 norns kernel: usb 1-1.2: Manufacturer: Logidy
Apr 17 21:57:10 norns kernel: hid-generic 0003:194F:0069.0002: hiddev96,hidraw0: USB HID v1.11 Device [Logidy Logidy UMI3] on usb-3f980000.usb-1.2/input2
Apr 17 21:57:10 norns mtp-probe[5420]: checking bus 1, device 7: "/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2"
Apr 17 21:57:10 norns mtp-probe[5420]: bus: 1, device: 7 was not an MTP device
Apr 17 21:57:10 norns ws-wrapper[461]: device_monitor(): adding midi device Logidy UMI3
Apr 17 21:57:10 norns mtp-probe[5425]: checking bus 1, device 7: "/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2"
Apr 17 21:57:10 norns mtp-probe[5425]: bus: 1, device: 7 was not an MTP device
Apr 17 21:57:10 norns systemd[5224]: Reached target Sound Card.
Apr 17 21:57:10 norns ws-wrapper[461]: device_monitor(): adding midi device Logidy UMI3
Apr 17 21:57:10 norns ws-wrapper[461]: ALSA lib rawmidi_hw.c:235:(snd_rawmidi_hw_open) open /dev/snd/midiC1D0 failed: No such device
Apr 17 21:57:10 norns ws-wrapper[461]: failed to open alsa device hw:1,0,0
Apr 17 21:57:10 norns ws-wrapper[461]: dev_list_add: error allocating device data
Apr 17 21:57:10 norns pulseaudio[5247]: Failed to find a working profile.
Apr 17 21:57:10 norns pulseaudio[5247]: Failed to load module "module-alsa-card" (argument: "device_id="1" name="usb-Logidy_Logidy_UMI3-00" card_name="alsa_card.usb-Logidy_Logidy_UMI3-00" namereg_fail=false tsched=no fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes avoid_resampling=no card_properties="module-udev-detect.discovered=1""): initialization failed.
```

**Comment by catfact** [comment]
thanks. but no - that device is "input only" in this context. the logidy device drivers simply don't work on linux at alll, as far as i can tell.

**Comment by awwaiid** [comment]
I modified my local source and re-compiled. The device shows up in the device->midi menu and works! Invokes the event callback in lua land without issue, sending in the 60/62/64 midi note for button 1/2/3 as expected. This device works under my linux desktop without issue, btw. Woo!

```diff
diff --git a/matron/src/device/device_midi.c b/matron/src/device/device_midi.c
index e5e2657..dfd03fc 100644
--- a/matron/src/device/device_midi.c
+++ b/matron/src/device/device_midi.c
@@ -68,7 +68,8 @@ int dev_midi_init(void *self, unsigned int port_index, bool multiport_device) {
         return -1;
     }

-    if (snd_rawmidi_open(&midi->handle_in, &midi->handle_out, alsa_name, 0) < 0) {
+    if (snd_rawmidi_open(&midi->handle_in, NULL, alsa_name, 0) < 0) {
         fprintf(stderr, "failed to open alsa device %s\n", alsa_name);
         return -1;
     }
```

**Comment by catfact** [comment]
oh, that's good! i have a UM3 here that is simply not functional, reports garbage fields from lsusb, doesnt work with any alsa application. i did complain to them about a year ago so maybe there has been a firmware update.

that's a little weird, but i guess "non-bidirectional" applies. if you look up top you see that a similar hack made things "work" for output-only devices. but we need to make the lua stack and device class aware that these configurations are possible.

**Comment by awwaiid** [comment]
I haven't figured out how to sniff input-only (yet, will continue next weekend), but once I do how about in `dev_midi_send` if it is an input-only device it skips the send? Then lua can try to send all it wants and it is shouting into the void (with no feedback but no errors)? I don't think that'll work as well for the output-only case, but maybe?

**Comment by catfact** [comment]
i guess that wou.d work. but ultimately we also need to fix the output-only case. and in that case we simply don't see the device in lua as is. 

my thinking would be that if we were going to get in there and clean this up at the C level, we may as well also inform lua about the input/output capabilities of each device. it seems confusing to have an undifferentiated list of I and O in the devices list. 

but yeah i guess that's really a seperate issue. i suppose for this issue, it would be enough to sniff the I/O here and pass NULL as appropriate to `snd_rawmidi_open`. i think it will work for output-only too; we'll just never raise any events for the device.

looks like my past self above noted that we will need some new checks in `dev_midi_start` in order to not crash as well.

---

i must've got a bad unit. oh well

**Comment by gtridr** [comment]
I can confirm from a user standpoint that this behavior also affects MIDI interfaces with an asymmetrical number of inputs & outputs. I have an M-AUDIO midisport 2x4 and outputs 3 & 4 are not made available in midi menu.

As above, amidi -l gives the following output:
```
Dir Device    Name
IO  hw:1,0,0  MidiSport 2x4 MIDI 1
IO  hw:1,0,1  MidiSport 2x4 MIDI 2
 O  hw:1,0,2  MidiSport 2x4 MIDI 3
 O  hw:1,0,3  MidiSport 2x4 MIDI 4
```

I'd like to help in any way I can, be it testing, logs, whatever. I'll be staying subscribed to this issue. Those extra ports would be mad useful

**Comment by forrestbaer** [comment]
I've run into the same issue with my new [USB2MIDI](https://michigansynthworks.com/products/usb2midi-5-port-trs-midi-output-module) which uses the Polytec GM5. It has 5 TRS outputs and one usb input.  I tried messing around with `device_midi.c` and recompiling as above but no change for me. I'll post any followups if I discover anything.

` aconnect -i
client 0: 'System' [type=kernel]
    0 'Timer           '
    1 'Announce        '
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 128: 'Client-128' [type=user,pid=7695]
    0 'Virtual RawMIDI '`

`aconnect -o
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 20: 'MSW_USB' [type=kernel,card=1]
    0 'MSW_USB MIDI 1  '
    1 'MSW_USB MIDI 2  '
    2 'MSW_USB MIDI 3  '
    3 'MSW_USB MIDI 4  '
    4 'MSW_USB MIDI 5  '
client 128: 'Client-128' [type=user,pid=7695]
    0 'Virtual RawMIDI '`

`amidi -l
Dir Device    Name
 O  hw:1,0,0  MSW_USB MIDI 1
 O  hw:1,0,1  MSW_USB MIDI 2
 O  hw:1,0,2  MSW_USB MIDI 3
 O  hw:1,0,3  MSW_USB MIDI 4
 O  hw:1,0,4  MSW_USB MIDI 5`

`/proc/asound/cards
 0 [sndrpimonome   ]: snd-rpi-monome - snd-rpi-monome
                      snd-rpi-monome
 1 [MSWUSB         ]: USB-Audio - MSW_USB
                      Ploytec GmbH MSW_USB at usb-3f980000.usb-1.3, full speed
`

**Comment by forrestbaer** [comment]
So it seems I'm lacking the C skills to make a ton of progress so far but what is working for me is just configuring a virtual midi port then using `aconnect` to link up the output of that port to one of the subdevice ports.  Would be awesome to be able to do this inside matron.

**Comment by catfact** [comment]
seems to me that we know the issue and it's pretty straightforward to fix it without any need for workarounds.

i don't have much of  a stake in this and wish a different contributor would contribute a fix. but if that's not possbile i will make some time next week and asseble the needed hardware for a norns midi bug fixing session.
