### ISSUE TITLE
screen is blank / "jack fail" after boot with 2+ USB devices

### ISSUE THREAD

**Issue by catfact** [monome/norns#1488]
lines thread:
https://llllllll.co/t/norns-screen-goes-blank-after-boot-up/38566/30

in summary:

- occasionally when booting with 2 or more USB devices (including WIFI dongle,) norns appears to halt after the bootup animation, displaying a blank screen and not responding to key presses

- normal operation resumes (sometimes?), showing the SELECT menu, when one device is removed.

- occurs on wall and battery power

- might occur more often with monome grids. but we have reports with many other devices (mostly MIDI.)

- the one journalctl output we have so far does show URB error; this is with an FTDI gri:
```
[ 377.280744] ftdi_sio ttyUSB0: usb_serial_generic_write_bulk_callback - urb stopped: -32
```

**Comment by catfact** [comment]
this has to be some kind of power starvation affecting the usb bus/hub. its not really something addressable in the norns stack. leaving as known issue

**Comment by tehn** [comment]
shield specific, i might add

**Comment by tehn** [comment]
or, as it happens, some occurrences noted on standard norns as well. sorry

**Comment by tehn** [comment]
will reopen with more reports
