### ISSUE TITLE
softcut filter(?) explosions in latest builds

### ISSUE THREAD

**Issue by catfact** [monome/norns#1526]
lately, rebuilding softcut results in sporadic noise after initialization. sometimes it is a loud burst that lasts until the system is stopped. this is happening in latest release image so is now an urgent problem.

bypassing the filter seems to fix it?

https://github.com/schollz/acrostic/commit/179494f69c25740ef916b8d1119a9ebe08a0d19e

so, looking at that:

- the SVF buffers are not specifically reset, so added that on this branch; doesn't fix
https://github.com/monome/softcut-lib/tree/fix-filter-reset

- NaNs/infs could be creeping into input. can test this theory by feeding NaNs into jack, and can address by sanitizing inputs, nbut that has some cost. 

- can mitigate cost and check stability at same time by considering approximation to `tan` in frequency warping during cutoff calculation; also check final coefficient ranges allowed (looks like all the qway to nyquist which is... optimistic.) (softcut/crone could definitely pick up some cycles by approximating trig functions elsewhere, like for panning.)

**Comment by catfact** [comment]
i was finally for some reason able to reproduce using `oooooo` on factory norns with latest image. (might try for more minimal repro script.)

possible solution (fixes it for me), but needs a little more refinement:
https://github.com/monome/softcut-lib/pull/64/files

**Comment by dndrks** [comment]
@catfact , dang, wild to watch how you identified the trouble! is this issue good to close?
