### ISSUE TITLE
Midi.remove doesn't return device info

### ISSUE THREAD

**Issue by jaseknighter** [monome/norns#1557]
Midi.remove is supposed to return a device object according to the docs, but it returns nil.

i believe the fix is in this file: /norns/blob/main/lua/core/midi.lua

line 403 should be changed from: `Midi.devices[id].remove()`

to something like:

```
local dev = {
  Midi.devices[id].id
  Midi.devices[id].name
  Midi.devices[id].dev
}
Midi.devices[id].remove(dev)
```

**Comment by jaseknighter** [comment]
i'll see if i can fix this myself and submit a PR (i haven't tried to change norns code before).

**Comment by ngwese** [comment]
i don’t have the code in front of me but i’d recommend validating which of those fields in the table being returned are safe/valid to even return after the device itself is gone. for instance i’m not sure the `dev` handle is valid or useful at that point.

**Comment by jaseknighter** [comment]
good point @ngwese. perhaps it would be better to just return the device's name and id, like:

```
local dev = {
  id = Midi.devices[id].id
  name = Midi.devices[id].name
}
Midi.devices[id].remove(dev)
```

**Comment by jaseknighter** [comment]
i've committed a fix to my local repo to address this issue and submitted a pull request. also, in the fix i updated the autodocumentation code to indicate the return object includes midi id, name, and port.

**Comment by catfact** [comment]
@jaseknighter does this change do what you need?
https://github.com/monome/norns/pull/1590/files

**Comment by jaseknighter** [comment]
i've not tested but the change looks fine to me. i didn't really have a specific need for this change other than to address the discrepancy between the docs and the code (as mentioned earlier).

**Comment by catfact** [comment]
id like to close this issue. it;s confuzing to me. firstply i think it's supposed to say that thep per-device callback should be getting device info as a parameter - which is what the comment illustrates, and which i actually don't agree with.

looking at this area the only issue i saw was that the glohbal customizable device removal callback wasn't firing, as the (inline) documentaiton suggests it should - hence the PR

i don't know of any other discrepancies with docs but please point out if you see
