### ISSUE TITLE
clock source must be re-selected after script load

### ISSUE THREAD

**Issue by zjb-s** [monome/norns#1567]
I often have crow clocking my norns - when I reload the script, i need to reselect crow in the clock param menu to get it to work.

**Comment by dndrks** [comment]
hi hi! hope all's well :)

i'm not able to repro this issue from my assumptions -- please lmk if there's any details that are different from your scenario and mine:

- load a fresh session of Awake
- set clock `source` to `crow`
- Awake responds to the new tempo
- clear Awake using K1 + K3 on SELECT/SYSTEM/SLEEP screen _or_ reload the script
- clock source remains `crow`

**Comment by zjb-s** [comment]
hey dan!

my bad, i didn't phrase the issue well. let me elaborate: even though the clock source *says* crow, it won't respond to crow tempo changes, and indeed it will drift out of sync slowly - until you reselect crow as a source, then it's rock solid.

-z

**Comment by dndrks** [comment]
didn't see this get re-opened, many apologies!
i'm unable to reproduce this issue with `240424` (or Feb 2024's release), but if anybody runs into similar trouble please bump!!
