### ISSUE TITLE
Fixing Maiden-REPL:"(cannot allocate memory)" 

### ISSUE THREAD

**Issue by jpnielsen** [monome/norns#1596]
Running the latest image on RPI4 - unsupported usb audio, no display.

I had errors, when running some jack related commands in Maiden-REPL.
"cannot lock down 107350048 byte memory area (cannot allocate memory)"

Fix:

```
change
'#DefaultLimitMEMLOCK=' to 
'DefaultLimitMEMLOCK=128M' in:

/etc/systemd/system.conf
and
/etc/systemd/user.conf
```
before fix:
```
os.execute("jack_lsp -c")
cannot lock down 107350048 byte memory area (cannot allocate memory)
system:capture_1
system:playback_1
system:playback_2
SuperCollider:in_1
SuperCollider:in_2
SuperCollider:out_1
   NDI_send:input0
SuperCollider:out_2
   NDI_send:input1
NDI_send:input0
   SuperCollider:out_1
NDI_send:input1
   SuperCollider:out_2
true	exit	0
```
after fix:

```
os.execute("jack_lsp -c")
system:capture_1
system:playback_1
system:playback_2
SuperCollider:in_1
SuperCollider:in_2
SuperCollider:out_1
   NDI_send:input0
SuperCollider:out_2
   NDI_send:input1
NDI_send:input0
   SuperCollider:out_1
NDI_send:input1
   SuperCollider:out_2
true	exit	0
```

PS. I'm using jack commands to patch to NDI https://llllllll.co/t/ndi-mod-share-the-norns-screen-over-a-network/56347/9

**Comment by Dewb** [comment]
You’ve added two Jack audio channels, so it makes sense that the locked memory requirements would increase, necessitating this change. What’s the case for doing it in the base system, though? My naive impression is that it seems like if future users get the error and have to increase the limit, that’s a good way to make them aware of the performance tradeoffs of their modifications. Maybe the community could start an “advanced JACK tricks” document to memorialize this kind of info.

**Comment by jpnielsen** [comment]
I reverted my changes,  then I get the error.

systemctl disable norns-jackconnect.service
systemctl disable jack2ndi.service
systemctl disable ndi2jack.service

```
os.execute("jack_lsp -c")
Cannot lock down 107350048 byte memory area (Cannot allocate memory)
system:capture_1
system:playback_1
system:playback_2
SuperCollider:in_1
SuperCollider:in_2
SuperCollider:out_1
SuperCollider:out_2
true	exit	0
```

Perhaps something wrong with my configuration - cound be, but I feel that i have seen the error often, when people have posted logs.

```
os.execute("ulimit -l")
64
true	exit	0
```
in a bash shell, the value seems to follow what is set in /etc/security/limits.d/audio.conf

```
127.0.0.1 ~ $ ulimit -l
unlimited
```

**Comment by jpnielsen** [comment]
Not an important issue. Will use the community forum in the future.
