### ISSUE TITLE
lattice transport value gets increased in steps of 5

### ISSUE THREAD

**Issue by kasperbauer** [monome/norns#1637]
@ryleelyman
@tyleretters  

Hey there, i think i just found an issue with lattice 2.0, due to the new sprocket ordering logic.
Heres a little script to demonstrate the problem. The action should be (is?) executed every pulse, but the transport value is increased in steps of 5.

```
lattice = require('lattice')

function init()
    lat = lattice:new()
    sprocket = lat:new_sprocket({
        action = function(t)
            print(t)
        end,
        division = 1 / lat.ppqn / 4, -- do every ppqn
        order = 1
    })
end

function key(n, z)
    if z == 1 then
        if n == 2 then
            lat:start()
        elseif n == 3 then
            lat:stop()
        end
    end
end
```

The output is the following:
```
> 0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
...
```

If I'm correct, the transport value should be increased outside the for-loop. PR incoming.

**Comment by dndrks** [comment]
closed via #1638
