### ISSUE TITLE
"accum" mapping issues

### ISSUE THREAD

**Issue by zjb-s** [monome/norns#1649]
If I turn an encoder on my controller, then change the param on norns itself using onboard controls, then go back to using the external controller, the value jumps to where it was when I last turned the controller knob.
Also, norns currently doesn't propagate CC's back to the controller like some controllers want. I can work on that part, but I'm at a loss on the above. Can anyone else reproduce this? I've tried it on multiple norns with multiple controllers.

**Comment by dndrks** [comment]
tytyty for report!!
fixed in #1696 !

**Comment by dndrks** [comment]
tytyty for report!!
fixed in #1696 !
