### ISSUE TITLE
Fates Norns clone  freeze during boot up, if it even boots up at all

### ISSUE THREAD

**Issue by moonworshiper** [monome/norns#1658]
Monome Fates clone, the software has been updated.  It's been a slow decline since I purchased it.  Any help idea if I can get the unit repaired in the US? I see the unit is getting power but it won't boot up and if it does it usually freezes shortly there after.  Any suggestions would be greatly appreciated.
Thank you

**Comment by tehn** [comment]
we do not directly support the fates hardware. please post to the lines forum: https://llllllll.co/t/fates-a-diy-norns-dac-board-for-raspberry-pi/22999 or contact whoever you purchased it from.
