### ISSUE TITLE
K3 on 'Battery Warning' traps navigation (230405)

### ISSUE THREAD

**Issue by dndrks** [monome/norns#1674]
from [raja](https://llllllll.co/t/norns-update-230405/62048/22):

***Problem*** -> engaging with the 'Battery Warning' field, mistakenly by using K3, will cause norns menu-navigation to be trapped within this screen of the settings menu from then on

**Steps To Repro:**
1) Navigate to the 'home'/main menu of norns, then go into System>Settings
2) Scroll down using enc2 to highlight the "Battery Warning" field
3) Press k3

**Results:**
Norns is trapped on this screen of the settings menu and pressing k2 will no longer allow you to back out like normal(and though enc3 works to select other items in this menu including the 'RESET' function, activating 'RESET' from here using k3 is not possible - had to use the hard-reset button under my stock norns to test this out.. edit: oops - i just remembered i could've also used ";restart" from within maiden - for anyone else trying to confirm/verify).

**Expected Results:**
since this field is just a simple toggle 'ON/OFF', pressing k3 here could flip the state of this field(?), but in any case, pressing k2 should allow us to back out of this menu/area/screen(as well as the other usual functionalities working here: i.e. k3 should work on the 'RESET' part of this menu screen), after trying k3 on the 'Battery Warning' field.

**Additional Details:**
-fiddled with k1, during this problem, and the font changed to the font of my app, but didn't actually go into my app(so maybe that's the same issue where all the buttons become unresponsive after pressing k3 on the 'Battery Warning' field?)
-it's possible with this bug in play to navigate into the 'Password' section, but password can't actually be changed(and backing out of 'Password' section strangely involves pressing either k2 or k3, and *then* turning enc2... but then after you back out of password, you're still stuck in the 'Settings' menu)
-this is on Norns update 230405(w/ nothing but power and a Panda Wireless PAU06 wifi usb stick plugged in)

:heart: Hope it helps. :sake: :heart:

**Comment by RajaTheResidentAlien** [comment]
here's a logfile attached here
also, upon retesting: it seems you CAN change the password(i just didn't hit 'OK' properly the first time... and having to restart got me confused on what i'd witnessed :p)

[system.log](https://github.com/monome/norns/files/11366610/system.log)
