### ISSUE TITLE
lfo lib - specify what the "offset" param does / add startpoint offset

### ISSUE THREAD

**Issue by sonocircuit** [monome/norns#1686]
logging this issue as per discussion on the discord NSG. it is unclear what the `offest` param actually does and I think it would be good to add a short description. Intuitively I had assumed that the `offset` param offsets the starting point of the lfo but it seems to add a "dc offset". I think it would be great to add a param that offsets the starting point of the lfo (in addition to `min`, `center`, `max`).

**Comment by dndrks** [comment]
closed via #1692
