### ISSUE TITLE
Lua files in dust/code/crow are shown in script listing

### ISSUE THREAD

**Issue by xmacex** [monome/norns#1739]
Hi. With the new update Lua files in directory `dust/code/crow` are shown in the norns script listing. Loading any of them on norns will probably fail.

![crows_are_there.gif](https://github.com/monome/norns/assets/879300/8a5450d6-fd8d-41df-9b8c-ad8d4b6ad0e9)

The relevant change seems to have been https://github.com/monome/norns/pull/1712 which moved getting the script listing from Lua to **find** *(1)*.

Files inside script subfolders called *crow* e.g. `code/murder/crow/caw.lua` are hidden, just not the one in *code* directly e.g. `code/crow/caw.lua`.

I am filing this as an issue not because _dust/code_ is necessarily a good place to store crow-only code, but because 

1. Loading crow code on norns will probably fail
2. Before #1712 `code/crow/*.lua` were recursively hidden, and
3. I read a clear intent in #1712 to hide Lua files in directories called _crow_

So maybe this is a non-issue simply to be closed as *won't fix*. If not, to hide Lua files in `dust/crow`, [I believe](https://youtu.be/uy-EOkUqpMk) removing the leading `/` from [the grep which filters find](https://github.com/monome/norns/blob/main/lua/core/menu/select.lua#L63) would do it, because of how **find** *(1)* prints its output.

With the following file tree, with `caw.lua` being a crow code and `murder.lua` norns code

```
$ ls -FRm dust/code/
dust/code/:
crow/, murder/

dust/code/crow:
caw.lua

dust/code/murder:
crow/, murder.lua

dust/code/murder/crow:
caw.lua
```

currently the listing filters out the crow code in script subdirectory _crow_ but not in directory _crow_. 

```sh
$ find ~/dust/code/ -mindepth 2 -name .git -prune -o -type f -name "*.lua" -printf "%P\n" | grep -Ev "/(lib|data|crow)/"
murder/murder.lua
crow/caw.lua
```

while without the leading `/` in the reverse grep the listing would filter out crow code both subdirectory _crow_ and directory _crow_.

```sh
$ find ~/dust/code/ -mindepth 2 -name .git -prune -o -type f -name "*.lua" -printf "%P\n" | grep -Ev "(lib|data|crow)/"
murder/murder.lua
```

I am not sure what's a good place for crow only code. Meanwhile, I've moved my own crow files without a norns component from _dust/code/crow_ to _dust/crow_.

caw have a good day

**Comment by tehn** [comment]
i think /dust/data/crow would be an appropriate place for crow code not intended to be run on a norns.

this would mean changing bowering --- https://github.com/whimsicalraps/bowering/blob/main/bowering.lua#L20

**Comment by dndrks** [comment]
@xmacex , curious how these scripts reached `dust/code/crow/`? were they manually imported there?
i ask because `bowering` bundles all of its crow scripts into a nav-hidden folder.
if these scripts were manually imported, then def recommend all crow-only files live in `/dust/data/crow` (if you want them to live on norns at all). but maybe i'm misunderstanding?

**Comment by xmacex** [comment]
They got there simply because I put them there :)

What confused me was that earlier `dust/code/crow` was hidden (like all paths with "crow" in them), but then with the update it wasn't anymore. That what was this issue was about basically. All is clearer now caw caw

Makes sense to keep them out of `dust/code` – they are obviously code, but not _that_ kind of code which is intended to run on norns. I'll keep my crow-only code there or in `dust/data`. I like keeping crow code on norns so I can run druid direct on norns, add my own scripts to bowery, and upload them with the _bowering_ norns script.

Thank you, have a nice day!
