### ISSUE TITLE
Grid LEDs do not illuminate in vertical orientation

### ISSUE THREAD

**Issue by brokyo** [monome/norns#1767]
I'm working on a script using an 8x16 grid from the most recent batch on norns 2.8.1/norns 231114 and I'm unable to light all the keys when it's in a vertical orientation. Even with the simplest approach, I can only get the top 8x8 section to illuminate.

A really small script that expresses this problem:

 ```
g = grid.connect()
g:rotation(1)
g:all(5)
g:refresh()
```

I don't believe this to be a mechanical issue because the opposite 8x8 set lights up if I rotate 270 degrees. Similarly, if the rotation is 0 or 180 everything lights up.

When I log key presses after `g:rotation(1)` with  `function g.key(x,y,z)` I get messages with appropriate x and y coordinates so this seems to be limited to illumination.

Additionally, I saw this [post on lines](https://llllllll.co/t/grid-rotation-on-norns/31660/16?u=new_moon) which makes me suspect this is an issue that isn't just affecting me.

**Comment by catfact** [comment]
please see my comment on the linked PR, and i also recommend getting comfortable with `git blame` if you're not already
