### ISSUE TITLE
consider exposing `median` filter length `\pitch` synth params via Lua/OSC

### ISSUE THREAD

**Issue by pq** [monome/norns#1769]
following up from the conversation about jitter in the tuner app (https://llllllll.co/t/tuner/21088/14), as @catfact notes

> [it] Might not be the worst thing to expose these system synth parameters through Lua /OSC.

`median` for sure but maybe `downsampling` too?

**Comment by catfact** [comment]
Maybe just a generic OSC method for each "system synth" (including pitch and amp follower, maybe that's it?), taking a synth control name and a value

Wouldn't really need Lua FFI

**Comment by catfact** [comment]
... One thing to consider is when/if to reset these to default values (should they be blind to parameters? Etc), as these synths outlive the script

**Comment by tehn** [comment]
the question of default values will follow the same logic as the reverb and compressor, right?

which raises the issue of perhaps this current logic should be evaluated (since we now have more system preference options than before).

**Comment by pq** [comment]
**update:** as much as i love the idea of exposing these params, i did some testing this afternoon and have to say i didn't see a noticeable improvement when i bumped the median and dropped downsampling. (obviously, this is just anecdotal and deserves a bit more exploration but i'm not as sold on the idea as i was when i proposed it.)
