### ISSUE TITLE
Encoder acceleration not working, enc() passing -1/1 only

### ISSUE THREAD

**Issue by dstroud** [monome/norns#1779]
Looks like encoder acceleration is not working on my system running 240424. `enc()` always returns delta of -1 or 1.

I think this is related to https://github.com/monome/norns/pull/1776/commits/d4eb4b39db7fda6137f9fac3e24a2f3efc2bbe62

**Comment by tehn** [comment]
is this inside of a script?

if so, you need to explicitly enable it: https://monome.org/docs/norns/reference/encoders

`norns.enc.accel(n,enable)`

**Comment by tehn** [comment]
apologies, to clarify, both pots and encoders "have" acceleration but their implementation is different. i should rename the redirection functions inside norns.lua to make more sense

**Comment by dstroud** [comment]
I'm probably confusing things by referring to "acceleration".

What I mean is that the `enc()` Lua function now returns exclusively _-1 or 1_ rather than a wider range of values proportional to how quickly the encoder is turned.

This doesn't seem to be affected by `norns.enc.accel()` or `norns.enc.sens()` as far as I can tell.

**Comment by tehn** [comment]
yes, found the typo.

if you'd like to `git pull` in the minor lua fix ahead of an update, that should do it for you
