### ISSUE TITLE
support midi sysex messages

### ISSUE THREAD

**Issue by artfwo** [monome/norns#262]
this requires an additional event type for sysex events.

**Comment by dndrks** [comment]
@tehn , this came up on lines today -- should we consider reopening? https://llllllll.co/t/how-do-i-send-midi-sysex-messages-on-norns/34359

**Comment by dndrks** [comment]
oh damn, @catfact solved it. sorry for the noise!

> you just send the bytes.
>
> ```
> midi_out.send(0xf0) -- sysex start
> --- send sysex bytes...
> midi_out.send(0xf7) -- sysex end
>```
> if anything is “missing”, it is that Midi.to_data() function doesn’t include entires for “systex_start” and “sysex_end”, which contstitutes the entirety of the “MIDI standard for sysex.”

**Comment by catfact** [comment]
my proposal needs testing, but that's all sysex is - those two bytes with stuff in between.
