### ISSUE TITLE
control / number param interface

### ISSUE THREAD

**Issue by catfact** [monome/norns#284]
trying to use `paramset`, having to make a lot of switches on parameter type (`tNUMBER` vs `tCONTROL`) and call different methods. would it not make sense to give the two types the same interface

number: `minval`, `maxval`, `set`
corresponds to
control: `min`, `max`, `set_raw`

^ and incidentally, `control.set` vs `control.raw_set` seems unintuitive / ambiguous? 
`set` should be the most commonly used, yeah? which would be, setting unmapped value and triggering update.,
for clarity, would recommned `set_mapped`, `set_unmapped` and `set` as alias to `set_unmapped`.

----

and, just curious - when would you expect to use a tNUMBER instead of a tCONTROL?

**Comment by tehn** [comment]
`set_mapped` and `set_unmapped` are much more intuitive.

i think we can make this work w/o it being breaking?
