### ISSUE TITLE
consider moving to luaJIT

### ISSUE THREAD

**Issue by catfact** [monome/norns#31]
i only recently dug into the documentation for [luaJIT](http://luajit.org/ext_ffi.html), which is a JIT compiler for lua. one thing it provides is a "native" FFI for lua to call C functions and access C data structures directly.

this has two main benefits that i can see:
- it's much more performant if there are many calls from lua to C, and especially if those calls are passing a lot of data through the lua stack
- it eliminates lua->c glue functions.
- it is supposedly more performant on the interpreter as well (better GC, byte code vectorization and alignemtn, &c)

however:
- i doubt that the performance gains from this approach would be very relevant for our purposes; we don't have tight computational loops between the languages, and we shouldn't be passing large amounts of data (if we are, i'd consider it a design issue.) that said, it's kind of pointless to speculate about performance impact before profiling. (in this case that would mean running cachegrind while, say, doing lots of graphics updates from lua on a fast timer. but we don't have a graphics engine yet...)
- it poses another learning curve for me; different calling semantics for the REPL (and i'm not totally clear on whether it needs to run as a separate executable, or what)
- it does nothing to simplify the c->lua glue, which is much uglier than its counterpart.

anyways just a thought to consider.

**Comment by tehn** [comment]
we're pretty deep into the non-JIT implementation. is this still interesting?

**Comment by catfact** [comment]
it isn't any _less_ interesting. i don't believe anything would be different in lua. our FFI could stay the same or be simplified. this is mostly about building/linking differently.

the bigger problem is that luaJIT seems to be sort of dead.

**Comment by catfact** [comment]
i think we've "considered" this long enough.

two nails in the coffin for me:
- luajit project has been looking for maintainers since 2015 and hasn't had a release since 2017.
- on close inspection, the not-implemented bytecodes include some important ones; list is hereot is : http://wiki.luajit.org/NYI

the upshot is that luaJIT can be very fast if using its FFI, but certain code constructs like anonymous functions and string concatenation, slow it down. and we use those constructs a lot.

so, no.
