### ISSUE TITLE
menu > sleep needs to perform more cleanup

### ISSUE THREAD

**Issue by antonhornquist** [monome/norns#369]
- [ ] needs to write paramsets to disk
- [ ] some engines may need cleanup 

this is recreatable with `hello_ack`

**Comment by tehn** [comment]
@antonhornquist re: sc de-init, we'd need to add another command to `weaver` for this. what's the use case specifically? what happens when `ack` isn't deinited on shutdown?

**Comment by antonhornquist** [comment]
@tehn that's a general comment on proper cleanup when norns goes to sleep, not specifically for `ack` (the `ack` engine will work fine with current shutdown).

example use case: if an engine records to disk using the DiskOut UGen* or similar it would be nice if the engine properly manages/disposes resources (soundfiles, metadata) gracefully before norns sleeps just as it would do if a new script was loaded.

(i did not think as far as this requiring another `weaver` command. this is not urgent, so you might wanna create a new issue for this)

* btw, is tape stopped before shutdown? it uses DiskOut under the hood.

**Comment by tehn** [comment]
moved to https://github.com/monome/norns/issues/499
