### ISSUE TITLE
Name tape recordings with periodical numbers instead of date/time

### ISSUE THREAD

**Issue by artfwo** [monome/norns#373]
With norns system date/time being highly inaccurate due to absence of hwclock, it makes sense to name recorded files with numbers (foo00001.aif), does it?

**Comment by dansimco** [comment]
+1 for keeping a global tape count, rather than current state of the directory. Much easier to keep track of recordings when archived, avoiding `tape1 2.aif`, `tape 1 3.aif`, which I often end up with from OP-1 tapes.
