### ISSUE TITLE
auto-stop tape player

### ISSUE THREAD

**Issue by artfwo** [monome/norns#374]
playing back tape recordings doesn't seem to stop after the file has finished playing, i.e. the player just continues to play silence, while displaying the same file and incrementing time.

**Comment by catfact** [comment]
@tehn @antonhornquist is this done now?

**Comment by tehn** [comment]
this is not done per se. i believe the tape now loops (not sure if that is desired behavior) but the playback time counter is still just a lua-based metro whereas i should be using the crone poll instead.

**Comment by antonhornquist** [comment]
Lua side should display playback position based on the tape poll. IIRC there’s no looping going on. As @tehn says this is probably about the playback counter.
