### ISSUE TITLE
disable acceleration (or reduce it) within menu

### ISSUE THREAD

**Issue by tehn** [monome/norns#376]
way too twitchy

**Comment by nf** [comment]
I'm happy to take a crack at fixing this.

**Comment by pq** [comment]
iirc should make for an easy tweak in `menu.lua`.

https://github.com/monome/norns/blob/7c553e4f0f8dcb2fd35b031f1db43aa07826b5ee/lua/menu.lua#L305-L308

**Comment by nf** [comment]
Thanks @pq, that was the spot.

I disabled acceleration and it did the trick for me. I'm sure further tweaks should be made, but this is a step in the right direction.

**Comment by antonhornquist** [comment]
@nf fix is mot merged

**Comment by tehn** [comment]
https://github.com/monome/norns/pull/480

**Comment by tehn** [comment]
acceleration should be enabled for LEVELS screen (so all faders will react the same)
