### ISSUE TITLE
norns goes unresponsive when router turns off

### ISSUE THREAD

**Issue by pq** [monome/norns#385]
twice today my `norns`  has gone unresponsive after the router it was connected to was turned off.  i'm guessing this would be easily reproducible with these steps:

1. connect to lan (or in my case phone hotspot)
2. turn off router
3. wait a bit

another data point: in my case I was on the meters page so i guess it's possible that menu has something to do with it.

possibly related to: #312

**Comment by catfact** [comment]
it seems likely that this is related to scsynth freaking out / crashing when network time sync produces a big jump in the system clock. not clear how to fix that yet. 

in any case, for debugging you might want to look at the output of `sclang`, which means running `sclang` directly in a separate screen (instead of `./crone.sh > /dev/null`

**Comment by catfact** [comment]
also, are you running with `-s` in the jackd configuration? that seems to prevent jackd from crashing on xruns from ALSA. the latter is likely to occur when network configuration changes and scsynth gets momentarily clogged up with UDP packets (or something)

**Comment by pq** [comment]
> also, are you running with -s in the jackd configuration? 

yep.

> in any case, for debugging you might want to look at the output of sclang, which means running sclang directly in a separate screen

when i have a little more time and get to do some script hacking i'll set myself up that way and see if i can catch a crash.

**Comment by tehn** [comment]
this (and SYNC and UPDATE) seem like good candidates to deactivate the current script and shutdown crone.

**Comment by simonvanderveldt** [comment]
@pq does this still happen/reproduce on the 180603 update?

**Comment by pq** [comment]
@simonvanderveldt : hasn't recurred.  optimistically closing. 🤞
