### ISSUE TITLE
softcut (ugen and engine) : audio quality enhancements

### ISSUE THREAD

**Issue by catfact** [monome/norns#407]
we did some severe, last-minute corner-cutting on audio quality for the `SoftCutHead` ugen, for performance reasons.

- playback resampling uses linear interpolation (fractional rates have noticeable aliasing)
- all parameter changes are control-rate (bad artifacts when using lag on speed, fast last with record is ugly)

there are others, but these two are the most noticeable and i would love to revert them.

independently, we must fix the resampling for the write head. it doesn't even attempt to be correct linear interpolation right now. there is a `softcut-resample` branch, created before the quality-reduction changes, that does so (as well as refactoring / cleaning up.)  for some reason this branch crashes on ARM but works on amd64 (hopefully something silly like a pointer error.) this task is orthogonal.

## tasks

- [ ] revert quality reduction changes. (requires making CPU headroom somehow.)
- [ ] fix resampling branch for ARM.

**Comment by tehn** [comment]
reverting (to higher quality) would be great given the dropout/noises were unrelated

**Comment by catfact** [comment]
? they weren't unrelated at all. the changes reduced usage by 25% or something, which was enough to avoid glitches. adding `-s` to jackd isn't really a magic bullet, we still have glitches with too much usage, but maybe there is enough headroom again.

**Comment by tehn** [comment]
you’re correct, i was confusin my issues

**Comment by catfact** [comment]
i wasn't thinking about write-head interpolation as part of this - just that it would be nice to rever the changes to playback interpolation quality, and make speed change / trigger timing sample-accurate again.

right now, simply reverting those changes will cause a glitchfest. because they will push cpu usage for the scsynth audio thread back over the ~60% threshold that seems to still be the barrier for xruns (or IO stalls - i'm still not sure what these artifacts are since jackd doesn't report them.)

but yes, resampling the write head correctly is another related task that i guess falls under this issue. the changes `softcut-resample` branch work very well on amd64 systems, but totally crash on ARM for some obscure reason i haven't yet identified.

in any case, it's necessary to save CPU somewhere else before we can apply it to higher-quality algorithms here. my current investigation is into moving aux and insert FX processing to a separate scsynth instance. (https://github.com/monome/norns/issues/417)

**Comment by catfact** [comment]
another thing we could do is basically redesign the engine. i guess it's important for the vision of MLR to be able to arbitrarily read or write with any head. but it would be vastly simpler to have a dedicated record head that is locked at speed=1

**Comment by catfact** [comment]
with record level being at control rate, lag sounds bad (a sweeping glitch artifact, worse than a click.) so it is currently disabled in the `SoftCutVoice` abstraction. 
https://llllllll.co/t/norns-dust/14015/110?u=zebra

**Comment by catfact** [comment]
actually if anyone wants to test the conclusion that .kr lag is worse than no lag, just uncomment these lines
https://github.com/monome/dust/blob/master/lib/sc/abstractions/SoftCutVoice.sc#L53-L54

**Comment by tehn** [comment]
success. splitting issue for record head
