### ISSUE TITLE
save and restore system settings when moving between menu and script

### ISSUE THREAD

**Issue by pq** [monome/norns#414]
encoder, key and screen settings should be saved and restored between switches.

specifically, this will 

* simplify script `redraw()`s since scripts won't need to (re)assert their screen settings
* allow scripts to customize encoder and key behavior

forward pointers:

`menu.init()` asserts encoder settings here:

https://github.com/monome/norns/blob/90b16dfa3a4d2114e448a4fb4558f1b8687680dd/lua/menu.lua#L291-L292

which is called _after_ script init here:

https://github.com/monome/norns/blob/90b16dfa3a4d2114e448a4fb4558f1b8687680dd/lua/script.lua#L42-L43

see also: #345 (for the plumbing to manage screen state).

/cc @tehn @artfwo

**Comment by tehn** [comment]
screen attribute saving works now.

must get the encoder states to restore properly now
