### ISSUE TITLE
investigate running multiple scsynth instances

### ISSUE THREAD

**Issue by catfact** [monome/norns#417]
scsynth's audio processing is single-threaded. so it runs on a single core.

when that thread uses ~60% or more CPU, we get audio glitches. they sound like xruns but might be something else - they aren't reported as xruns by jackd, but on the other hand running jack without `-s` seems to cause jack to crash occasionally when these artfiacts occur.

anyways, one weird idea i had is to run two instances of scsynth, connected with jack. call them the 'main' server and the 'aux' server.  we would run aux and insert effects on the aux server, and Engines on the main server. 

### pros:
+ the servers can run on separate cores, basically doubling the CPU cycles available for engines (improve MLR sound quality) and for aux / insert  effects (add EQ section or whatever.)

### cons:
- latency. adds either one buffer or two, depending on how jack implements inter-client connections. on the other hand might give us enough headroom to make the buffers smaller.   
- complexity. more process lifecycles to keep track of.

### implementation issues

- as far as i can tell, would need a utility like [njconnect](https://sourceforge.net/projects/njconnect/), or roll our own, to manage persistent jack client connections.
- we'd need the the aux server to have 4 inputs (2 hardware ADC and 2 virtual), to accommodate routing like ADC->aux, main->aux , &c. it seems possible to invoke scsynth this way.

**Comment by simonvanderveldt** [comment]
I think at least investigating this approach makes sense since we're currently unable to use a big part of the available CPU cycles. Another approach might be figuring out the issues (on ARM) with SuperCollider's supernova engine (which is multithreaded) and fix those.

> when that thread uses ~60% or more CPU, we get audio glitches. they sound like xruns but might be something else - they aren't reported as xruns by jackd, but on the other hand running jack without -s seems to cause jack to crash occasionally when these artfiacts occur.

Especially the `-s` part seems to hint at the soundcard/driver being the issue. Maybe it's worth the time to investigate the ALSA driver code and see if there are obvious improvements that can be made there.

**Comment by catfact** [comment]
supernova seems like a better solution and is working so far, closing this
