### ISSUE TITLE
default input gain (hardware)

### ISSUE THREAD

**Issue by catfact** [monome/norns#418]
while debugging some stuff, i realized that the input gains on my hardware are really different for each channel. i don't know if this is normal.

i also noticed:

- the i2c settings are all exposed in weaver, but not all are mapped to lua modules. in particular `gain_in` is not. 
- i don't know the correct range for levels. 50 seemed reasonable for me.
- the order of args (level, channel) is opposite from basically everywhere else.
- this should maybe be set to some default, and/or exposed as a system parameter?

**Comment by tehn** [comment]
you have a prototype right now-- the i2c-controlled gain stage was removed on the production units.

the solution for prototypes is to have the levels set to unity at startup by the init scripts. i thought @simonvanderveldt and i fixed this a couple months ago, but perhaps recent images lost the i2c setup (given it's used by just a couple units out there now)

**Comment by simonvanderveldt** [comment]
@tehn The commands are still there, just prefixed with a `-` so they won't fail the unit https://github.com/monome/norns-image/blob/master/config/norns-init.service#L11

@catfact Did the `norns-init` unit run correctly for you?

**Comment by catfact** [comment]
ah  -sorry - i don't know. i'll check.


so @tehn can we remove the lua bindings for these hardware commands that aren't in the hardware anymore? can just set stuff from shell for protos right?

**Comment by tehn** [comment]
yes we can, and should. i apologize for not pulling them out sooner.

**Comment by simonvanderveldt** [comment]
@catfact Sorry, I missed the "input" part of the issue title, the link I posted goes to the commands for output.

The commands for the gain of the inputs are still in the unit but commented out https://github.com/monome/norns-image/blob/master/config/norns-init.service#L15
@tehn just to be sure: the gain staging was removed from both inputs and outputs?

**Comment by tehn** [comment]
correct. no i2c gain on input or output anymore for production units.
