### ISSUE TITLE
default / consistent parameter mappings for engines

### ISSUE THREAD

**Issue by catfact** [monome/norns#420]
messy discussion from forum around here:
https://llllllll.co/t/norns-development/14073/41?u=zebra

in a nutshell: it would be useful to have a discovery mechanism for lua scripts to know about engine parmeters - e.g. their ranges and preferred control mappings. 

one proposal (which i like) is to have each engine accompanied by a lua file declaring default parameters. 

e.g. `Engine_PolySub.sc` would be accompanied by, say, `Engine_PolySub.lua`.  this would include "boilerplate" code to add parameters mapped to appropriate single-argument commands:

```
engine.map_default_params = function() 
   params:add_control("cutoff", controlspec.new(0,32,"lin",0,8,""))
   params:set_action("cutoff", function(x) engine.cut(x) end)
   -- ... etc.
end
```

this file could be automatically executed by the `Engine` lua module when loading an engine. 

scripts can then decide to use the default mapping, ignore it, or partially override it.

**Comment by antonhornquist** [comment]
yeah. i've been giving this some thought after my `ack` and `gong` lua libs. in those libs i have focused on the visible UI parts (params) - it's not really the _engine_ perspective.

for instance stuff like gate and trig engine commands which typically arent presented in the menu > parameters are not covered. these i believe are important in a engine discovery type of module. all engine commands should be "introspect-able"/discoverable in such a module, which would facilitate building loosely decoupled scripts.

also i'm not very fond of my dependency on the `params` globals in those scripts. i've been thinking about simply creating a number of `control´ objects with suitable actions, that other libs push into `params` or any other paramset, if needed.

**Comment by antonhornquist** [comment]
(and such an engine approach does not need to exclude tagging presentable params and having a one-method-to-add-params-to-menu approach)

**Comment by tehn** [comment]
this has become the norm!
