### ISSUE TITLE
save in-progress TAPE recordings to a temp folder

### ISSUE THREAD

**Issue by tehn** [monome/norns#429]
and then copy them to audio/tape afterwards

so they can't be loaded elsewhere while recording

**Comment by catfact** [comment]
@tehn do you still want this? it's pretty easy to implement.

**Comment by tehn** [comment]
it's a pretty minor edge case, hardly urgent

i'm wondering if moving the file on completion creates any problems? or could the system call (from matron) be issued to auto-fork? ie `mv a b &`

**Comment by catfact** [comment]
there is no problem with doing this in crone if you want me to.

**Comment by tehn** [comment]
sure but i'd honestly just put it off until there's some other touching of the TAPE...

**Comment by catfact** [comment]
i'm going to add 'loop' to tape presently. (default on?) i can also add commands for 'pause' and 'seek'.
