### ISSUE TITLE
after submitting password, wifi list can change

### ISSUE THREAD

**Issue by jlmitch5** [monome/norns#430]
It seems like sometimes the wifi list can change out from under you when you finish submitting the password.  This may be due to varying signal strengths with competing networks.  It is difficult to get a consistently reproducible scenario.

The scenario is:

- Go to NETWORK tab of WIFI
- Scroll using encoder 3 to the desired network's SSID (let's say it's "AAA")
- Enter correct password for "AAA" and click ok
- When taken back to the previous screen sometimes a different SSID is listed (let's say "BBB")

This will result in a "password fail" auth error.

I seem to be able to get the correct behavior and a successful login only by explicitly selecting the "OFF" selection, and then going back to the NETWORK list, selecting my SSID, and attempting to connect again.

**Comment by ngwese** [comment]
there is work underway to revamp the wifi handling which should address stuff like this.

**Comment by jlmitch5** [comment]
👍 sounds good!
