### ISSUE TITLE
update the readme (stale function refs, etc)

### ISSUE THREAD

**Issue by pq** [monome/norns#433]
https://github.com/monome/norns/blob/master/readme-script.md

contains a bunch of stale references that are confusing folks.

see for example:

https://llllllll.co/t/norns-scripting/14120/76

**Comment by okyeron** [comment]
Would it be reasonable to take these Readme items and add them to the wiki section?

I would volunteer to do so if needed.

**Comment by simonvanderveldt** [comment]
@pq wouldn't it make sense to generate these docs as well? Similar to the [issue created for dust](https://github.com/monome/dust/issues/105)

**Comment by pq** [comment]
@simonvanderveldt: maybe!  are you thinking the docs could be embedded in source somehow?  curious what you're thinking...
