### ISSUE TITLE
callback registration

### ISSUE THREAD

**Issue by tehn** [monome/norns#444]
new approach to hardware (grid/arc/midi/etc) callback registration.

original proposition:

```
callbacks.register({
   'grid:*': mygridkey,
   'midi:nanopad': mycontrollercallback,
   'midi:*': other_midi_devices_callback,
})
```

which doesn't follow lua syntax, but the idea is there. alternatively:

```
register('grid', mygridkey)
register('midi:nanopad', ccdecode)
register('midi', otherthing)
```

what we need is the ability to differentiate devices.

**Comment by catfact** [comment]
you can already register callbacks for specific devices.

```
local grid = require 'grid'
for id,dev in ipairs(grid.devices) do 
   -- check dev.name here or whatever
   dev.key = function(x, y, z) ... end
end
```

**Comment by tehn** [comment]
yes. the idea is to have a simplified/centralized user method for defining a bunch of callbacks at once, such as the psuedo-syntax shown above. it's just a matter of designing the experience and building the glue... making sure we cover a range of use cases.
