### ISSUE TITLE
restructure dust scripts, SELECT menu, allow "projects"

### ISSUE THREAD

**Issue by tehn** [monome/norns#446]
### dust restructuring

- [x] move `dust/lib` to `norns` repo. encourage lua libs and engines to be collaboratively maintained/developed.

- [ ] remove the dust repo entirely. dust is now the local user folder. establish a "factory pack" of scripts that ship with a new device, or represent a cleanly-flashed image.

- [ ] proper matron startup behavior for non-existent `~/dust`

### projects

- [x] project folder logic. "projects" can contain a bunch of extra files in their folder:

- default pset files (these should get automatically copied to `dust/data` if the scripts data/subfolder does not exist on first run
- other data files (and/or default data files)
- audio files
- "private" libs/engines can exist inside a dust script subfolder ie `/scripts/tehn/lib`. lua subfiles need to be called by `include` (basically `do_file` with path logic) as `require` will not watch these paths (and deal dynamically with reloading). scripts should not attempt to use private libs from another project.

- [ ] standard init/reset behaviors for script `data` folder ie contents of `scripts/mlr/data` is default data (psets/etc)

### file management

see maiden issue

- [ ] upload single file from host
- [ ] download single to host
- [ ] upload zip (project) from host and auto-uncompress

### git integration

see maiden issue

- [ ] add git url
- [ ] pull git
- [ ] reset git (in case of local edits)
- [ ] generate ssh keys
- [ ] push git

### new menu behavior

- [x] SELECT menu is a flat list, no folder diving. scripts represented this way:

```
mlr
earthsea/polyperc
earthsea/pluck
ish
tehn/mlr
tehn/mlr/alt
tehn/others/halfsecond
```
where the folder structure is:
```
mlr/mlr.lua
earthsea/polyperc.lua
earthsea/pluck.lua
ish.lua
tehn/mlr/mlr.lua
tehn/mlr/alt.lua
tehn/others/halfsecond.lua
```
1. a "project" folder with a single file named the same as the folder.
2-3. a project folder with several files.
4. a raw lua file in the root folder
5-7. within a subfolder, same pattern

- _note_ 'lib' and 'data' folders are ignored in the list

- [ ] STARS (or favorites, whatever) is a set list. scripts can be added and sorted in specific order

- [ ] reset default script data (if default data is present for the project)

### transition

- [ ] fix all existing scripts to ensure they're not broken by this change

- [ ] encourage versioning in scripts. 1.0.0

**Comment by tehn** [comment]
extra feature (future):

- [ ] favorites / set list. be able to line up a bunch of scripts for sequential execution.
- [ ] be able to launch scripts in this set list with specific pset files (or passing args to `init()` ?)

**Comment by nf** [comment]
> favorites / set list. 

counterproposal: 'select >' menu shows 5 most recently used scripts and 'all >' at the bottom to browse everything. or maybe even the favs list could be auto-populated by LRU until the user has nominated favorites.

**Comment by tehn** [comment]
@nf very good suggestion

**Comment by jasonw22** [comment]
How will script, library, and engine updating work, especially when script changes depend on library or engine changes? As a user, how will I be informed about changes?

**Comment by jasonw22** [comment]
https://github.com/monome/maiden/issues/115 seems relevant to my questions, although project organization is an important piece of the puzzle.

**Comment by okyeron** [comment]
From a user perspective, what happens when I have 100+ scripts? That'd be a bunch of knob turning thru a long flat list.

Being able to subdivide a mass of scripts into groups (sub-folders similar to the current setup) would still be very useful.

**Comment by tehn** [comment]
re: long flat lists, agreed this is a concern.

alphabetical sorting and knob acceleration should make navigating relatively painless, but there's also been a proposition to have a "favorites" functionality which could be an ordered list, which would double as a "setlist" for sequential script execution during performance, for example.

we can explore the possibility of keeping subfolders, but i'm certainly not convinced that per-author is the correct structure.

**Comment by nf** [comment]
IMO it's worth trying the flat list initially and revisiting when we have the happy problem of too many scripts.

**Comment by pq** [comment]
> STARS (or favorites, whatever) is a set list. scripts can be added and sorted in specific order

been thinking about this again and would love to revisit the idea.

https://github.com/monome/norns/issues/987 to track.
