### ISSUE TITLE
main event loop should pause during blocking operations in lua

### ISSUE THREAD

**Issue by mhetrick** [monome/norns#461]
I'm experiencing weird behavior when performing a USB sync with the "wormhole" script open. As soon as the sync completes, there is a massive explosion of sound, as though the engine is attempting to catch up with a large queue of Lua messages. This slows norns down to a crawl. I can still navigate to SLEEP, but it takes many button presses until the machine responds.

**Comment by catfact** [comment]
renamed issue. more generally, the problem is that handling an event in lua blocks the main event loop.

**Comment by tehn** [comment]
other processes that block:

- UPGRADE
- WIFI operations (though generally shorter)

perhaps scripts/engines should just be shut down before any of these operations. this would require implementing `engine.shutdown()`

**Comment by tehn** [comment]
i meant running `cleanup()` which should null out any callbacks to `norns.none`

this seems sufficient to have the event loop continue but do nothing? or are you suggesting we'd overflow the event queue?

**Comment by tehn** [comment]
likely solution: https://github.com/monome/norns/issues/779
