### ISSUE TITLE
feature request: midi CC for toplevel system audio

### ISSUE THREAD

**Issue by nightmorph** [monome/norns#465]
it would be great to have midi control over things like aux fx send/return volume, fx parameters, input/output volume, and such. right now, it seems the only things that can have CCs assigned are a few parameters inside individual scripts. there doesn't seem to be a way to map anything at all outside of a script.

_example usage:_

a live performance with mlr. while mlr exposes a few per-track params such as volume, it would be fantastic if my nanokontrol could not just cover those, but also bring in the system's aux fx as desired.

i also have ideas for the old mlrv-style "press/hold buttons to toggle reverb/delay fx" on the grid itself, and also per-track fx sends (is that even possible, or is each dust script sending _all_ its output to the system aux fx?), but those are probably best placed in a dust/mlr feature request.

**Comment by tehn** [comment]
agreed, this is a feature i'd like to add.

this is actually possible within the script, but you'd have to manually map the cc. to change the "global" audio params, see the `mix` param table: https://github.com/monome/norns/blob/master/lua/menu.lua#L45

for example, if you'd like to send unity gain of mlr to the reverb:

```mix:set(aux output level', 0)```

and then back to -60db

```mix:set('aux output level',-60)```

**Comment by tehn** [comment]
FYI i'm possibly going to rename to `mix` paramset to `levels` in an upcoming update

**Comment by nightmorph** [comment]
so it would look something like:

`levels:set('aux output level', x)`

...inside the mlr script, or perhaps manually coding a CC assigned to the aux send, alongside my saved mlr params for CC-mapped track volumes?

**Comment by catfact** [comment]
@tehn, @nightmorph  is this something we need to add in norns? or can we leave it as a script feature?

**Comment by tehn** [comment]
the feature is to have cc mapping on-the-fly via menu same as script parameters.

we're planning to combine the system audio menu into the parameters menu, as discussed with @markwheeler so we can close this.
