### ISSUE TITLE
usb driver crashes

### ISSUE THREAD

**Issue by catfact** [monome/norns#469]
user reports new spate of crashes when plugging usb devices (especially grid / mlr) 

seems like a regression in 1.1.0 update

please post here with any more reproductions

**Comment by tehn** [comment]
i don't think this is a regression, it's just that grids and midi likely hadn't been tested together by many people.

observed:

- i've been seeing this strange behavior with midi + grid, where the grid seems to receive serial garbage, making the LEDs flip out. this typically ends with LEDs stuck on or all off, with no response from the grid. replugging fixes it.
- replugging to the same USB port typically means the issue will re-emerge within seconds to a minute
- plugging into a different port might actually no experience the issue (???)
- moving the midi plug to another port sometimes changes it

short of some issue with the hub itself (which i hope is not the case) i'm suspecting some sort of device collision issue? though i can't image how this could happen given we're using thoroughly hardened linux methods? any other thoughts? trying to imagine what could be happening in matron to cause this possibly.

**Comment by tehn** [comment]
additional report: https://github.com/monome/norns/issues/511

**Comment by tehn** [comment]
sometimes the eventual grid-freakout leads to endless errors:

```libmonome: error in write: Input/output error```

**Comment by tehn** [comment]
also got one of these:

```*** Error in `build/matron/matron': malloc(): memory corruption: 0x00141c50 ***```

**Comment by catfact** [comment]
well that one is an out-of-bounds write that extends to the next page of memory. hm..

(question: can anyone reproduce on x86? what about using an external hub?)

**Comment by catfact** [comment]
fwiw, i doubt the lua error is related.

**Comment by okyeron** [comment]
Yeah - I think my lua thing was user error with the new midi functions.

But more on libmonome errors... I Just got 20 of these (in maiden)

`libmonome: error in write: Resource temporarily unavailable`

Seems reproducible:
* rebooted pi-norns
* checked that SYSTEM->DEVICES->GRID are all set to none
* plug in teensy-grid device 1 
* plug in teensy-grid device 2

```
grid added:	1	monome 4676790	4676790
libmonome: error in write: Resource temporarily unavailable
libmonome: error in write: Resource temporarily unavailable
(...18 more times...)
grid added:	2	monome 2289490	2289490
```

**Comment by tehn** [comment]
apologies, but what is a teensy-grid? there's been no discussion of DIY teensy-based grids _ever_ on the forum etc. is this something you came up with? are you using a hacked libmonome?

**Comment by tehn** [comment]
digging into this deeper, i'm getting:

```
usb 1-1.4: urb status -32
```

from `dmesg` in bulk, right after a disconnect of USB MIDI.

this will often lead to what seems to be a USB hub reset, which kills then reconnects the wifi dongle.

is anyone else seeing this?

**Comment by tehn** [comment]
another data point.

1. grid plugged in, running `awake`
2. insert usb-midi device:

```
[  +0.133347] usb 1-1.3: New USB device found, idVendor=16c0, idProduct=0485
[  +0.000008] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  +0.000005] usb 1-1.3: Product: Teensy MIDI
[  +0.000004] usb 1-1.3: Manufacturer: Teensyduino
[  +0.000004] usb 1-1.3: SerialNumber: 1840180
[  +0.005512] hid-generic 0003:16C0:0485.0001: hidraw0: USB HID v1.11 Device [Teensyduino Teensy MIDI] on usb-3f980000.usb-1.3/input1
[  +0.058431] usbcore: registered new interface driver snd-usb-audio
[  +0.464421] WARN::dwc_otg_handle_mode_mismatch_intr:68: Mode Mismatch Interrupt: currently in Host mode
```

that final error is very strange.

resulted in the grid freaking out and then a stream of libmonome errors in matron.

**Comment by tehn** [comment]
another data point:

no `urb` errors in `dmesg` with disconnection/reconnection of grids and midi when matron is not running

**Comment by tehn** [comment]
holy smokes. this has the added issue of filling up the log files, which is probably why some people have full disks despite not having any TAPE recorded.

**Comment by tehn** [comment]
seeing initial success adding `dwc_otg.speed=1` to `cmdline.txt`

and doing an `apt-get upgrade`

no more `urb` errors from midi. got a few from grid.

matron seems not to be seeing grid disconnects now?

```
[  +3.620256] ftdi_sio ttyUSB2: usb_serial_generic_write_bulk_callback - nonzero urb status: -71
[  +0.000404] ftdi_sio ttyUSB2: usb_serial_generic_write_bulk_callback - nonzero urb status: -71
[  +0.000481] ftdi_sio ttyUSB2: usb_serial_generic_write_bulk_callback - nonzero urb status: -71
[  +0.036054] usb 1-1.4: USB disconnect, device number 13
[  +0.000194] ftdi_sio ttyUSB2: error from flowcontrol urb
[  +0.000204] ftdi_sio ttyUSB2: FTDI USB Serial Device converter now disconnected from ttyUSB2
[  +0.000618] ftdi_sio 1-1.4:1.0: device disconnected
```

---

edit: now grid replugging is working?? still same error as above.

**Comment by tehn** [comment]
now to test is just editing `cmdline.txt` on the existing image fixes it, without all the kernel changes and apt-get

**Comment by okyeron** [comment]
> now to test is just editing cmdline.txt on the existing image fixes it

FWIW - I tried this just now and I'm not seeing any `urb` errors with 2-3 different midi devices plugged/unplugged.

**Comment by tehn** [comment]
confirmed.

downside: only USB1.1 is supported now. this shouldn't be a big issue, but we'll return USB2 support once the kernel is fixed.

rolling this into update 180904 (building now)

**Comment by okyeron** [comment]
data point followup - with the change to cmdline.txt (i.e. defaulting to USB 1.1), my Roland TR-8 and TR-09 do not show up as MIDI devices when plugged in (they show up properly if I revert cmdline.txt back to stock). 

So I suppose there are some devices that will not work with USB 1.1

**Comment by okyeron** [comment]
Another data point (perhaps unrelated, but wasn't sure it needed its own issue) :

Unplugging my teensy grid on RasPi norns gives me a string of these errors while watching` journalctl -f`

```
Sep 14 16:37:57 norns jackd[336]: JackEngine::XRun: client = supernova was not finished, state = Running
Sep 14 16:37:57 norns jackd[336]: JackAudioDriver::ProcessGraphAsyncMaster: Process error
Sep 14 16:37:57 norns jackd[336]: JackEngine::XRun: client = supernova was not finished, state = Triggered
Sep 14 16:42:14 norns jackd[336]: JackAudioDriver::ProcessGraphAsyncMaster: Process error
Sep 14 16:42:14 norns kernel: usb 1-1.3: USB disconnect, device number 9
```

**Comment by okyeron** [comment]
Circling back on this - in `dmesg` I'm seeing a bundle of the 
`[ 9221.447023] usb 1-1.3: urb status -32` 
errors again on RasPi with my DIY grid/arc and midi devices - seems to be more on device disconnect than on connect.

maiden dumps a number of these as well
```
libmonome: error in write: Input/output error
libmonome: error in write: Resource temporarily unavailable
libmonome: error in write: Resource temporarily unavailable
```

Did the kernel get updated with something specific to fix this on norns hardware?

I've been working from the stock stretch kernel because the beta kernel would just hang/freeze on the RasPi boot screen.
