### ISSUE TITLE
"x is not defined in any file" / NONE (error: AUDIO ENGINE)

### ISSUE THREAD

**Issue by joakimhellgren** [monome/norns#472]
See posts made in update thread on lines for documentation on the issue. 

we@norns:~/norns$ ./stop.sh
scsynth: no process found
we@norns:~/norns$ ./crone.sh
attempting to bind socket at url ws://*:5556
compiling class library...
        Found 594 primitives.
        Compiling directory '/usr/share/SuperCollider/SCClassLibrary'
        Compiling directory '/usr/share/SuperCollider/Extensions'
        Compiling directory '/home/we/.local/share/SuperCollider/Extensions'
ERROR: Superclass 'CroneGenEngine' of class 'Engine_Gong' is not defined in any file.
/home/we/.local/share/SuperCollider/Extensions/dust/sc/Engine_Gong.sc
ERROR: Superclass 'CroneGenEngine' of class 'Engine_Shift' is not defined in any file.
/home/we/.local/share/SuperCollider/Extensions/dust/sc/Engine_Shift.sc
ERROR: Superclass 'CroneGenEngine' of class 'Engine_Bob' is not defined in any file.
/home/we/.local/share/SuperCollider/Extensions/dust/sc/Engine_Bob.sc
ERROR: Class extension for nonexistent class 'HistoryGui'
     In file:'deprecated/3.9/HistoryGui.sc'
ERROR: There is a discrepancy.
numClassDeps 1417   gNumClasses 2828

**Comment by joakimhellgren** [comment]
unit also freezes after this and needs a hard reset.

**Comment by antonhornquist** [comment]
The reason for this error is that sclang won’t start at all if all required classes are not present - this is a SuperCollider thing, it compiles all classes on startup and won’t start when there’s a discrepancy. The missing class is in a file called CroneGenEngine.sc that should reside in the ”~/dust/lib/sc/abstractions” folder. Please check whether this file exists on your device by connecting via SSH or serial. If not I think something’s gone wrong in the update. 

Ctrl-D in your SSH session should get you back to the command prompt. You should not need to hard reset if you’re connected via ie. SSH. ”sudo shutdown now” should work.

**Comment by joakimhellgren** [comment]
deleting the version.txt caused the unit to update 180603 on power up after I restarted it. 
The issue was still there, but after upgrading it once more to the latest release from the same USB drive everything seem to be working again.

I'm not sure what caused the issue, however when i plugged in my USB drive from which I had initially tried to update to, my computer notified me about the drive needing a disk repair.
