### ISSUE TITLE
allow executing scripts without saving

### ISSUE THREAD

**Issue by catfact** [monome/norns#473]
maybe this is more properly a maiden issue but would also need support in norns/lua.

clicking "run" from maiden actually saves the editor contents to disk and executes `norns.script.load` with the filename. 

it seems like unexpected behavior, especially since a "save" button also exists. 

`norns/script.lua` should probably have a way to accept a chunk of lua code in lieu of a filename, which seems like an easy change.

**Comment by tehn** [comment]
this works in maiden now. hotkey ctl/cmd-8 executes selected text
