### ISSUE TITLE
xvfb required to run sclang without $DISPLAY

### ISSUE THREAD

**Issue by lazzarello** [monome/norns#475]
I don't know yet where to add this to the Raspberry Pi build instructions but I figured out how to run `sclang` without a screen through Xvfb. Writing notes here for the future.

```
sudo apt-get install xvfb
export DISPLAY=:0
Xvfb :0 -ac -screen 0 1280x1024x16 &
sclang
sc3> {SinOsc.ar(440,0,0.2)}.play
```

This should produce some sound.

**Comment by tehn** [comment]
@lazzarello i'd suggest adding this as an addendum to the raspberry pi build instructions, though we haven't seen this issue in the past.

**Comment by lazzarello** [comment]
@artfwo supercollider requires X to run, in the form of `sclang`. There is an [open issue upstream](https://github.com/supercollider/supercollider/issues/1736). @tehn , what magic did you do to make this not an issue?

**Comment by catfact** [comment]
@lazzarello afaict, that issue only applies when building SC with QT but without X.

like i said on yr other issue, norns.catfact.net also provides a custom supercollider build that is configured for headless deployment. in particular it is built with `DSC_QT=0` among other things. the full cmake config can be seen here:
https://github.com/monome/norns/issues/435

**Comment by lazzarello** [comment]
HA! The secrets are revealed. This makes sense why my build required X.
