### ISSUE TITLE
scripts in subfolders under script/[author] lock menu cursor to menu > parameters

### ISSUE THREAD

**Issue by antonhornquist** [monome/norns#486]
I'm aware of discussions on changing script folder structure, but i guess this may be good to know anyhow. Cursor gets locked in menu > parameters when script is not contained directly under author folder.

To recreate:
1. create a script utilizing params and add it to a folder under `script/[author]`, such as `script/jah/r`
2. load (select) the script
3. go to MENU > PARAMETERS.
4. press key2 to go back to MENU

Expected behavior: cursor should navigate back to main menu page.
Actual behavior: cursor remains in MENU > PARAMETERS.

I believe this is due to some bug in menu logic. An error is thrown here: https://github.com/monome/norns/blob/master/lua/menu.lua#L1020

Stacktrace in screenshot.

![image](https://user-images.githubusercontent.com/32165/43992568-8eb02890-9d80-11e8-9c22-85d6f928acb3.png)

**Comment by catfact** [comment]
@tehn @antonhornquist is this still happening?

**Comment by tehn** [comment]
will not fix as i'll be shortly rewriting this entire system
