### ISSUE TITLE
Naming of "aux" and "insert" in system audio menu

### ISSUE THREAD

**Issue by emenel** [monome/norns#488]
Question:
- Is there a reason that "aux" and "insert" in the system audio menu are not named for their function?

In the manual, and based on what they do, it seems like "aux" is only reverb, and "insert" is only the compressor. Are there future plans to expand the aux and insert options? If not I would suggest naming them more clearly in relation to what they do.

It might also make sense to do this for any future system level effects, as internal routing in this menu system could be confusing and more complex than necessary. 

I suggest renaming "aux" to "reverb" and "insert" to "compressor" as well as updating the parameters with the same type of clear nomenclature.

My suggested changes:

Reverb:
rev: on/off
rev engine level: engine output -> aux input
rev input 1 level: input 1 -> aux input
rev input 2 level: input 2 -> aux input
rev input 1 pan: pan for input 1
rev input 2 pan: pan for input 2
rev output level: aux output -> main output

rev pre delay: reverb delay time
rev lf x: reverb low frequency crossover
rev low time: reverb low time
rev mid time: reverb mid time
rev hf damping: reverb high frequency damping

Compressor:
comp: on/off
comp mix: dry/wet (dry = 0.0, wet = 1.0)
comp ratio: compressor ratio
comp thresh: compressor threshold
comp attack: compressor attack time
comp release: compressor release time
comp makeup: compressor makeup gain

**Comment by catfact** [comment]
> Are there future plans to expand the aux and insert options? 

yes

**Comment by emenel** [comment]
At the moment they are not busses though, they are single effects. 

Does that concept of a bus make sense inside of Norns? I'm not so sure. Managing internal routing, building chains, etc, could be very complex at the system level and might be better as part of individual scripts.

If we want master effects like reverb and compression are they really busses? Or are they just master effects?

I find the current naming and structure confusing.

**Comment by emenel** [comment]
(for example, the way delay is handled in foulplay makes sense to me as an effect that you can "send" your tracks to)

**Comment by catfact** [comment]
yes, they are really busses. (well, the aux bus is.) you can send any signal to the aux bus from any engine, in addition to the hardcoded routes from inputs and outputs.

**Comment by catfact** [comment]
i also don't actually care what the menu says, and am only responding to your questions.

**Comment by tehn** [comment]
adding a HEADING field in parameter sets (to separate groupings) would be a nice addition (currently we only have SEPARATOR which is the three dashes)

made an issue, it's a good idea: https://github.com/monome/norns/issues/491

**Comment by tehn** [comment]
if you agree, i'd like to close this issue in favor of #491 ?

**Comment by catfact** [comment]
> (although I'm still not sure how the ui would support it, 

probably something one would have to customize at the script level.

**Comment by emenel** [comment]
Agreed.

In the short term could I suggest two quick language changes to this current menu?

- "aux output level" : "aux engine level" (current wording isn't clear that this is about how much of the engine audio to send)
- "rev in delay" : "rev pre delay" (more common on reverb effects)
- "rev low rt60"/"mid rt60" : "rev [low/mid] time" (more consistent with other reverbs, took me some googling to figure out what rt60 means)

**Comment by tehn** [comment]
issue re: swappable aux/insert: https://github.com/monome/norns/issues/492
