### ISSUE TITLE
Prevent HardReset's endless crashes

### ISSUE THREAD

**Issue by martinmestres** [monome/norns#495]
A line of code i wrote in maiden makes my norns crash (freeze). Hard resetting won't work because the last used code is automatically executed and the bad script make it crash again etc....
So:
In case of **hard reseting while KEY 1 is pressed** execute "AWAKE" at startup.

**Comment by nf** [comment]
Another idea: don't load any user script on startup if norns was not shut down gracefully (through the 'sleep' menu option). That wouldn't require any special knowledge to get out of a bad state.

**Comment by tehn** [comment]
@nf excellent idea

**Comment by nf** [comment]
I'll take a crack at it.

**Comment by tehn** [comment]
you'll get a glimpse at the scary guts of `menu.lua` which may drive you away ;)

perhaps the best approach is to add an argument to `state.save` (0 or 1) which is then passed to a new line in the file "cleanshutdown" (etc). and then have this line only written 1 when called from `SLEEP` ?

**Comment by nf** [comment]
Yep that's exactly what I was thinking; adding `state.cleanShutdown = false` by default.
