### ISSUE TITLE
supernova not found 

### ISSUE THREAD

**Issue by TheTechnobear** [monome/norns#503]
updated to master, now getting 
sc3> /bin/sh: 1: exec: supernova: not found

when running sclang

I assume this is to do with now using supernova.

Ive 'upgraded' from http://norns.catfact.net/  but issue persists.

has the new sc build (with supernova) not been packaged, and uploaded to catfact? 

if not, then I will build supercollider* myself (no issue there :) )

if we now expect SC to be build from source, then we need to  update readme-setup.md.

p.s. also one of the supernova PR's indicates submodules are used , so git submodule update --init is required, but this appears not to be the case... correct?

**Comment by artfwo** [comment]
Hi Mark,

Please use the following URL `https://package.monome.org/` to get new sc3 packages. We should update the docs to reflect that, but feel free to open a PR on that as well. Hope this helps!

**Comment by TheTechnobear** [comment]
you also need to add supernova to the the install list
e.g 
sudo apt-get install  supercollider-supernova*

**Comment by artfwo** [comment]
Thanks, added that to the instructions too!

**Comment by okyeron** [comment]
For reference - which instructions should I be tracking here?

**Comment by tehn** [comment]
from norns-image:

```
# monome package apt
sudo cp config/norns.list /etc/apt/sources.list.d/
```
