### ISSUE TITLE
no error message if audio engine fails to start

### ISSUE THREAD

**Issue by TheTechnobear** [monome/norns#504]
look like now if the audio engine (scsynth/lang) fails to start, you no longer get a message to indicate this.

note:
this is on my push2 build of master, so possibly someone needs to verify this on norns hardware... 
(but my display is working in all other ways, so seems likely its a general issue)

**Comment by tehn** [comment]
i'm mid-process working the error reporting. the removal of the audio error is incorrect and it's back in my local branch. sit tight.

**Comment by tehn** [comment]
fixed in the whitespace cleanup.
