### ISSUE TITLE
http://norns.catfact.net/debian/Packages  404  Not Found

### ISSUE THREAD

**Issue by rross101** [monome/norns#508]
Working through build instructions [here](https://github.com/monome/norns/blob/master/readme-setup.md) and this repository is not working.

(first issue report - sorry if in wrong place or if I'm missing something obvious)

**Comment by rross101** [comment]
OK, got it - from (this) [https://github.com/monome/norns/issues/503] issue here - I think it needs changed to package.monome.org

**Comment by tehn** [comment]
i'm also going to add a "none" option for device ports.

**Comment by tehn** [comment]
paste error, apologies. fixed on github comment!
