### ISSUE TITLE
Trouble with grid and mio USB>MIDI interface

### ISSUE THREAD

**Issue by markwheeler** [monome/norns#511]
I've been using a simple USB>MIDI interface, the [iConnectivity mio](https://www.iconnectivity.com/products/midi/mio/), to connect norns. This works fine when no grid is connected. And the grid works fine when the mio isn't connected.

But when both are plugged in I see:
- 'Tearing' of grid led refreshes, ie, part of the grid updates out of sync with another half/quarter. General stuttering of grid led updates. Tested varibright 256 and greyscale 128.
- Occasional random lights in upper left section of grid or whole grid dims.
- Occasional grid reconnects. All leds go bright, then startup pattern shows momentarily, then back to normal.
- Lost MIDI messages sent via mio. Have tested this less but occasionally I see missing note messages that I've been unable to recreate when the grid isn't connected.

I don't have to be sending or receiving any MIDI data for the grid to have issues - even with the mio disconnected at the DIN end and no MIDI stuff in a script, the problem still shows. I have the wifi nub and power connected.

It seems that somehow the two devices are interfering with each-other. Has anyone else seen this or have a suggestion for how to debug further?

**Comment by tehn** [comment]
thanks for the thorough report!

duplicate: https://github.com/monome/norns/issues/469
