### ISSUE TITLE
softcut write head interpolation

### ISSUE THREAD

**Issue by tehn** [monome/norns#519]
split issue #407 

quoting @catfact 

> but yes, resampling the write head correctly is another related task. the changes insoftcut-resample branch work very well on amd64 systems, but the buffer writes in the Resampler class totally crash on ARM for some obscure reason i haven't yet identified.

**Comment by catfact** [comment]
@tehn 
i checked out softcut-resample branch again and seems working fine, made a couple fixes.

extracted the logic into standalone project for easier debugging. haven't tried on ARM yet, will get to it ASAP but in the meantime here is the project in case anyone has an itch to try it:
https://github.com/catfact/softcut
