### ISSUE TITLE
Avoid sending data to MIDI devices that aren't selected

### ISSUE THREAD

**Issue by markwheeler** [monome/norns#530]
One thing i noticed with the MIDI API is that it relies on scripts checking `attached()` to keep things tidy. ie, if I connect to a virtual port which has a device attached with `midi.connect(1)`, then go into the devices menu and switch the virtual port to ‘none’, the device keeps getting sent MIDI data. This continues even after restarting the script.

I wonder if we should be checking `attached()` somewhere in the MIDI class before sending data or somehow cleaning up the devices that were attached to that port?

**Comment by tehn** [comment]
fixed in 1.0.3
