### ISSUE TITLE
save MIDI along with audio from tape recording

### ISSUE THREAD

**Issue by jlmitch5** [monome/norns#538]
No idea how feasible this is, but it'd be awesome if any midi output that happens during a tape recording saved to a midi file with the same name as the tape file!

**Comment by tehn** [comment]
this is conceivable, but i'm not quite sure how it would integrate into the system design. for example, what if a script only outputs midi? it'd be silly to record a blank sound file--- suggesting any such midi functionality should be decoupled, or at least highly configurable. trying to consider the playback analogy as well... would playing back a midi file mean directing the file to midi inputs?
