### ISSUE TITLE
libmonome fail on disconnect of "series" edition grids

### ISSUE THREAD

**Issue by markwheeler** [monome/norns#539]
When I unplug my gs128 I get a flood of callbacks on the grid key event with x, y and z values all coming in as 1.
Using a varibright 256 I don't see the same issue.
Minor but reproducible every time.

**Comment by tehn** [comment]
this is likely the same issue that is causing gs not to work with a (eurorack) usb switch between norns and earthsea/etc.

**Comment by tehn** [comment]
highly suspect #542

**Comment by tehn** [comment]
confirmed failing behavior with other mono-bright grids of the "series" generation/protocol

worth checking if libmonome is working properly for these older devices.

tested fine with a variety of newer (2012-on) "mext" protocol devices
