### ISSUE TITLE
'SCRIPT ERROR: NO SCRIPT' after stop/start

### ISSUE THREAD

**Issue by okyeron** [monome/norns#540]
I'm seeing this pretty regularly since the new update.

I will do something that crashes part of norns and run `stop.sh` and `start.sh`. When norns comes back up it shows `### SCRIPT ERROR: NO SCRIPT` (in maiden) or `NONE (error: NO SCRIPT)` on the norns display.

Second test. I just tried running `stop.sh` and `start.sh` again (not a crash situation) and had the same result.

Steps:
* load earthsea in maiden
* run stop.sh from terminal
* run start.sh from terminal
* results in `NONE (error: NO SCRIPT)`

**Comment by rross101** [comment]
Ah - I had assumed this was just normal behaviour - when resetting the software it doesn't load a script; and the message is letting you know that. Can still load a new script after this?

**Comment by okyeron** [comment]
Yes. No problem loading a script at that point. I think the "problem" here is that it _forgets_ which script was loaded - which did not happen prior to the recent update.

**Comment by tehn** [comment]
this is correct behavior.

there's a "clean shutdown" flag that is set (to the system.lua file) when executing "sleep"

if matron is quite any other way, the shutdown is regarded as not clean, and the last script will not be reloaded. this is to protect from infinite-loop broken script loading after reboot.
