### ISSUE TITLE
LEVELS input control does nothing presently

### ISSUE THREAD

**Issue by tehn** [monome/norns#544]
input control should be a gain (attenuate only?) pre-engine input.

**Comment by catfact** [comment]
https://github.com/monome/norns/issues/543 ?

**Comment by tehn** [comment]
slightly related. though i can't understand what's going on with marcus' setup. it's working here.

input, has never worked. i didn't hook it up.

**Comment by catfact** [comment]
> it's working here.

this is one reason i suspect some engine de-initializing something it shouldn't, in cleanup. that would make the appearance of the problem dependent on order of engines executed.

**Comment by tehn** [comment]
yep, worth investigating.

weird that he's getting it on a fresh boot though.

re: input issue. traced it all the way from `menu.lua` down through `oracle.c` to `CroneAudioContext.sc` and it all looks correct to me. need a set of sc eyes @catfact @antonhornquist 

trace:

https://github.com/monome/norns/blob/master/lua/menu.lua#L58
https://github.com/monome/norns/blob/master/lua/norns.lua#L143
https://github.com/monome/norns/blob/master/lua/audio.lua#L12
https://github.com/monome/norns/blob/master/matron/src/weaver.c#L259
https://github.com/monome/norns/blob/master/matron/src/weaver.c#L1660
https://github.com/monome/norns/blob/master/matron/src/oracle.c#L421
https://github.com/monome/norns/blob/master/sc/core/Crone.sc#L412
https://github.com/monome/norns/blob/master/sc/core/CroneAudioContext.sc#L100

**Comment by antonhornquist** [comment]
i'm pretty sure this is due to there is no \level arg in the \adc SynthDef used for in_s:
https://github.com/monome/norns/blob/master/sc/core/CroneDefs.sc#L93

so this won't make any difference:
https://github.com/monome/norns/blob/master/sc/core/CroneAudioContext.sc#L100

this should be easy to fix. i'll check it out now
