### ISSUE TITLE
MIDI vports showing old connections

### ISSUE THREAD

**Issue by okyeron** [monome/norns#547]
Running a few tests on MIDI connections with the 180904 update...

I could not find the previous post where @tehn mentioned the "+" designation for duplicate devices (or remember where it was mentioned)

But here's my test (running scripts from maiden) - plugging and unplugging 2 differnt midi devices gives me something like this

```
    print("midi.list:")
    tab.print(midi.list)
```
```
midi.list:
1	Code
2	Code+
3	Code++
4	QuNexus
5	QuNexus+
6	Code+++
```

but vport seems to not get the most recent connected device of the same name and shows the older ones as `attached` 

```
    for x,y in pairs(midi.vport) do
        tab.print(y)
    end
```
```
name	Code
attached	true
callbacks	table: 0x1bb1998
index	0
send	function: 0x1baa1f0
name	Code+
attached	true
callbacks	table: 0x1bb19c0
index	0
send	function: 0x1b43458
name	Code++
attached	true
callbacks	table: 0x1bb1a80
index	0
send	function: 0x1ba2700
name	QuNexus
attached	true
callbacks	table: 0x1bb1aa8
index	0
send	function: 0x1bad0f0

```

**Comment by okyeron** [comment]
yes indeed. rpi3b+. 
I did add `dwc_otg.speed=1` to `/boot/cmdline.txt`

USB disconnects seem to be working from `dmesg` output, but let me restart and confirm something...

**Comment by okyeron** [comment]
Is this related? (or just a 0-based vs 1-based array problem)

output from maiden while plugging and unplugging the QuNexus twice. 
```
midi added:	5	QuNexus
dev_delete(): removing device 4
midi added:	6	QuNexus
dev_delete(): removing device 5
```

(either way this output is somewhat confusing.)

**Comment by tehn** [comment]
this is a symptom of #542
