### ISSUE TITLE
MIDI device select does not scroll

### ISSUE THREAD

**Issue by okyeron** [monome/norns#548]
`SYSTEM>DEVICES>MIDI>device 1>` is limited to 4 items on screen - but does not scroll. You can scroll offscreen to select an item further down the list.

something needed around line 1176 in `menu.lua` to set position?

**Comment by tehn** [comment]
i'll rewrite the scroller.

typically the "normal" case will have only 2-3 devices max, so i was cutting corners. the + bug of course exposed this issue.

**Comment by tehn** [comment]
symptom of #542
