### ISSUE TITLE
midi_device:reconnect bad argument error

### ISSUE THREAD

**Issue by markwheeler** [monome/norns#561]
What's the correct usage of `midi_device:reconnect(value)` ?

I seem to get errors whenever I'm trying to use this tied to a param callback with value 1 to 4. Not sure if I'm just using it wrong or if it's a bug in midi.lua. I see:

`lua: /home/we/norns/lua/midi.lua:108: bad argument #1 to 'remove' (position out of bounds)`

**Comment by tehn** [comment]
will check this out!
