### ISSUE TITLE
params:add (helper function)

### ISSUE THREAD

**Issue by tehn** [monome/norns#569]
ie

```lua
params:add{control: 'freq_mod_env1', name: 'Frequency Mod (Env-1)', spec: specs.FREQ_MOD_ENV, action: engine.freqModEnv}
```

- name is derived from the value for control if not explicitly specified.
- param type `control` derived from the fact that it's the only arg of the set {control, option, number, etc} present
- throw a friendly error if the main arg isn't a table

cc @pq

**Comment by pq** [comment]
as motivation, the call proposed above would replace these two-lines

```lua
params:add_control("Frequency Mod (Env-1)", specs.FREQ_MOD_ENV)
params:set_action("Frequency Mod (Env-1)", engine.freqModEnv)
```

in the case where index is OK for a name, the call could be even simpler:

```lua
paramset:add{ control: 'monitor',  spec: cs.MAIN_LEVEL, action: function(x) norns.audio.monitor_level(x) end }
```

since this is pretty common, param initialization could get a bunch simpler for the common case.

**Comment by tehn** [comment]
changed spec, now explicit `type` is required.

```
paramset:add{ type="control", id="level", action=engine.level }
```
