### ISSUE TITLE
consider allowing `metro.alloc` config by table

### ISSUE THREAD

**Issue by pq** [monome/norns#570]
along the lines of #569, consider updating `metro.alloc` to allow for configuration by table.

```lua
counter = metro.alloc()
counter.time = 0.1
counter.count = -1
counter.callback = count
```

can currently be simplified to:

```lua
counter = metro.alloc(count,0.1,-1)
counter.callback = count
```

(but rarely is).

a table could take this a little further, allowing for `callback` assignment and also potentially be more readable:

```lua
counter = metro.alloc{time: 0.1, count: -1, callback: count}
```

**Comment by pq** [comment]
@tehn: if we do this maybe we should re-think the name `callback` while we're at it?

**Comment by tehn** [comment]
agreed re: `callback`

and also `alloc` 😬

**Comment by pq** [comment]
> agreed re: callback

`event`?  (a la midi?)

> and also alloc

maybe `init`?  (the zero arg version could continue to do what it does now.)

or re-jigger `new`?

**Comment by tehn** [comment]
`event` i think is good.

`init` probably makes sense as well.

**Comment by pq** [comment]
great.  updated w/ these names we'd have:

```lua
counter = metro.init{time: 0.1, count: -1, event: count}
```

which looks pretty good to me!
