### ISSUE TITLE
consider generating API docs as part of the build

### ISSUE THREAD

**Issue by pq** [monome/norns#590]
currently the docs are getting generated manually and are unsurprisingly laggy.

![image](https://user-images.githubusercontent.com/67586/46622484-a59f5300-cadf-11e8-8339-3ced2c477089.png)

(see #589.)

it would be great to automate generation (for `lua` and `sc`).

i'm not sure how exactly this would work with how we're currently hosting docs but i think we could use `gh-pages` without too much hassle.

**Comment by tehn** [comment]
current the API docs are not hosted on the web. i think it'd be sensible to investigate gh-pages as an update to monome.org requires a manual trigger as well.

agreed that travis automation would be great for this!

**Comment by tehn** [comment]
re: hosting docs = https://github.com/monome/norns/issues/484

**Comment by pq** [comment]
initial implementation of deploy to gh-pages complete. 🎉 

https://monome.github.io/norns/doc/

still todo:

* #593 
* #595 
* #594
