### ISSUE TITLE
update gh pages styling

### ISSUE THREAD

**Issue by pq** [monome/norns#594]
i opted for the "minimal" theme but we should consider polishing it a bit to be more consistent w/ other monome sites.

![image](https://user-images.githubusercontent.com/67586/46683782-e9f52680-cba5-11e8-8ca8-dd69f30c15ea.png)

@tehn: any thoughts?

**Comment by tehn** [comment]
looks great! i can take a pass at the css for some synchronization

**Comment by pq** [comment]
groovy.  thanks @tehn!

if styling is in a jekyll theme it it should be as simple as updating [_config.yml](https://github.com/monome/norns/blob/master/_config.yml) to point to it.

see: https://blog.github.com/2017-11-29-use-any-theme-with-github-pages/

**Comment by tehn** [comment]
i am going to remove this site entirely, as i believe all the content is better served by the main docs and just the git repo itself.
