### ISSUE TITLE
consider styling api docs

### ISSUE THREAD

**Issue by pq** [monome/norns#595]
![image](https://user-images.githubusercontent.com/67586/46683861-1dd04c00-cba6-11e8-9307-f9569f5fdce9.png)

it'd be nice to modernize this a bit.

**Comment by tehn** [comment]
agreed.

also applies to https://monome.org/docs/modular/teletype/manual/ possibly

**Comment by jlmitch5** [comment]
@tehn @pq would be happy to help out with the implementation of this.  Do y’all have ideas for the actual design side of things (or ideas of how we could open it to people interested in that from the community)?

**Comment by pq** [comment]
awesome!

i don't have any ideas specifically...  it should just look better. 😬 

i wonder if we could crib some CSS from other doc generators?  alternatively maybe there are some good more modern lua doc templates we could borrow from?

@tehn : did you have any specific ideas?

**Comment by tehn** [comment]
no specific ideas but would love to have you take it on. as Phil said,
modernizing is a good guiding goal

b

**Comment by ocreurer** [comment]
Currently working on mocks for the TT manual with @jlmitch5. Should have more extensive designs by the end of the weekend, which could perhaps be re-purposed for the Norns API docs. Will share those in the [corresponding thread](https://llllllll.co/t/web-documentation-design-ideas-and-inspiration/16779/17) on lines as soon as they're ready.

**Comment by tehn** [comment]
success on teletype!
