### ISSUE TITLE
Adjustable brightness for connected grids

### ISSUE THREAD

**Issue by jlmitch5** [monome/norns#599]
I am currently on a plane, and I brought my Norns and grid along to keep me company on the flight.  I learned that the grid was a bit bright, and I am a little self conscious to use it as it might disturb other passengers near me.

Would be cool if there was a way to adjust brightness.  Not sure if it would be possible to do so and still maintain the same 15 levels of granularity.

**Comment by tehn** [comment]
this is possible. grids have an overall brightness setting which is not
associated with the 25 steps.

trying to figure out where that would go in the ui

**Comment by okyeron** [comment]
Aha. For my own curiousity - where (in what file) does that libmonome communication with grid devices happen? (I'm interested in tracking down some libmonome errors I get sometimes from my DIY grid)

**Comment by tehn** [comment]
https://github.com/monome/norns/blob/master/matron/src/device/device_monome.c

**Comment by okyeron** [comment]
Great. Thank you. That's where I was looking, but wanted to be sure.

**Comment by tehn** [comment]
implemented in v2.2.3

no menu UI yet, but other issue addresses that
