### ISSUE TITLE
engine unload on cleanup

### ISSUE THREAD

**Issue by tehn** [monome/norns#604]
engine should get explicitly unloaded on cleanup (script unload)

**Comment by catfact** [comment]
there's an OSC path for explictly freeing the engine
https://github.com/monome/norns/blob/master/sc/core/Crone.sc#L362
but it's missing weaver/lua glue

**Comment by tehn** [comment]
added glue: https://github.com/monome/norns/tree/free_engine

but it doesn't seem to actually unload the engine? tested with `awake` which uses `PolyPerc` by typing `free_engine()` into the REPL and confirming that sc received the command

**Comment by catfact** [comment]
ahh my bad

**Comment by catfact** [comment]
fixed by PRs #613, #614
