### ISSUE TITLE
TAPE: option to record input channels

### ISSUE THREAD

**Issue by tehn** [monome/norns#605]
currently output channels are captured.

likely TAPE needs some settings. option to capture input and/or output. (ie, no output capture could make it work just like an input recorder, which seems useful at times).

need to look into split-file sync, if supercollider can accurately start two file recorders at once. otherwise a quad file might be an option.

**Comment by catfact** [comment]
> need to look into split-file sync, if supercollider can accurately start two file recorders at once. otherwise a quad file might be an option.

both options should work fine. either way, we should make a custom version of the `Recorder` class. it should take a new argument to `prepareForRecord` setting the record mode.

it sounds like we want three modes: 0 == record output, 1 == record input, 2 == record both. 

with mode=0/1, all that changes is the source bus argument to Recorder. the basic stereo recording synthdef is unchanged.

with mode=2, the two options are:
- 1. dual stereo files
    start:
        allocate two streaming buffers, prepare two files
        use a different synthdef that contains two DiskOuts
   stop: free synth, write+close two files, close two buffers.

- 1. dual stereo files
    start:
        allocate two streaming buffers, prepare two files
        use a different synthdef containing two DiskOuts. this should have tighter sync that spawning two synths (whose start time may differ up to one control period.)
   stop: free synth, write+close two files, close two buffers.


- 2. single quad file
    start. 
        same as stereo mode, but different args to streaming buffer, different SynthDef that simply expands the input to `DiskOut`.
   stop: 
        same as stereo mode, but optionally reload and split the output file.

i think option 2 would be cleaner and more flexible, but both are fine and the difference should be basically transparent to the user.

**Comment by antonhornquist** [comment]
(nit)

> use a different synthdef containing two DiskOuts. this should have tighter sync than spawning two synths (whose start time may differ up to one control period.)

I believe you are able to sync two synths creations using `s.makeBundle`.
