### ISSUE TITLE
Wifi status reads "password fail" with correct password

### ISSUE THREAD

**Issue by lazzarello** [monome/norns#607]
I'm typing this message on the same wifi network as I'm trying to connect Norns. It was connected fine yesterday, then I took the device to another place with a wifi network that has no password. It connected successfully to that network.

Now I'm back on my home network and the device says "password fail" and sometimes, it says "failed". Hotspot mode works, so I don't think it's hardware. I don't think it's the router because my laptop and phone are connected to the same one.

`~/wpa_supplicant.conf` doesn't seem to have much interesting stuff regarding passwords. The systemd unit for it has no logs exposed via journalctl. I'm worried if I mess with the system `wpa_supplicant.conf` I will render my device impossible to upgrade. I can do a serial connection via USB, right?

*update* I did the following in hotspot mode
```
mkdir ~/configs.bak
mv ~/*.wifi ~/configs.bak/
sudo halt
```
removed the wifi dongle, powered up the system, inserted the wifi dongle, added the same password again through the menu.

Connection succeeded.
```
$ md5sum configs.bak/psk.wifi psk.wifi 
85b5095e6cc5dcdbc0c5be5c3e575339  configs.bak/psk.wifi
85b5095e6cc5dcdbc0c5be5c3e575339  psk.wifi
```

It doesn't look like there is any [logging in wifi.lua](https://github.com/monome/norns/blob/master/lua/wifi.lua) so I don't think there is any other way to debug this without a serial console.

norns version stuff

```
we@norns:~ $ head changelog.txt 
# 181008

## norns 1.1.0

- BREAKING parameter ids. args to `params:add_number()` (etc) changed
- NEW OSC mapped parameters @artfwo
- ADD updated docs @pq
- FIX fileselect unit (affects mlr,etc)

## dust
```

**Comment by Dewb** [comment]
I'm having the same issue -- hotspot mode works (sort of, my phone can connect to the norns network, but my laptop cannot for some reason) but every attempt to join a wifi network fails.

**Comment by lazzarello** [comment]
##Update

The opposite happens at random intervals too. The status reads "failed" but the network interface has a connection. Contents of *.wifi

```
we@norns:~ $ cat status.wifi 
failed
we@norns:~ $ cat ssid.wifi 
#youareawesome2-2.4Ghz
we@norns:~ $ md5sum psk.wifi configs.bak/psk.wifi 
85b5095e6cc5dcdbc0c5be5c3e575339  psk.wifi
85b5095e6cc5dcdbc0c5be5c3e575339  configs.bak/psk.wifi
we@norns:~ $ ip addr show wlan0
2: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:13:ef:f2:12:36 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.106/24 brd 192.168.0.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::213:efff:fef2:1236/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by tehn** [comment]
duplicate #521
