### ISSUE TITLE
Missing note off messages using Arturia KeyStep

### ISSUE THREAD

**Issue by markwheeler** [monome/norns#609]
Having trouble getting the Arturia KeyStep working correctly with norns.
The midi event frequently doesn't seem to get called for note offs. It happens consistently and even at very low tempos (1/4 notes) causing lots of hung notes.

I'm not having the same problem with an Akai MPK Mini or when sending notes from Ableton Live via an iConnectivity mio. It all points towards the KeyStep being the issue... but it works perfectly when connected to my Mac.

Any ideas how to debug further? Could there be something different about the way the KeyStep sends its data?

**Comment by tehn** [comment]
added to line 108:
```
fprintf(stderr,"midi %d %d %d\r\n", msg_buf[0], msg_buf[1], msg_buf[2]);
```

weird repeat data coming in:

```
midi 145 60 30
midi 145 60 30
midi 145 60 30
midi 129 60 64
midi 129 60 64
midi 129 60 64
midi 129 60 64
midi 129 60 64
midi 145 48 36
midi 145 48 36
midi 145 48 36
midi 129 48 64
midi 129 48 64
midi 129 48 64
midi 129 48 64
midi 129 48 64
midi 145 60 30
midi 145 60 30
midi 145 60 30
midi 129 60 64
midi 129 60 64
midi 129 60 64
midi 129 60 64
```

this seems to only happen when the arpeggiator is on. normal note-pressing just sends one note.

and somehow, despite the repeat sends, only one note event is generated?

it's a start...

**Comment by malacalypse** [comment]
See https://github.com/raspberrypi/linux/issues/2687 for some details - I'm having the same exact issues with my Keystep. I was able to mitigate the problem under certain circumstances but a real fix is not yet available.

**Comment by malacalypse** [comment]
I don't have a Norns but on my Pi I have a hardware MIDI input, and for my Keystep I'm just using that hardware input port and powering the keystep via USB only. That seems to solve the problem. Not sure if the Norns has a hardware MIDI port but that might be a workaround if it's available to you. I have no idea why Arturia cheaped out so hard on the USB MIDI implementation - devices that cost far less than the Keystep implement it just fine.

**Comment by tehn** [comment]
@malacalypse thank you for the tip! much appreciated.

**Comment by tehn** [comment]
nice that they wrote you back. has arturia ever offered firmware updates for any of their controllers? (just curious). keystep is one of the nicer cheap controllers, so it'd be great if we had it working correctly some day.

**Comment by markwheeler** [comment]
Yes I'm surprised it's an issue, seems like a nice match.
It looks like they did release a few bug-fix updates for the KeyStep but nothing new since 2016.

**Comment by malacalypse** [comment]
Yes, they updated their Beatstep Pro quite heavily in the first few years, adding a ton of features. Nothing much for the KeyStep though, as @markwheeler mentions. It is disappointing that they don't have a more robust USB implementation. And, unless I'm wrong, there isn't another 37 key controller that's got playable keys with aftertouch that is so compact, so not only is it a nicer cheap controller, it's the only option at any price if you need more than two octaves and still ultraportable. I tried setting the USB speed to 1 with `dwc_otg.speed=1` as @tehn mentioned (as part of the debugging process with the Pi team) but it didn't do anything for me. `nak_holdoff=1` did help quite a bit, but didn't solve the problem entirely. There are reports that the 4.19 kernel that's out now has some improvements but I haven't tried it yet. And there are also reports that the pre-4.14 kernels (4.09?) were fine too.

**Comment by jonnybutler** [comment]
Arturia released a new firmware for the Keystep today, so maybe someone can test it out and see if it fixes these issues.  Doesn't mention any bugs, but worth a shot?  Personally don't have one but have held off since reading through this issue.

**Comment by tehn** [comment]
thanks for the heads up. do we have a script that can reproducibly fail?

**Comment by markwheeler** [comment]
This was always an issue with Molly the Poly in the past, I can test it out again in the next few days. There are some bug fixes listed on the Arturia site although they are fairly vague.

**Comment by markwheeler** [comment]
I just did the Keystep update and spent 10mins testing - and didn't get the problem at all! Obviously I'd want to live with it a bit longer before declaring this 100% fixed but it seems hopeful :)
