### ISSUE TITLE
MIDI event called with empty data table

### ISSUE THREAD

**Issue by markwheeler** [monome/norns#610]
When sending clock to norns, the MIDI event is often called with an empty `data` table.
This sometimes happens every tick (seems related to stopping/starting the external clock source) and sometimes happens when stop messages are sent. I mainly tested sending clock from Ableton Live via iConnectivity mio.

It's easy to ignore the empty tables but seems odd.

**Comment by okyeron** [comment]
just posted this PR which I think will help with your issue
https://github.com/monome/norns/pull/658

**Comment by markwheeler** [comment]
great yes that fixes it!
