### ISSUE TITLE
Scripts without engines cannot use polls until a script with an engine has been run

### ISSUE THREAD

**Issue by markwheeler** [monome/norns#615]
If a script wants to poll one of the norns system polls (eg, `pitch_in_l`) but doesn't use an audio engine (engine.name is not specified) and it's the first script run after startup, it will fail at init.
However, if another script which has an audio engine is run previously, the above described will work as expected.

Niche use case I know but I did run into it :D

**Comment by catfact** [comment]
it's silly and the reasons are convoluted, but i think it's most straightforward to just load a fallback engine.

this could be an engine that does nothing, or has some generic useful functions like additional analysis or something.

**Comment by markwheeler** [comment]
Cool will close this one, thanks for the quick response!

**Comment by catfact** [comment]
eh, i think this is definitely a problem that needs addressing in some way: we don't say you can't have a script with no engine (we may even encourage it somewhere?) but if you do that it breaks things in an unexpected way by destroying the analysis polls.

the simplest solution right now is to have an empty engine that `script.lua` uses as a fallback.

the next, better solution i think is to not rely on SC for these anlaysis polls at all. the amp poll is simple, the pitch poll would be part of a somewhat larger effort to add freq-domain analysis/processing to `crone`.
(best implementation i'm aware of right now, using SNAC: http://www.katjaas.nl/helmholtz/helmholtz.html)

**Comment by tehn** [comment]
fixed by https://github.com/monome/norns/pull/809
