### ISSUE TITLE
improve sample/file loading

### ISSUE THREAD

**Issue by Gittifer** [monome/norns#622]
For all of the sample-based scripts, it would be nice to load things up a little faster. Maybe on init, the number of empty file-parameters could be counted, then the user could go through directories, "checking" or "unchecking" their selected files as they go. 

I would also like the ability to select whole directories (perhaps by holding a button, instead of a press) and create tables from them.

**Comment by catfact** [comment]
sorry, this is a bit too vague for the way we're using GH issues. best to hash out some concrete proposals on the llll [ideas thread](https://llllllll.co/t/norns-ideas/17625) or for a particular script.
