### ISSUE TITLE
Levels: Enc for 'in' has a different response when returning from a script

### ISSUE THREAD

**Issue by markwheeler** [monome/norns#624]
The encoders all feel correct when you first go to the levels screen.
Press key 1 to jump to script. Press it again to jump back to levels.
The 'in' encoder now has a different mapping to the others.

**Comment by tehn** [comment]
thanks for the heads up, and weird, because i thought i encountered this last month and fixed it! will find the issue

**Comment by markwheeler** [comment]
I'm not sure but I think maybe it was fixed when coming from another menu page but is still there when coming directly from a script.

**Comment by wirelesswine** [comment]
That is at Silverado resort correct?
