### ISSUE TITLE
"libmonome: error in write: Resource temporarily unavailable"

### ISSUE THREAD

**Issue by okyeron** [monome/norns#634]
I've run into this error a few times and I'm trying to track it down. However, it seems a bit over my head at the moment.

NOTE: This is on RasPi with my DIY teensy-grid. I'm not sure it's happening the same for stock norns and grids.

I can replicate this error running loom.lua and the cause seems to be the grid refresh rate (GRID_FRAMERATE variable in loom). If the grid is being refreshed at a rate of 27 fps or higher, the grid will basically lock up and then after about 25-30 seconds, maiden (or matron from the cmd-line) will start dumping an endless stream of "libmonome: error in write: Resource temporarily unavailable" errors.  At a framerate of 26, no errors.

Questions: 
* Where is this "libmonome: error in write" error being generated? I've combed through the matron and libmonome source, but can't find a similar error.

* to debug this, where could I start looking and/or adding some debug output/logging to see what might be happening?

**Comment by catfact** [comment]
i think it's coming from here:

https://github.com/monome/libmonome/blob/master/src/platform/posix.c#L163

and my guess is it indicates the teensy is taking too long to accept incoming bytes.

**Comment by okyeron** [comment]
OK - I've narrowed down this particular instance to a problem in my Teensy grid code where `0x12 /grid/led/all off` was getting triggered after every `0x1A /grid/led/map` message so there was twice the amount of LED traffic happening. (still no idea why that's happening as yet)

Should I close this issue, or leave it open for other instances of this error?

**Comment by tehn** [comment]
glad you found it. i'll close it until we see another issue.
