### ISSUE TITLE
Levels doesn't fully mute input

### ISSUE THREAD

**Issue by markwheeler** [monome/norns#635]
Feeding a loud (but at least in theory line level) signal into norns I hear it at the output even with all three levels turned all the way down (out/in/mon).

**Comment by catfact** [comment]
hm, things to check
- input/output synths in AudioContext getting their level args going all the way down to zero? (looking at the SC side, including aux bus)

- bleed still happen with no program running?

- any playthrough paths on the codec accessible by i2c?

**Comment by tehn** [comment]
would be curious in a peak-to-peak voltage reading of your input signal to assess the analog side. i've tested with pretty hot signals (ie, headphone out of a macbook) without issue.

use `alsamixer` with crone deactivated to gain full control of codec (there are no unexposed i2c functions)

**Comment by markwheeler** [comment]
I had a further look at this:
- Only noticed this so far with audio from a Serge modular (it has a line level out in theory but I suspect it may go higher given the below, might be something I just need to re-calibrate).
- I hear the leakage even after running `stop.sh`
- With only the left input connected, at reasonable input volumes everything is as expected (left channel only) but when the input gets high the leaking sound is on both channels of the headphone out.

Presumably this means that the input is just super-hot and leaking through the hardware somewhere.
I wasn't sure what I was looking for with `alsamixer` or where to measure voltage but I do have a cheap multimeter here if you can give me idiot-friendly instructions :)

Also happy to close this as just "unreasonable input"!

**Comment by tehn** [comment]
i can do a hardware evaluation and even swap you out a new circuit if something suspicious is going on.

basically if you see the input levels on the matron mixer peaking or overdriving, it's probably too hot :)

**Comment by markwheeler** [comment]
sorry for the noise, i'll stop feeding norns such high levels :)
