### ISSUE TITLE
tape: show time in file loader

### ISSUE THREAD

**Issue by tehn** [monome/norns#637]
helpful for identifying tapes given the file names tend to be obtuse

**Comment by w30n** [comment]
It would be useful to be able to pre-listen audio files before loading (for tape and samples in scripts)

**Comment by catfact** [comment]
> It would be useful to be able to pre-listen audio files before loading (for tape and samples in scripts)

useful sure, but really different scope. (need to add specific functionality in `crone`, effectively a second `Tape` instance / bus / mix point.)

this issue is just about a tweak to the lua layer and menu.

**Comment by tehn** [comment]
this would be a feature-add to fileselect.lua

**Comment by tehn** [comment]
fixed by #975
