### ISSUE TITLE
midi note-on, velocity zero not handled as note-off

### ISSUE THREAD

**Issue by okyeron** [monome/norns#646]
while checking out midi with molly_the_poly script tonight I found I'm not getting note off messages while using a QuNexus.

Looking at midi.lua, it appears it does not account for some instruments that do not send a note-off byte, but rather a note-on byte with velocity 0 instead.

For example if I do
```
m = midi.connect(2)
m.event = function(data)
  local d = midi.to_msg(data)
  
  local status = data[1]
  local data1 = data[2]
  local data2 = data[3]
  print(status .. " " .. data1 .. " ".. data2)
  tab.print(d)
end
```
returns
```
144 59 105
vel	105
type	note_on
note	59
ch	1
144 59 0
vel	0
type	note_on
note	59
ch	1
```

so perhaps this needs to be changed in midi.lua?

```
   -- note on
  if data[1] & 0xf0 == 0x90 then
    if data[3] > 0 then
    --print("note")
    msg = {
      type = "note_on",
      note = data[2],
      vel = data[3],
      ch = data[1] - 0x90 + 1
    }
    elseif data[3] == 0 then
    --print("noteoff")
    msg = {
      type = "note_off",
      note = data[2],
      vel = data[3],
      ch = data[1] - 0x80 + 1
    }
    end
```

Should I submit this as a pull request?

Or... are there cases where a note-on, velocity zero should not be considered a note-off?

**Comment by tehn** [comment]
yes that sounds good. send a PR
