### ISSUE TITLE
USB Sync w/ multiple devices

### ISSUE THREAD

**Issue by okyeron** [monome/norns#654]
From menu.lua SYNC section...
```
m.sync.disk = util.os_capture("lsblk -o mountpoint | grep media")
``` 
with multiple USB devices attached `lsblk -o mountpoint | grep media` will return 
```
/media/usb0
/media/usb1
```
Does `util.os_capture` deal with that or does this create a funky m.sync.disk path?

Doing a quick test it appears `sync to usb` data will go to usb1 in this situation.

For future enhancement, checking for multiple drives and selecting the one you want would be excellent features.

**Comment by tehn** [comment]
thanks for the suggestion, you're correct.

but i'm dropping the SYNC feature entirely, as it's not an effective file management strategy. rather i'll be encouraging people to use SFTP (cyberduck/etc)
