### ISSUE TITLE
make metro stage settable

### ISSUE THREAD

**Issue by catfact** [monome/norns#655]
(after rambling about it here https://github.com/monome/norns/issues/653)

`metro.lua` objects have a `stage` property that is automatically updated on each wakeup, and given as an argument to the lua callback. it's not user-settable.

in a nutshell, the reason is that allowing it to be user-settable leads to race conditions. 

currently, stage number is protected by mutex and it seems like a bad idea to let lua thread hold the lock at any time (not just on init/start.)

one idea might be to make stage atomic (`sig_atomic_t`?) and read it directly at the lua callback, instead of writing it in the scripting event data.

(NB that this can easily be worked around by keeping explicit sequence state in lua.)

**Comment by tehn** [comment]
i _really_ think this is going to far. the explanations on #653 are valid, the metro API is good.

if complicated behaviors are needed ie resets or different step sizes, just do that in the lua userspace.

my vote is to close this.

**Comment by artfwo** [comment]
+1 for closing this.
