### ISSUE TITLE
missing battery globals cause errors

### ISSUE THREAD

**Issue by okyeron** [monome/norns#668]
*Issue only on RasPi*

if not initialized, `norns.battery_percent` and `norns.battery_current` will throw errors on the main menu and cause the HOME menu to become unaccessible if the stats are accessed.

Quick fix for this would be to set those to zero in [battery.c](https://github.com/monome/norns/blob/1d1b4a669a04c3a79f0748034b47d8418b1e16e1/matron/src/hardware/battery.c#L42)

Adding this code after `fprintf(stderr, "BATTERY: FAIL.\n");` solves the issue
```
		union event_data *ev = event_data_new(EVENT_BATTERY);
		ev->battery.percent = 0;
		ev->battery.current = 0;
		event_post(ev);
```

Alternately you can comment those variables out in menu.lua but it throws off the formatting on the stats screen a bit.

Would this be a reasonable PR for the main code branch, or something I should just keep for my own install?

**Comment by artfwo** [comment]
@okyeron that also has to cover the case when battery_init fails to create a thread. have you considered initializing these variables in norns.lua instead?

**Comment by tehn** [comment]
agreed. initializing them in lua would be a more appropriate fix.

**Comment by okyeron** [comment]
Understood. 

So in `battery percent handler` in `norns.lua` I could check to those variables for nil and set to zero - which might look like this:

```
--- battery percent handler
-- @param percent battery full percentage
norns.battery = function(percent, current)
  norns.battery_percent = tonumber(percent)
  norns.battery_current = tonumber(current)
  if (norns.battery_percent == nil) then norns.battery_percent = 0 end
  if (norns.battery_current == nil) then norns.battery_current = 0 end
  --print("battery: "..norns.battery_percent.."% "..norns.battery_current.."mA")
end
```
It's possible for tonumber() to return nil, so checking the value after seems appropriate?

**Comment by artfwo** [comment]
This will only set the variables to nil on first event received. Just set them to nil outside of the function.

**Comment by okyeron** [comment]
Perhaps setting `norns.battery_percent = "n/a"` or `norns.battery_percent = "-"` (or similar)?  This seems a bit less prone to errors vs. passing a nil value through to the menu

**Comment by artfwo** [comment]
Passing these values to menu doesn't signal about any errors. I like nil because it breaks an unhandled special case that should break (and should be handled as special case). And it only requires simple value check in display code (where stuff like error indication belongs).

**Comment by okyeron** [comment]
okie dokie... then that circles me back around to menu

```
    if (norns.battery_percent ~= nil) then 
      screen.text("BAT " .. norns.battery_percent)
    end 
    screen.move(36,10)
    if (norns.battery_current ~= nil) then 
      screen.text(norns.battery_current .. "mA")
    end
```

**Comment by artfwo** [comment]
Yeah, or
```
if norns.battery_percent and norns.battery_current then
    screen.move(0,10)
    screen.text("BAT " .. norns.battery_percent)
    screen.move(36,10)
    screen.text(norns.battery_current .. "mA")
end
```

**Comment by tehn** [comment]
fixed by https://github.com/monome/norns/pull/676/commits/402a455037c4870fc07a03705c2aa744a4cfe216
