### ISSUE TITLE
Add LuaSocket to norns

### ISSUE THREAD

**Issue by markwheeler** [monome/norns#686]
Would it be possible to add the LuaSocket lib to norns? Or a similar lib that allows network access from scripts.
http://w3.impa.br/~diego/software/luasocket/home.html

I had a quick look at installing this but wasn't sure how to go about doing so - happy to make a PR if someone can point me in the right direction.

**Comment by catfact** [comment]
some of the caveats/reservations on #479 apply especially strongly to anything involving sockets or filesystem access. namely, dont do stuff that will block from a script in realtime (in an event handler.) rethinking the event queue would help make this a little more forgiving (#461)

**Comment by markwheeler** [comment]
Just to note: It's fairly easy to use `util.os_capture()` and `curl` instead for anyone else landing here and looking for network access from scripts.

**Comment by tehn** [comment]
still worth revisiting possible inclusion of luarocks, if there are any further opinions.
