### ISSUE TITLE
tape play/rec CPU usage too high

### ISSUE THREAD

**Issue by tehn** [monome/norns#697]
on new-crone. noticed the CPU spike as clicks get into the playback and recording.

i wasn't seeing this before and so far i'm not sure what changed.

with `htop` open (for easy sub-process visibility) the cpu spike can be seen right after executing:

```
audio.tape_play_open("/home/we/dust/audio/tape/0003.aiff")
audio.tape_play_start()
```

@catfact are you able to replicate this?

**Comment by catfact** [comment]
> i wasn't seeing this before and so far i'm not sure what changed.

before what?

**Comment by catfact** [comment]
i don't see a spike but i do see a lot of CPU usage for playback, more than there should be. enough to push one core near 90% 

if you are really seeing a "spike" at the beginning then maybe the actual file preparation is blocking a long time on your system. i haven't seen this yet but will try some more

first step for CPU usage might be to address these FIXMEs in Tape.h
https://github.com/monome/norns/blob/dev/crone/src/Tape.h#L104
https://github.com/monome/norns/blob/dev/crone/src/Tape.h#L312

re: click
unlike the SC implementation, this doesn't have an amplitude envelope. should add one for playback at least. 

are you hearing something more than the hard on/off switch? (i will try listening to file with soft onset)
