### ISSUE TITLE
create a "programming reference" doc

### ISSUE THREAD

**Issue by pq** [monome/norns#717]
from @tehn:

> i’d like to consider condensing/creating a single doc that’s a bit more readable, perhaps something like the TT manual. (we might enlist some of the talent who worked on that?) i’m imagining something that is a reference, but also with the progression of a distilled norns study: so it starts with script basics outline (ie, init function, engine selection) and then shows encoders/keys/screen, then params, metro, external devices, etc. each section having a brief “what is this stuff” text, etc. function stubs are fine where sufficient. slightly more where needed (ie, metro.init())

**Comment by simonvanderveldt** [comment]
Initial documentation for this can be found here https://monome.org/docs/norns/script-reference/ sources here https://github.com/monome/docs/blob/master/docs/norns/script-reference.md

I also found this file in this repo https://github.com/monome/norns/blob/master/readme-script.md
Which I think has become irrelevant though there might be some parts we want to pull from it and add to the script reference documentation.

**Comment by tehn** [comment]
i think readme-script.md should be removed. there is a lot of outdated information.

script-reference is looking good, just `MIDI` and `HID` are TODO (MIDI can be basically surmised from one of the studies).

**Comment by neauoire** [comment]
We could use the [tutorial](https://llllllll.co/t/norns-tutorial/23241) for that.
