### ISSUE TITLE
create a "2.0 transition" doc

### ISSUE THREAD

**Issue by pq** [monome/norns#719]
from @tehn:

> i’ll need to additionally create a “2.0 transition” doc which outlines the major changes to workflow, programming syntax, and most importantly dust sharing. we’ll be creating a new category here on the forum for general patch/script/project sharing, but that’s a bigger issue that i can describe later.

**Comment by artfwo** [comment]
something to start with: https://github.com/monome/norns/wiki/syntax-2.0

**Comment by jasonw22** [comment]
What do folks think about the idea of a study that shows how to migrate your 1.0 script to 2.0? Needed? Overkill?

**Comment by tehn** [comment]
i like the idea of a study, but think would prefer to have it a lesser weight as to not intimidate users--- the "transition guide" will be a time-sensitive document--- most all users will have transitioned within a few months--- certainly those programming it actively.

perhaps the transition guide is just split into two sections:

- new
- changes

where the "changes" section is effectively a how-to (study) in addition to a bullet-list. i started on this in the syntax-2.0 doc
