### ISSUE TITLE
consider default .github community health files for the monome organization

### ISSUE THREAD

**Issue by pq** [monome/norns#724]
(this could as well be tracked on any monome repo; picking `norns` for its activity.)

anyway, see: https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization

it's now possible to setup org defaults and we might considering doing so for shared docs for:

* code of conduct
* pull requests
* issue templates
* ... ?

/fyi @tehn

**Comment by simonvanderveldt** [comment]
Unsollicated opinion following :P

I never really understood these things, when I'm interacting with a project as a user all these popups and templates are most of the time just an annoyance.

Keep it simple, if someone has an issue or wants to discuss something: file an issue, if someone has some suggested fixes or wants comments on changes: create a PR
That's it, done, no templates and other overhead needed :)

**Comment by pq** [comment]
that's why i qualified it w/ "consider" 😜 

seriously though, i appreciate your thoughts on templates.  i'm kind of on the fence about them.  in another one of my projects i added them (iirc because github nagged me to) and i'm not convinced they're worth it.

on the other hand, a code of conduct is generally a good thing so i'd probably pitch for one of those if nothing else.

**Comment by jasonw22** [comment]
Pretty long thread on the topic of a code of conduct. 
https://llllllll.co/t/code-of-conduct/9727 Seems to me we have one, and it's just not very prominently linked.

**Comment by okyeron** [comment]
No strong feelings here... but I don’t think this covers a thing I’d like to see - which is a “style guide” for docs (markdown conventions)

**Comment by pq** [comment]
re: a code of conduct,

> Seems to me we have one, and it's just not very prominently linked.

chatting with dan derks, my sense is that the code of coduct is almost there but the mods needed to finalize it and make it available.  once that happens it'd be great to integrate here.

/cc @tehn @trentgill

**Comment by tehn** [comment]
CoC for lines is one of those long-outstanding issues that simply requires me or josh (ioflow) to just push it through. there's already wide agreement amongst the mods.

but honestly the discussion on github is so laser-focussed it's difficult to imagine needing to link to the very-extensive lines CoC, but i'm fine with a mention of it.

the templates and guidelines/suggestions/howtos are much more useful and i'd be happy to review any suggested docs!

**Comment by pq** [comment]
sgtm!
