### ISSUE TITLE
Deleting wifi networks doesn't remove them from menu

### ISSUE THREAD

**Issue by simonvanderveldt** [monome/norns#745]
When deleting a wifi network via `system > wifi > del` the network/config is removed from the NetworkManager config but is still being shown in the menu.
A restart of matron does remove it from the list.

**Comment by okyeron** [comment]
Were you testing prior to this change?
https://github.com/monome/norns/pull/676/commits/0ddedbbcdb7631b3d28e83364062579075f77c58 

Just did a quick test and I'm getting the network removed OK

**Comment by simonvanderveldt** [comment]
Good question :P I'll not the commit next time and I'll give this a try on current `dev`.

**Comment by simonvanderveldt** [comment]
I am still getting the same behaviour on the 190314 beta update.

**Comment by tehn** [comment]
this is likely an error in the wifi menu code updating its network list. it has not yet been addressed.
