### ISSUE TITLE
re-examine main event system

### ISSUE THREAD

**Issue by tehn** [monome/norns#778]
- memory leaking
- event size? switch to object pool

**Comment by ranch-verdin** [comment]
Just finished long stress soak at 75% sgynth load, 53% matron load (best guess 1000 messages per sec).  0 xruns and no increase of memory usage over a 4.5 hour run at 64fpp/2ppb. The test exercises metros, front-panel controls, cairo, OSC send.  Several terminals open to norns over wifi during test (emacs session, top etc).

I think the remaining small 'leaks' detected by valgrind after last patch are things which are allocated only once and never freed, so only a problem in so much as they obfuscate valgrind results.

Anyone think an object pool will definitely give measurably better performance?  Personally wouldn't like to bet either way!

**Comment by catfact** [comment]
> Anyone think an object pool will definitely give measurably better performance? Personally wouldn't like to bet either way.

i'm willing to make only a very small bet, and the key word is "measurably." i just want to make the change b/c malloc in a realtime loop is decidedly gross.
