### ISSUE TITLE
implement async os commands

### ISSUE THREAD

**Issue by tehn** [monome/norns#779]
currently there are quite a few features that block. (wifi, file listings, etc).

UPDATE:

something like:

```
function callback_func(returned_txt)
  print(returned_txt)
end

util.cmd("ls ~", callback_func)
```

i can try this in c with a thread though i'm wondering how to parse the resulting txt as it may be long, ie not fit in an event data type. perhaps the txt gets sent line by line?

**Comment by tehn** [comment]
context: https://github.com/monome/norns/issues/779

**Comment by catfact** [comment]
i'm not sure what this issue is really about.

a coro is just a thing that can yield execution to it's calling context, then be resumed an arbitrary later time with it's old contents (stack contents.) by itself, i don't think they can actually perform concurrent execution.

for example, the clocks lib uses coroutine to create a seamless asynchronous syntax in lua , but requires the backing of system threads to actually resume the clock coros that have yielded.

**Comment by tehn** [comment]
you're right, this is poorly worded.

one thing that would make sense is to create an os call command which can be asynchronous... provide a command and a callback upon completion. this would pretty much solve the use cases where blocking is a real problem.

**Comment by tehn** [comment]
ahead of an attempt to solve this, considering some options...

1. should the os calls just be a queue? so that there's really only one user OS thread? otherwise it seems trickier to spawn threads for each call from lua, and track separate callback functions?

this however presents the issue of a time-consuming os process stalling out later calls, but i guess that's exactly what happens now with lua... but it could be more controlled in that it doesn't stall lua itself, so the behavior could be more predictable (and not stop metros (event processing) etc).

2. for the callback function, should the data sent back be line-by-line? along with perhaps with a command-finished flag? or should it wait til finished and throw a (potentially huge) chunk? lines would accommodate the event system better.

**Comment by catfact** [comment]
imho:

> should the os calls just be a queue? so that there's really only one user OS thread? 
yes. need OS worker thread with its own request queue. i'd suggest something like (pseudocode):

```
//---- [from LVM main thread]

// called from lua
function make_os_call_request: 
   allocate os_call_start_data:
       - string containing OS command, copied from lua stack
       - lua coroutine ID to resume when finished (cleaner than using callbacks directly) 
   push os_call_start_data pointer to work queue

// called from main event loop
function handle_os_call_response_event:
    copy os_call_response_data results string to lua stack
    free os_call_response_data (pointer in main-loop event struct)
    call low-level lua handler with coroutine ID

//----- [from worker thread]
function handle_os_call_request:
   free os_call_request_datta
   ... do blocking work...
   allocate os_call_response_data:
      - results string (copy from child process stdout)
      - coroutine id (from request data)
  push new event to main loop with os_call_response_data
```
in other words: responses  use the event queue with dynamic allocation. we already do this for other event types. with reasonable amounts of data it's fine. (not many megabytes or whatever)

> should it wait til finished and throw a (potentially huge) chunk? 

yes

**Comment by catfact** [comment]
i guess since it's a one-shot thing, coroutines don't actually give any benefits here over plain functions. 

so lua would be somethin like:

( in `OS` module or whatever)
```
local os = {}
os.callbacks = {}

function os.requestCall(cmd, cb)
   local id = os.getCallbackId()
   os.callbacks[id] = cb
   _os_request(cmd, id)

function os.handleResponse(results, id)
   local cb = os.callbacks[id]
   if cb ~= nil then cb(results)

-- helper; returns a fresh coroutine ID 
os.current_id = 0
function os.getCbId()
   -- i dunno...
   local id = os.current_id
   id = id + 1
   if id > 9999 then id = 1
   return id

return os
```

**Comment by tehn** [comment]
yes indeed this seems highly sensible. i'll re-acquaint myself with the event queue payload sizing...

**Comment by catfact** [comment]
me too...

ok. there are several event types which allocate extra memory and pass the pointer in the `event_data` struct. this is totally fine as long as it doesn't happen constantly. (well, it's as fine as using dynamic allocation for `event_data` in the first place, which isn't great, it should use an object pool.)

these pointers are freed from the main event loop after handling the event, from appropriate case here: 
https://github.com/monome/norns/blob/master/matron/src/events.c#L108
