### ISSUE TITLE
improve lua stack traces (pcall output)

### ISSUE THREAD

**Issue by tehn** [monome/norns#780]
perhaps we can produce better error messages?

**Comment by catfact** [comment]
is this about lua stack traces (output of `pcall`?) 

like, for example, getting name of table indexed by `nil`?

if so, i'd like to make the title more descriptive, add tags, that stuff

**Comment by pq** [comment]
> is this about lua stack traces (output of pcall?)

👍 

> like, for example, getting name of table indexed by nil?

i believe this is exactly right.

**Comment by catfact** [comment]
this will probably involve some magic in the lua eval module itself

perhaps around this salty FIXME
https://github.com/monome/norns/blob/dev/matron/src/lua_eval.c#L150

**Comment by tehn** [comment]
revisiting this, it was very dumb of me not to actually include an example of a bad error trace. so i'm not sure what this was originally trying to address. @pq any context you could add?

**Comment by tehn** [comment]
closing this as i don't have a good reference case.
