### ISSUE TITLE
wifi.state not set until visiting WIFI menu

### ISSUE THREAD

**Issue by okyeron** [monome/norns#788]
When viewing `menu.showstats` the IP shows up as `IP -` until you visit the wifi page once.

`wifi.state` appears not to be set on first run.

**Comment by okyeron** [comment]
@tehn 
In `startup.lua` I tried moving `wifi.init()` into the `norns.startup_status.ok` callback function and it seems to then properly init wifi on start (I get REPL output of the connections from the wifi.init function). This in turn properly sets `wifi.state` 

With `wifi.init()` as it currently stands in `startup.lua` , I don't see any of the wifi.init debug.

Not sure what the intended procedure is for wifi.init() on startup so I don't know if moving it around is good or bad.

**Comment by tehn** [comment]
startup_status_ok is dependent only on supercollider starting correctly, so it seems to be that wifi.init() just wants some sort of delay? i'll continue to investigate but would be interested if you find another approach

**Comment by okyeron** [comment]
FWIW - it looks like this ONLY happens on first launch at boot. doing `;restart` from REPL and wifi init's just fine.

So maybe that needs to be in a callback in the same way `norns.startup_status.ok` is for boot?

**Comment by okyeron** [comment]
BTW - Is this [duplication](https://github.com/monome/norns/blob/6cf7c55bd0962ecffe7760113041fa4bfd6d5112/lua/core/norns.lua#L145) of  `norns.startup_status.ok` (and `norns.startup_status.timeout`) OK? (since it's also [in startup.lua]

(https://github.com/monome/norns/blob/6cf7c55bd0962ecffe7760113041fa4bfd6d5112/lua/core/startup.lua#L41))

**Comment by okyeron** [comment]
Revisiting this today.

Is there any reason not to move `wifi.init()` into the `norns.startup_status.ok` callback function?

That seems to fix this issue.

**Comment by tehn** [comment]
want to send a PR? happy to test

**Comment by tehn** [comment]
fix by 861
