### ISSUE TITLE
engine list report not getting called

### ISSUE THREAD

**Issue by tehn** [monome/norns#798]
noticed that `engine.names` is empty

https://github.com/monome/norns/blob/dev/matron/src/weaver.c#L1625

calling `report_engines()` bonks

---

was attempting to do a check on `engine.name` for scripts against available engines to warn the user if the engine is missing instead of just failing poorly

**Comment by catfact** [comment]
@tehn interesting... i didn't have this problem with `we` at commit `a7c1943b5c1e1316f8dbedeffce93b8564fe7f50` (april 1) and `norns` at current master.

then i pulled `we/master` just now (april 8) and got the crash/hang in matron apparently. breaking out the debugger...

**Comment by tehn** [comment]
good chance i broke something when touching (theoretically cleaning up) a lot of weaver bits while i was implementing softcut glue. i can take a look later tonight.

**Comment by tehn** [comment]
fixed by #808
