### ISSUE TITLE
ansible stops responding when grid switched to it after using norns mlr

### ISSUE THREAD

**Issue by audionerd** [monome/norns#804]
steps to reproduce:
1) run a kria pattern on ansible 1.6.1, externally clocked, connected to a grid
2) disconnect the grid from ansible, connect the grid to norns running mlr, but:
3) don't press any grid keys on mlr
4) disconnect from norns and re-connect to ansible
5) ansible will not respond to grid input, and sometimes will halt playback

if you do press a grid key in step 3), reconnecting to ansible will work as expected.

side note: mlr does not immediately update the grid ui when a grid reconnects, but i believe that is a separate issue. i tried modifying mlr to update the grid every 30 msecs, causing the grid leds to "wake" after connect, but unless i press a grid key, ansible is still unresponsive when switching back.

other scripts, like awake, do not have this problem! i've noticed the problem when norns has just started, and mlr is the first script run before the grid has connected.

i am on norns 2.0 using an older disk image from last month. ansible 1.6.1 from the github release.

**Comment by audionerd** [comment]
i noticed an odd entry in norns device list for grid: two grids show up, both with the same id but one has a garbled name. i tried clearing both and restarting norns.

using the isms switch i tried the above steps again, but see the same issue. however, now the device list shows only two entries: 1. monome 128 m---  and 2. is blank. no 3 or 4. and viewing the device list causes norns to freeze, i have to reset with the little button on the back of norns.

**Comment by tehn** [comment]
it sounds like there is a libmonome error on norns regarding reinitialization. 

I would suggest not using switch with norns for the moment. thank you for the report.
