### ISSUE TITLE
softcut reset

### ISSUE THREAD

**Issue by tehn** [monome/norns#812]
https://github.com/monome/norns/blob/master/lua/core/softcut.lua#L153

this needs _way_ more default settings (ie filter)

this function gets called when scripts are loaded.

**Comment by simonvanderveldt** [comment]
Is there no `reset` message or something along those lines to reset softcut?

**Comment by catfact** [comment]
there is - it's linked above - it simply needs to touch quite a few more parameters.

**Comment by simonvanderveldt** [comment]
@catfact Ohw, OK. I expected there to be something on the non-lua side, that would then get called from the lua side.

**Comment by tehn** [comment]
need to implement a single OSC message to reset crone to softcut defaults, as currently it requires a _massive_ amount of packets.

**Comment by catfact** [comment]
i'll do it

**Comment by catfact** [comment]
one wrinkle about this is that it's probably a good idea to still have a lua `reset` that returns a state object reflecting the default state of the underlying audio process

**Comment by tehn** [comment]
i figure this should only be really used for script clear/startup so wondering how important it is?

**Comment by catfact** [comment]
i won't sweat it, but it seems wise to at least document stuff like what voices are assigned to what buffers, instead of just magic stuff in the .cpp

**Comment by catfact** [comment]
actually i'll just add it to the lua since it is totally trivial anyway

**Comment by tehn** [comment]
fixed by https://github.com/monome/norns/pull/856
