### ISSUE TITLE
menu file SELECT bogs lua timing

### ISSUE THREAD

**Issue by tehn** [monome/norns#815]
the script list folder recursion is too heavy for lua to maintain timing of metros/etc, so it's likely that metros will get stalled and a running script will stutter. (ie awake)

more pronounced with more scripts in the folder.

coroutines is one solution.

**Comment by okyeron** [comment]
There may also be other/faster ways to get/parse the directory structure without recursively hammering `scandir`/`popen`

I looked at this briefly awhile back and will revisit

**Comment by audionerd** [comment]
In [build_select_tree ](https://github.com/monome/norns/blob/954f26da8a0362b5d657df31de26820526fc3bfc/lua/core/menu.lua#L324), how about a single `popen` to `find . -type f -name "*.lua"` and then filter that list?

**Comment by tehn** [comment]
that would certainly accelerate the process if you want to give it a try. i won't be able to get to this for a bit.

**Comment by audionerd** [comment]
i gave it a try:

https://github.com/audionerd/norns/commit/faa4b1c8da04f03f2cd6ac9aded244e0626fcd00#diff-43ab06b2651c491ba3ef9004fa809bd1

but i still notice a lag in metros & dropped MIDI clock messages on SELECT :/

**Comment by tehn** [comment]
likely needs https://github.com/monome/norns/issues/779

**Comment by catfact** [comment]
i'm trying to see how a coroutine could help this. i will make some relevant comments on 779.

the only actual solution i see is to create an asynchronous wrapper for these blocking OS calls, in C, backed by pthreads. coroutines could rovide some convenient syntax on the lua side.

**Comment by catfact** [comment]
i'd actually recommend closing this and making #779 more specific ("implement asynchronous system calls")

**Comment by tehn** [comment]
agreed!
