### ISSUE TITLE
softcut.pan() is reversed

### ISSUE THREAD

**Issue by darwingrosse** [monome/norns#817]
Working with softcut.pan() has the locations reversed from expected values. I'm guessing 0.0 is left, 1.0 is right - but reality is opposite. As an example, change the pan line in ash/orbit to:

    softcut.pan(i, i - 1)

You will see that the channels are reversed from expected. Probably missed because most examples center the softcut voices.

**Comment by catfact** [comment]
i don't know why it seems normal to me to have 0=R, 1=L!

i would change that here:
https://github.com/monome/norns/blob/master/crone/src/Bus.h#L199

**Comment by catfact** [comment]
Forgot about this, sorry
https://github.com/monome/norns/pull/818
