### ISSUE TITLE
TAPE: aiff files at 44.1khz play back at a faster rate

### ISSUE THREAD

**Issue by audionerd** [monome/norns#823]
44.1khz aiff files play back at a faster rate in TAPE

48khz play back correctly

norns 2.0.1

using an older norns-image (190314) not sure if that makes a difference

**Comment by catfact** [comment]
It’s true, crone tape performs no resampling

**Comment by audionerd** [comment]
Makes sense. 

What if I added a section to the [TAPE docs](https://github.com/monome/docs/blob/master/docs/norns/index.md) re: which files work for playback?

Something like:

> PLAY can load 48khz / 24bit WAV files.

Is there a list of file formats that will work with PLAY out of the box?

**Comment by catfact** [comment]
files must be stereo. any header / sample format should work (including raw.) 48khz is assumed.

**Comment by audionerd** [comment]
Any exceptions re: FLAC, MP3, M4A?

**Comment by catfact** [comment]
sorry yes, i should have said:
ah good point yeah. no formats requiring a license (mp3, AAC, etc)

flac/ogg should work.

we are just using libsndfile. here is the full table of supported encodings / sample formats:

http://www.mega-nerd.com/libsndfile/


we have not specifically tested every entry in this table, just the basics. (wav, aif, 16b, 24b, float.)

**Comment by audionerd** [comment]
Closing now that this is in the docs.
