### ISSUE TITLE
On device debug mode?

### ISSUE THREAD

**Issue by okyeron** [monome/norns#824]
In regards to duplicate engine errors (or similar SC problems)...

Is is possible to pipe SC errors to be displayed on the device screen? 

Perhaps a "debug mode" that could be toggled on/off - Especially for situations where you don't have a computer and maiden handy?

**Comment by catfact** [comment]
in general, you need to be on a computer to fix SC errors anyway, and the output is verbose...

but the 'duplicate class' errors problem is common enough that it should be caught and handled...

(even in lua possible to catch most duplicate-class issues by checking for duplicate filenames? after update maybe?)

**Comment by okyeron** [comment]
>even in lua possible to catch most duplicate-class issues by checking for duplicate filenames?

Seems like it could be easy enough to add checking for duplicate engines at startup (`startup.lua` or `engine.lua`?)

**Comment by tehn** [comment]
SC gets in a failure state with duplicate engines and becomes non-communicative.

we can, however, check if the user is trying to load something that doesn't exist.

also, generally it's difficult to get your norns into a fail state without a computer as the thing that creates the fail state.
