### ISSUE TITLE
display_png crashes display with bad file path

### ISSUE THREAD

**Issue by okyeron** [monome/norns#825]
Using `display_png` with a path to a non-existent file looks like it crashes the display in some fashion (screen goes black, no other script will show anything) .

`;restart` brings things back to normal.

Suggestions on debug?

**Comment by okyeron** [comment]
So here's a possible solution.
[screen.c #L139](https://github.com/monome/norns/blob/7d61c27ded0a6e22db3bcb8ad3fff2f0e6e035d7/matron/src/hardware/screen.c#L139)
instead of checking `image == NULL`, we look at the status instead

```
        image = cairo_image_surface_create_from_png (filename);
	//if(image == NULL) { return; }
	if (cairo_surface_status (image)) { 
		fprintf(stderr, "display_png: %s\n", cairo_status_to_string (cairo_surface_status(image))); 
		cairo_surface_destroy (image);
		return; 
	}
```

FWIW - it appears the surface created will still be a valid pointer, but it will return a pointer to a "nil" surface for an error like file not found. I don't understand if that "nil" pointer actually == NULL though.

Also - What I'm not sure about - does the surface need to be destroyed before `return;`? (Or the filename pointer free'd?)

**Comment by tehn** [comment]
@okyeron did your solution work? please PR if so!

**Comment by okyeron** [comment]
I'll need to revisit this and refresh my memory. Will see if I can get a PR together shortly.

Again - was looking for feedback here about: " does the surface need to be destroyed before return;? (Or the filename pointer free'd?)"

**Comment by tehn** [comment]
not sure if the image needs to be destroyed. perhaps try a sizeof and see if memory was allocated?

**Comment by okyeron** [comment]
if file not found, `cairo_surface_get_reference_count ()` returned zero, so I *think* that means there's no image to be destroyed. 

PR sent. Fix prints an error on file not found, does not crash.
