### ISSUE TITLE
Script fails to load engine, loads previous successfully loaded engine as a fallback

### ISSUE THREAD

**Issue by lazzarello** [monome/norns#828]
From a [thread on Lines](https://llllllll.co/t/norns-development/14073/319?u=lazzarello) I found a strange one. It feels like there's some kind of default engine loading precedence defined somewhere. Summary from that thread

> This is reproducible by loading the FM7 library, followed by [loading this commit](https://github.com/lazzarello/gemini/commit/b434ff2750308359a43da9a3189e93d36e6ce404) from the Gemini library, which will throw an exception when an Arc is connected. The third step is to apply [my diff to fix the initial exception](https://github.com/lazzarello/gemini/commit/483a3ceaeb7646f3baaf0ff1e81ce94a3d0bd360) via Maiden, save and load the script. This will cause SuperCollider to throw an exception expressing a missing engine from Gemini. This is followed by something (perhaps this is the root cause?) loading *the last successful engine* into this script, exposing all parameters and polls then initializing the "failed" script a second time. Rebooting the device "fixed" this bug.

**Comment by catfact** [comment]
fwiw, i think this is a problem on the lua side, with `engine.name` being a persistent global field. supercollider retains no memory of previous engine-load attempts.

**Comment by catfact** [comment]
AFAICT, this was fixed by PR #950.

requesting a missing engine now throws a script error and an informative message on the screen ("error: missing foobar".) `init()` won't be called, so there are no other side effects.
