### ISSUE TITLE
TAPE record mode breaks norns encoder callback

### ISSUE THREAD

**Issue by lazzarello** [monome/norns#831]
Initial bug was posted in [the norns development thread on lines](https://llllllll.co/t/norns-development/14073/325?u=lazzarello). The FM7 script [defines a callback for the norns encoders]. When the script is loaded, the encoder callback works as expected, in this instance modifying a floating point number for an engine parameter. When I begin recording with TAPE, the encoder callback breaks and Lua throws the following exception.

```
stack traceback:
/home/we/norns/lua/core/encoders.lua:57: in function 'core/encoders.process'
lua: /home/we/norns/lua/core/encoders.lua:57: attempt to call a number value (field 'callback')
```

From the output, it seems that the callback field in the encoders module no longer contains a function after enabling recording, rather it contains a number. I'd imagine getting some kind of debugging environment to inspect the table before and after starting to record could be helpful. Not sure how to do that outside of the REPL.

**Comment by tehn** [comment]
failed to replicate.

could you pull master, recompile, and see if you can replicate this?
