### ISSUE TITLE
mix params workflow

### ISSUE THREAD

**Issue by tehn** [monome/norns#838]
right now the way to update audio levels is to call ie

```
audio.level_cut(x)
```

but the menu level page uses the `mix` class which is a paramset. clearly updating `audio.level_cut` directly is not going to update the `mix` pset.

---

solution might be to have the `audio.level_cut` do a set on the mix pset (not calling the action, that is, avoiding a loop)

**Comment by markwheeler** [comment]
could the params just be available everywhere and scripts call `mix_params:set("level_cut", x)` ?

**Comment by tehn** [comment]
this will be addressed in the menu system rework, where all the SYSTEM > AUDIO bits will be rolled into the params screen/system... and likely a breaking change
