### ISSUE TITLE
add keyboard support to menu

### ISSUE THREAD

**Issue by tehn** [monome/norns#840]
when a USB keyboard is connected, MENU mode could use this as an interface.

ie. up/down, left/right, enter/escape.

also wherever there is text entry.

possible hotkeys for screens, etc.

**Comment by tehn** [comment]
note that this would require a substantial rework of the menu system to stub out functions in a more sensible way for this sort of integration.

**Comment by dndrks** [comment]
bump! did a maiden overview session this morning and this came up -- keyboard entry even just for wifi passwords would be super helpful to smooth out the first touchy thing someone needs to do to get new scripts, etc.
