### ISSUE TITLE
crone/softcut: add / rename smoothing parameters.

### ISSUE THREAD

**Issue by catfact** [monome/norns#876]
in `crone` mixer client, smoothing is applied to routing levelsand pan (`MixerClient::smoothLevels` structure.) but there are no parameters to change the smoothing time constant. a couple people have asked about adding these. 

similarly, there is smoothing on output level and pan for each softcut voice, also with fixed timing. more confusingly, there is a `levelSlew` parameter which only controls recoruld/erase levels. 

it's easy to add these parameters. 
is it a good idea? 
should we rename existing softcut slew params? 
should a single param control all mixer slew times?
&c

**Comment by lpgitadmin** [comment]
Slew on output level and on panning of a voice would be welcome from my point of view. 

Name wise softcut.rate_slew_time makes total sense while currently softcut.level_slew_time is confusing.

**Comment by tehn** [comment]
smoothed level/pan on softcut voices makes for some fun modulation and sound design... initial tests were easy and satisfying
