### ISSUE TITLE
commands used to determine duplicate SC scripts fail on buildroot image

### ISSUE THREAD

**Issue by simonvanderveldt** [monome/norns#937]
Follow-up from #866 

I ran into this whilst working on https://github.com/simonvanderveldt/norns-image/issues/30

The `find`, `uniq`, etc commands used to determine if there are duplicate SC files which were introduced in #866 fail on the buildroot image with
```
Dec 21 18:53:52 norns ws-wrapper[128]: norns.startup_status.timeout
Dec 21 18:53:52 norns ws-wrapper[128]: find: unrecognized: -printf
```
This is because the `find` offered by busybox doesn't support all the options of the full/normal `find` in this case it's missing support for `-printf`. We could of course add regular find and uniq, etc to the image, but I'd prefer to try to keep the image as small as possible.

Another solution could be to try to rely less (or not at all) on command-line tools and do either the whole find all `*.sc` files and check duplicates in Lua or still use find to get all the `*.sc` files and do the duplicate file check in Lua.
I don't think this causes problems with our design goals for norns and it would enable us to keep the smaller busybox provided command-line tools in the image to keep the image small.

I'll have a look if I can come up with a working patch/PR/proposal.

**Comment by simonvanderveldt** [comment]
My Lua knowledge is lacking and I got annoyed by the lack of basic functionality in Lua so for now I've worked around this by including coreutils and findutils in the buildroot image, see https://github.com/simonvanderveldt/norns-image/pull/31

**Comment by catfact** [comment]
:+1: , seems kinda good to have those anyway, no?

**Comment by simonvanderveldt** [comment]
@catfact they were all already there but in their simpler and (much) smaller busybox version :)

**Comment by simonvanderveldt** [comment]
I'm going to go ahead with using coreutils and findutils in the buildroot image for now, but I'd still like to fix this issue without relying on them since it means we'll need to maintain a non-standard busybox config for the buildroot image. I don't really want to maintain that busybox config though because it's quiet large.
Fixing this issue means we can go back to the out of the box busybox config.
