### ISSUE TITLE
crow.lua

### ISSUE THREAD

**Issue by mortenwagner** [monome/norns#939]
The "ii.ansible" part seems to have an error on line 197, where "trigger" is used instead of "pulse"

**Comment by mimetaur** [comment]
This is tripping me up as well:
`crow.ii.ansible.trigger_pulse = function(channel) crow.send("ii.ansible.trigger_toggle("..channel..")") end`

Experimenting in druid with crow directly, `ii.ansible.trigger_pulse(channel)` is definitely the function crow should be calling.

**Comment by tehn** [comment]
whoa, thanks for bumping this. will get it fixed right away.

**Comment by mimetaur** [comment]
Just made a pull request so all it needs is a review and we'll be good to go.
