### ISSUE TITLE
crone libatomic linkage on RasPi w/ Buster

### ISSUE THREAD

**Issue by okyeron** [monome/norns#947]
Back when the pi4 came out I ran into an error while trying to build crone

```
[45/45] Linking build/crone/crone
/usr/bin/ld: crone/src/softcut/SoftCutVoice.cpp.1.o: in function `softcut::SoftCutVoice::getQuantPhase()':
SoftCutVoice.cpp:(.text+0x670): undefined reference to `__atomic_load_8'
```
This appeared to be something to do with a newer version of gcc on debian requiring explicit linkage (Buster kernel has gcc version 8.3.0)?

at the time @catfact  helped me out and I added `atomic` to the `lib` array in the `crone/wscript` and everything would compile just fine.

However, with norns updates, my replacement of the `crone/wscript` will get broken and recompile can error.

So - how best to account for this going forward?

Can the `norns/wscript` waf configure be modified to check for `libatomic`?

would that be adding something like 
`conf.check_cfg(package='atomic', args=['--cflags', '--libs'])` to the configure def?

Or just explicitly adding `lib=['atomic']` to `crone/wscript` as I did for my build? (would that cause any errors for the regular hardware norns build recompiling on device?)

**Comment by simonvanderveldt** [comment]
It's strange, I can't find anything about changes in GCC linking behavior regarding libatomic, I'd expect an entry in a changelog or an announcement about this but nothing.
I did see some notes about this being architecture dependent, so not relevant on AMD64 but relevant on (certain?) ARM architectures, could that be?

**Comment by catfact** [comment]
if i understand correctly this is really an issue with the stdlib version, and it shouldn't hurt to link `libatomic` explicitly regardless. but will check this assumption

**Comment by okyeron** [comment]
I understand this has low or zero priority, but any chance to revisit this? (this would eliminate one patch I need to make on fates so people can recompile norns with `./waf` - otherwise this errors)

I tested just now with shield and adding `atomic` did not cause any error during compile and everything seems to work normally.

addition is on line 47 of `norns/crone/wscript`

```
                 lib=[
                     'jack',
                     'pthread',
                     'm',
                     'sndfile',
                     'atomic'
                 ],
```

**Comment by catfact** [comment]
sorry, just slipped my mind.

i'm sure it's fine, but i do want to test on factory norns, it is possible libc versions are different. can do this tonight

**Comment by simonvanderveldt** [comment]
We could use `--as-needed` (as suggested here https://gcc.gnu.org/ml/gcc-patches/2013-11/msg02605.html)?

Still not sure why it works on one version of Debian and not on the other :confused: 
@okyeron Just to check is the `libatomic1` package installed?

**Comment by tehn** [comment]
@okyeron please fork the norns repo and make your modifications there (along with the update url/etc). it is straightforward to sync upstream so you can continue to benefit from all of the work we put into the main repo.

we will eventually move to buster, but it's not a priority. or we may do something totally different--- buildroot, or something else.

it's disrespectful to use so much of our time solving problems raised by your clone project, particularly given that we released an open-source DIY option. if you wanted to solve this issue the appropriate action would be:

1. test it against official hardware and confirm it does not break functionality. enlist others (not core devs here) to also test.
2. submit a PR with a detailed description and any related issues.

this way everyone here can remain focused on our various tasks to improve the norns ecosystem, which will benefit everyone.

even so, it's not a given that just modifying the build files will solve the problem, but that i'll have to spend time creating a new update that manually delivers libatomic (or something similar).

i apologize that this seems like a large response to a small issue--- it's the result of an accumulation of the last many months of similar issues--- and the anticipation that these sorts of requests will continue each time we make a minor change to the system.

so please, fork the repo and go from there.
