### ISSUE TITLE
move "standard" engines into norns repo

### ISSUE THREAD

**Issue by tehn** [monome/norns#948]
- polysub
- polyperc
- simpletest

these are commonly used across several scripts and studies/tutorials, so it'd be good if they weren't subject to messy user management.

this would mean complicating the sc path perhaps

presently polysub and simpletest are in `we`, polyperc is in `tehn/awake`

**Comment by simonvanderveldt** [comment]
> this would mean complicating the sc path perhaps

What do you mean exactly by this?

We already have an SC engines directory in this repo (https://github.com/monome/norns/tree/master/sc/engines) which I'm installing to the (system) SC extensions directory (https://github.com/simonvanderveldt/norns-image/blob/master/package/norns/sc-wscript-install-sc-files-to-system-wide-sc-extension-dir.patch#L31).
Would something on the current Raspbian setup need changing if we move them to this `sc/engines` directory?

Apart from these details I think the main question I is if we want to be able to update/version these engines separately from the norns stack (ie the rest of this repo) or not?

**Comment by tehn** [comment]
you're right of course re: the paths, i'd forgotten

i'd prefer not to sync version control with the norns repo, now that you mention it. need to think on it further.

**Comment by simonvanderveldt** [comment]
A simple/short term fix/change could be to either include the projects that carry these engines (i.e. "we" and "awake") in the "base" catalog or alternatively move only the engines from these projects into a new repo and include that new repo in the base catalog.

With "base" catalog I mean this one https://github.com/monome/norns-community/blob/master/base.json

**Comment by tehn** [comment]
we're going to move to .scd files which means all engines can be included per script (this is preferable in general, so different versions can exist across scripts)
