### ISSUE TITLE
SAMBA with MacOS adds invisible files 

### ISSUE THREAD

**Issue by okyeron** [monome/norns#974]
Reference [this lines thread](https://llllllll.co/t/norns-help/14016/2220)

when uploading files from MacOS with SAMBA (and apparently SFTP from the finder) - "invisible" files with the prefix `._` are created and then are listed in the norns menu file select.

possible fix:
[scandir](https://github.com/monome/norns/blob/3eda4c08b1fb6d47721495ac07a68617e6bf7b9b/lua/lib/util.lua#L27) could be updated with either of these flags for `ls` to ignore listing those files:

```
--hide=PATTERN
              do not list implied entries matching shell PATTERN (overridden by -a or -A)

-I, --ignore=PATTERN
              do not list implied entries matching shell PATTERN
```

**Comment by tehn** [comment]
did you test this? i'd be curious to see your updated code

**Comment by okyeron** [comment]
Ok - did some testing. I was barking up the wrong tree.

SELECT menu is using [this chunk ](https://github.com/monome/norns/blob/093643680862505aa3f954f077f61bce7c0fbca6/lua/core/menu/select.lua#L36) from select.lua

Patching that to 
```
  norns.system_cmd('find ~/dust/code/ -name "[!^.]*" -name "*.lua" | sort', sort_select_tree)
```
eliminates the dot files from the select menu.

**Comment by tehn** [comment]
solved with samba setup. see forum. update forthcoming.
