### ISSUE TITLE
revive command-line maiden

### ISSUE THREAD

**Issue by tehn** [monome/norns#978]
code is here: https://github.com/monome/norns/tree/master/maiden

needs to be updated to use WS instead of IPC

**Comment by ngwese** [comment]
I’m willing to take this on. I was actually wanting this as well just two days ago!

**Comment by tehn** [comment]
i made an attempt a couple months ago and the nanomsg bits really tripped me up--- it's been a long time since i got the ws tests working.

i can try to go way back in the git history to find some of the ws-test code which may shed light on all this.

**Comment by tehn** [comment]
here's the spot in history where `ws-test` is working

https://github.com/monome/norns/tree/c6a687177ec6be48196910ada98b8f66e156b78e/ws-test
